package com.leetcode.backend.config;

import com.leetcode.backend.model.*;
import com.leetcode.backend.repository.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import java.util.*;

/** The published Verdixa practice catalog.  It is deliberately idempotent: rows are keyed by title. */
@Configuration
public class VerdixaProblemCatalogSeeder {
    static record Case(String arguments, String expected, boolean hidden) {}
    static record Spec(String title, String difficulty, String tags, String description, String constraints,
                       String input, String output, String examples, String name, String returns,
                       String[][] parameters, List<Case> cases, String[] hints) {}

    @Bean @Order(110) CommandLineRunner verdixaProblemCatalog(ProblemRepository problems, TestCaseRepository tests,
            ProblemHintRepository hints, PlatformTransactionManager transactionManager) {
        TransactionTemplate transaction = new TransactionTemplate(transactionManager);
        return args -> transaction.executeWithoutResult(status -> seed(problems, tests, hints));
    }

    void seed(ProblemRepository problems, TestCaseRepository tests, ProblemHintRepository hints) {
        Set<String> existing = new HashSet<>();
        problems.findAll().forEach(p -> existing.add(p.getTitle().trim().toLowerCase(Locale.ROOT)));
        for (Spec spec : catalog()) {
            if (existing.contains(spec.title.toLowerCase(Locale.ROOT))) continue;
            Problem problem = new Problem();
            problem.setTitle(spec.title); problem.setDifficulty(spec.difficulty); problem.setTags(spec.tags);
            problem.setDescription(spec.description); problem.setConstraints(spec.constraints);
            problem.setInputFormat(spec.input); problem.setOutputFormat(spec.output); problem.setExamples(spec.examples);
            problem.setActive(true); problem.setExecutionMode(ExecutionMode.FUNCTION);
            problem.setFunctionSignature(signature(spec)); problem.setStarterCode(starters(spec));
            problem = problems.save(problem);
            for (Case c : spec.cases) { TestCase t = new TestCase(); t.setProblem(problem); t.setInputData(c.arguments); t.setFunctionArguments(c.arguments); t.setExpectedOutput(c.expected); t.setHidden(c.hidden); tests.save(t); }
            for (int i=0;i<spec.hints.length;i++) { ProblemHint h=new ProblemHint(); h.setProblem(problem); h.setTitle("Hint " + (i+1)); h.setContent(spec.hints[i]); h.setDisplayOrder(i+1); h.setPenaltyPoints((i+1)*5); h.setActive(true); hints.save(h); }
        }
    }

    static FunctionSignature signature(Spec s) {
        FunctionSignature f=new FunctionSignature(); f.setFunctionName(s.name); f.setReturnType(s.returns);
        List<FunctionParameter> values=new ArrayList<>();
        for(int i=0;i<s.parameters.length;i++){ FunctionParameter p=new FunctionParameter(); p.setName(s.parameters[i][0]); p.setType(s.parameters[i][1]); p.setParameterOrder(i); values.add(p); }
        f.setParameters(values); return f;
    }
    static String starters(Spec s) {
        StringBuilder j=new StringBuilder("public ").append(javaType(s.returns)).append(' ').append(s.name).append('(');
        StringBuilder c=new StringBuilder(cppType(s.returns)).append(' ').append(s.name).append('(');
        List<String> py=new ArrayList<>();
        for(int i=0;i<s.parameters.length;i++){ if(i>0){j.append(", ");c.append(", ");} j.append(javaType(s.parameters[i][1])).append(' ').append(s.parameters[i][0]); c.append(cppType(s.parameters[i][1])).append(' ').append(s.parameters[i][0]); py.add(s.parameters[i][0]); }
        j.append(") {\n    throw new UnsupportedOperationException(\"Implement the method\");\n}");
        c.append(") {\n    throw runtime_error(\"Implement the function\");\n}");
        String python="def "+snake(s.name)+"("+String.join(", ",py)+"):\n    raise NotImplementedError(\"Implement the function\")";
        return "{\"java\":"+quote(j.toString())+",\"cpp\":"+quote(c.toString())+",\"python\":"+quote(python)+"}";
    }
    private static String quote(String s){return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n")+"\"";}
    private static String snake(String s){return s.replaceAll("([a-z0-9])([A-Z])", "$1_$2").toLowerCase(Locale.ROOT);}
    private static String javaType(String t){return t;}
    private static String cppType(String t){return switch(t){case "int","Integer"->"int";case "long"->"long long";case "boolean"->"bool";case "String"->"string";case "int[]"->"vector<int>";case "String[]"->"vector<string>";default->t;};}
    private static Case p(String a,String e){return new Case(a,e,false);} private static Case h(String a,String e){return new Case(a,e,true);}

    static List<Spec> catalog() { return List.of(
        s("Missing Beacon Index","EASY","arrays,math,bit-manipulation","A beacon registry contains every identifier from 0 through n except one. Return the missing identifier.","nums has n distinct values in [0,n].","nums is an integer array.","Return the missing integer.","[3,0,1] -> 2\n[0,1] -> 2","missingBeacon","int",a("nums","int[]"),cs(p("[[3,0,1]]","2"),p("[[0,1]]","2"),h("[[9,6,4,2,3,5,7,0,1]]","8"),h("[[0]]","1"),h("[[1]]","0"),h("[[2,0]]","1")),hs("The values represent a complete range with exactly one gap.","Compare the expected range sum with the actual sum, or cancel values with XOR.","Compute n*(n+1)/2 and subtract every array value.")),
        s("Letter Inventory Match","EASY","strings,hash-map","Determine whether two lowercase inventory labels contain exactly the same letters with the same frequencies.","Both strings contain lowercase English letters and have length at most 100000.","Two strings s and t.","Return true when they are anagrams.","\"listen\", \"silent\" -> true\n\"rat\", \"car\" -> false","letterInventoryMatch","boolean",a("s","String","t","String"),cs(p("[\"listen\",\"silent\"]","true"),p("[\"rat\",\"car\"]","false"),h("[\"aacc\",\"ccac\"]","false"),h("[\"\",\"\"]","true"),h("[\"anagram\",\"nagaram\"]","true"),h("[\"ab\",\"a\"]","false")),hs("Only letter counts matter, not their positions.","Track each character's frequency while scanning the strings.","Increment for one string and decrement for the other; every final count must be zero.")),
        s("Stable Zero Shift","EASY","arrays,two-pointers","Move every zero to the end of nums while preserving the relative order of nonzero values. Return the resulting array.","1 <= nums.length <= 100000; values fit in int.","An integer array nums.","Return nums after the stable shift.","[0,1,0,3,12] -> [1,3,12,0,0]\n[0] -> [0]","stableZeroShift","int[]",a("nums","int[]"),cs(p("[[0,1,0,3,12]]","[1,3,12,0,0]"),p("[[0]]","[0]"),h("[[1,2,3]]","[1,2,3]"),h("[[0,0,1]]","[1,0,0]"),h("[[-1,0,-2,0]]","[-1,-2,0,0]"),h("[[0,0]]","[0,0]")),hs("Keep one position for the next nonzero value.","A write pointer can compact nonzeros in one pass.","Write nonzeros in order, then fill the remaining positions with zero.")),
        s("Bracket Balance Check","EASY","stack,strings","Return whether every opening bracket in a string is closed by the matching bracket in the correct order.","s contains only (), [], and {}; length at most 100000.","A bracket string s.","Return true for a balanced string.","\"()[]{}\" -> true\n\"([)]\" -> false","bracketBalance","boolean",a("s","String"),cs(p("[\"()[]{}\"]","true"),p("[\"([)]\"]","false"),h("[\"{[]}\"]","true"),h("[\"(]\"]","false"),h("[\"\"]","true"),h("[\"(((\"]","false")),hs("Nested openings must be closed in reverse order.","Use a stack to remember unmatched opening brackets.","On a closing bracket, require a nonempty stack whose top is its matching opener.")),
        s("Longest Run of Ones","EASY","arrays,sliding-window","Find the length of the longest contiguous run of 1 values in a binary array.","1 <= nums.length <= 100000; each value is 0 or 1.","A binary integer array nums.","Return the maximum run length.","[1,1,0,1,1,1] -> 3\n[0,0] -> 0","longestRunOfOnes","int",a("nums","int[]"),cs(p("[[1,1,0,1,1,1]]","3"),p("[[0,0]]","0"),h("[[1]]","1"),h("[[1,1,1,1]]","4"),h("[[0,1,1,0,1]]","2"),h("[[0]]","0")),hs("A zero ends the current run.","Maintain a running count and reset it when you see zero.","Update the best length after extending each run of ones.")),
        s("Sorted Target Locator","EASY","binary-search,arrays","Given a nondecreasing sorted array, return any index containing target, or -1 when it is absent.","nums.length <= 100000; values fit in int.","A sorted integer array nums and integer target.","Return an index or -1.","[-1,0,3,5,9,12], 9 -> 4\n[-1,0,3,5,9,12], 2 -> -1","sortedTargetLocator","int",a("nums","int[]","target","int"),cs(p("[[-1,0,3,5,9,12],9]","4"),p("[[-1,0,3,5,9,12],2]","-1"),h("[[5],5]","0"),h("[[5],-5]","-1"),h("[[1,2,2,2,3],2]","2"),h("[[],1]","-1")),hs("The array ordering lets you discard half of the search range.","Keep inclusive low and high indices around the remaining candidate range.","Compare nums[mid] to target and move exactly one boundary past mid.")),
        s("Unique Window Length","MEDIUM","strings,sliding-window,hash-map","Return the length of the longest substring that contains no repeated character.","s.length <= 100000; s uses printable ASCII characters.","A string s.","Return the maximum valid window length.","\"abcabcbb\" -> 3\n\"bbbbb\" -> 1","uniqueWindowLength","int",a("s","String"),cs(p("[\"abcabcbb\"]","3"),p("[\"bbbbb\"]","1"),h("[\"pwwkew\"]","3"),h("[\"\"]","0"),h("[\"abba\"]","2"),h("[\"dvdf\"]","3")),hs("A repeated character only invalidates part of the current window.","Record the most recent index of each character.","Move the left boundary just beyond a repeated character when it lies inside the current window.")),
        s("Product Without Position","MEDIUM","arrays,prefix-sum","For every index, return the product of all other elements without using division.","2 <= nums.length <= 100000; every prefix and suffix product fits in int.","An integer array nums.","Return the product array.","[1,2,3,4] -> [24,12,8,6]\n[-1,1,0,-3,3] -> [0,0,9,0,0]","productWithoutPosition","int[]",a("nums","int[]"),cs(p("[[1,2,3,4]]","[24,12,8,6]"),p("[[-1,1,0,-3,3]]","[0,0,9,0,0]"),h("[[2,3]]","[3,2]"),h("[[0,0]]","[0,0]"),h("[[1,1,1]]","[1,1,1]"),h("[[-1,-1,-1]]","[1,1,1]")),hs("Each answer is a product to its left times a product to its right.","Store prefix products in the result, then sweep backward with a suffix product.","On the reverse pass multiply result[i] by the suffix before extending that suffix with nums[i].")),
        s("Frequency Crown","MEDIUM","hash-map,heap,priority-queue","Return the k most frequent values. Break equal frequencies by smaller numeric value first so the result is deterministic.","1 <= k <= number of distinct values; nums.length <= 100000.","An integer array nums and integer k.","Return k values in descending frequency, then ascending value.","[1,1,1,2,2,3], 2 -> [1,2]\n[4,4,1,1,2], 2 -> [1,4]","frequencyCrown","int[]",a("nums","int[]","k","int"),cs(p("[[1,1,1,2,2,3],2]","[1,2]"),p("[[4,4,1,1,2],2]","[1,4]"),h("[[1],1]","[1]"),h("[[-1,-1,2,2,2,3],2]","[2,-1]"),h("[[5,5,4,4,3,3],3]","[3,4,5]"),h("[[9,9,8,7,7,7],1]","[7]")),hs("Count occurrences before deciding which values survive.","A heap or a sort over distinct values can rank frequency/value pairs.","Order by frequency descending and value ascending, then take the first k.")),
        s("Quiet Street Robber","MEDIUM","dynamic-programming,arrays","Choose house values with no two adjacent houses chosen, maximizing the total amount.","nums.length <= 100000; 0 <= nums[i] <= 10000.","An integer array nums.","Return the largest obtainable sum.","[1,2,3,1] -> 4\n[2,7,9,3,1] -> 12","quietStreetRobber","int",a("nums","int[]"),cs(p("[[1,2,3,1]]","4"),p("[[2,7,9,3,1]]","12"),h("[[]]","0"),h("[[5]]","5"),h("[[2,1,1,2]]","4"),h("[[0,0,0]]","0")),hs("At each house, decide between taking it or preserving the previous best.","The best through i depends only on the best through i-1 and i-2.","Use rolling values: current = max(previous, twoBack + nums[i]).")),
        s("Well-Formed Parenthesis Builder","MEDIUM","recursion,backtracking,strings","Generate every well-formed parenthesis string containing exactly n pairs, in lexicographic construction order: add '(' before ')'.","0 <= n <= 8.","An integer n.","Return all valid strings in construction order.","3 -> [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]\n1 -> [\"()\"]","wellFormedParenthesisBuilder","String[]",a("n","int"),cs(p("[3]","[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]"),p("[1]","[\"()\"]"),h("[0]","[\"\"]"),h("[2]","[\"(())\",\"()()\"]"),h("[4]","[\"(((())))\",\"((()()))\",\"((())())\",\"((()))()\",\"(()(()))\",\"(()()())\",\"(()())()\",\"(())(())\",\"(())()()\",\"()((()))\",\"()(()())\",\"()(())()\",\"()()(())\",\"()()()()\"]"),h("[1]","[\"()\"]")),hs("A partial string is valid only if it never has more closes than opens.","Backtrack with counts of opening and closing brackets used.","Add '(' while opens < n; add ')' only while closes < opens; emit at length 2n.")),
        s("Prerequisite Route Check","MEDIUM","graphs,dfs,topological-sort","Courses are numbered 0 through courseCount-1. Each string in prerequisites is \"course,prerequisite\". Return whether every course can be completed.","0 <= courseCount <= 2000; each entry is two valid comma-separated course ids.","courseCount and a String[] prerequisites.","Return false exactly when a prerequisite cycle exists.","2, [\"1,0\"] -> true\n2, [\"1,0\",\"0,1\"] -> false","prerequisiteRouteCheck","boolean",a("courseCount","int","prerequisites","String[]"),cs(p("[2,[\"1,0\"]]","true"),p("[2,[\"1,0\",\"0,1\"]]","false"),h("[1,[]]","true"),h("[3,[\"1,0\",\"2,1\"]]","true"),h("[3,[\"1,0\",\"2,1\",\"0,2\"]]","false"),h("[4,[\"1,0\",\"3,2\"]]","true")),hs("The only obstruction is a circular dependency.","Model prerequisites as directed edges and track each node's in-degree or DFS state.","Repeatedly remove zero-in-degree courses; completion is possible iff all courses are removed.")),
        s("Daily Temperature Wait","MEDIUM","stack,arrays","For each day, return how many days must pass until a warmer temperature. Return 0 when none exists.","1 <= temperatures.length <= 100000; temperatures are integers.","An integer array temperatures.","Return the wait array.","[73,74,75,71,69,72,76,73] -> [1,1,4,2,1,1,0,0]\n[30,40,50,60] -> [1,1,1,0]","dailyTemperatureWait","int[]",a("temperatures","int[]"),cs(p("[[73,74,75,71,69,72,76,73]]","[1,1,4,2,1,1,0,0]"),p("[[30,40,50,60]]","[1,1,1,0]"),h("[[30,60,90]]","[1,1,0]"),h("[[90,80,70]]","[0,0,0]"),h("[[70]]","[0]"),h("[[70,70,71]]","[2,1,0]")),hs("A day waits for the next greater value to its right.","Keep indices whose temperatures have not yet found a warmer day in a decreasing stack.","When a warmer temperature arrives, pop every colder index and set its distance.")),
        s("Circular Fuel Departure","MEDIUM","greedy,arrays","At station i you gain fuel[i] and spend cost[i] to reach the next station. Return the unique start index that completes one full circuit, or -1 when no circuit is possible.","fuel and cost have equal length up to 100000; all values are nonnegative.","Two integer arrays fuel and cost.","Return a valid starting index or -1.","[1,2,3,4,5], [3,4,5,1,2] -> 3\n[2,3,4], [3,4,3] -> -1","circularFuelDeparture","int",a("fuel","int[]","cost","int[]"),cs(p("[[1,2,3,4,5],[3,4,5,1,2]]","3"),p("[[2,3,4],[3,4,3]]","-1"),h("[[5],[4]]","0"),h("[[1],[2]]","-1"),h("[[2,2,2],[1,3,1]]","0"),h("[[3,1,1],[1,2,2]]","0")),hs("A valid circuit needs at least as much total fuel as total cost.","If a running tank becomes negative, none of the starts since the current candidate can work.","Reset the candidate to the next station after a negative tank; return it only when total balance is nonnegative.")),
        s("Rainwater Basin","HARD","arrays,two-pointers,stack","Given wall heights, return how many units of rainwater are trapped after rainfall.","heights.length <= 100000; 0 <= heights[i] <= 100000.","An integer array heights.","Return total trapped water.","[0,1,0,2,1,0,1,3,2,1,2,1] -> 6\n[4,2,0,3,2,5] -> 9","rainwaterBasin","int",a("heights","int[]"),cs(p("[[0,1,0,2,1,0,1,3,2,1,2,1]]","6"),p("[[4,2,0,3,2,5]]","9"),h("[[]]","0"),h("[[1,2,3]]","0"),h("[[3,0,3]]","3"),h("[[5,4,1,2]]","1")),hs("Water above a position is bounded by the shorter of its best left and right walls.","Two pointers can maintain the greatest wall seen from each side.","Advance the side with the smaller current maximum and add its maximum minus the current height.")),
        s("Histogram Skyline","HARD","stack,arrays,monotonic-stack","Return the largest rectangular area that can be formed under a histogram with unit-width bars.","heights.length <= 100000; 0 <= heights[i] <= 100000.","An integer array heights.","Return the maximum area.","[2,1,5,6,2,3] -> 10\n[2,4] -> 4","histogramSkyline","int",a("heights","int[]"),cs(p("[[2,1,5,6,2,3]]","10"),p("[[2,4]]","4"),h("[[]]","0"),h("[[2,1,2]]","3"),h("[[1,1,1,1]]","4"),h("[[6,2,5,4,5,1,6]]","12")),hs("For each bar, find the widest interval where it is the shortest bar.","Maintain indices of increasing heights in a monotonic stack.","Append a virtual zero-height bar; when a lower bar appears, pop and compute width to the new stack top.")),
        s("String Transformation Cost","HARD","dynamic-programming,strings","Return the minimum number of insertions, deletions, and replacements needed to transform source into target.","source and target have length at most 500.","Two strings source and target.","Return the edit distance.","\"horse\", \"ros\" -> 3\n\"intention\", \"execution\" -> 5","stringTransformationCost","int",a("source","String","target","String"),cs(p("[\"horse\",\"ros\"]","3"),p("[\"intention\",\"execution\"]","5"),h("[\"\",\"abc\"]","3"),h("[\"abc\",\"abc\"]","0"),h("[\"kitten\",\"sitting\"]","3"),h("[\"a\",\"\"]","1")),hs("Consider the answer for prefixes of the two strings.","Use a DP table where dp[i][j] transforms the first i source characters into the first j target characters.","Matching last characters copy the diagonal; otherwise take one plus min(replace, delete, insert).")),
        s("Smallest Covering Window","HARD","strings,sliding-window,hash-map","Return the shortest substring of source that contains every character of target with at least its target multiplicity. Return an empty string if impossible.","source and target length are at most 100000; both use ASCII characters.","Two strings source and target.","Return the shortest covering substring.","\"ADOBECODEBANC\", \"ABC\" -> \"BANC\"\n\"a\", \"aa\" -> \"\"","smallestCoveringWindow","String",a("source","String","target","String"),cs(p("[\"ADOBECODEBANC\",\"ABC\"]","\"BANC\""),p("[\"a\",\"aa\"]","\"\""),h("[\"a\",\"a\"]","\"a\""),h("[\"aa\",\"aa\"]","\"aa\""),h("[\"ab\",\"b\"]","\"b\""),h("[\"abc\",\"z\"]","\"\"")),hs("A valid window must satisfy character counts, then should be shrunk as much as possible.","Keep required counts and a moving window count map.","Expand right until all requirements are met; then advance left while validity remains, recording the best window.")),
        s("Word Mutation Steps","HARD","graphs,bfs,strings","Words have equal length. Change one character at a time, and every intermediate word must be in dictionary. Return the number of words in the shortest sequence from beginWord to endWord, or 0.","At most 5000 lowercase words of length at most 10.","beginWord, endWord, and String[] dictionary.","Return the shortest sequence length.","\"hit\", \"cog\", [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"] -> 5\n\"hit\", \"cog\", [\"hot\",\"dot\",\"dog\",\"lot\",\"log\"] -> 0","wordMutationSteps","int",a("beginWord","String","endWord","String","dictionary","String[]"),cs(p("[\"hit\",\"cog\",[\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]]","5"),p("[\"hit\",\"cog\",[\"hot\",\"dot\",\"dog\",\"lot\",\"log\"]]","0"),h("[\"a\",\"c\",[\"a\",\"b\",\"c\"]]","2"),h("[\"same\",\"same\",[\"same\"]]","1"),h("[\"lost\",\"cost\",[\"most\",\"fist\",\"lost\",\"cost\",\"fish\"]]","2"),h("[\"red\",\"tax\",[\"ted\",\"tex\",\"red\",\"tax\",\"tad\",\"den\",\"rex\",\"pee\"]]","4")),hs("Each word is a graph node, with one-letter mutations as edges.","Breadth-first search discovers the fewest mutations first; use a set for dictionary membership.","For each dequeued word, try every letter at every position and enqueue unseen dictionary words.")),
        s("Queen Board Counter","HARD","backtracking,recursion,bit-manipulation","Count placements of n queens on an n by n board so that no two queens attack each other.","0 <= n <= 12.","An integer n.","Return the number of valid boards.","4 -> 2\n1 -> 1","queenBoardCounter","int",a("n","int"),cs(p("[4]","2"),p("[1]","1"),h("[0]","1"),h("[2]","0"),h("[3]","0"),h("[8]","92")),hs("Place one queen in each row, avoiding previously attacked columns and diagonals.","Track used columns, main diagonals, and anti-diagonals during backtracking.","At row r, try every safe column; recurse to r+1 and undo the marks after each choice.")),
        s("Majority Signal","EASY","arrays,hash-map,voting,counting","A monitoring stream contains a value that appears more than half the time. Return that value.","1 <= nums.length <= 100000; a majority value always exists.","An integer array nums.","Return the majority value.","[2,2,1,2] -> 2\n[7] -> 7","majoritySignal","int",a("nums","int[]"),cs(p("[[2,2,1,2]]","2"),p("[[7]]","7"),h("[[3,3,4]]","3"),h("[[-1,-1,-1,2,2]]","-1"),h("[[0,0,1,0,2]]","0"),h("[[5,5,5,5,4,4,4]]","5")),hs("A majority cannot be fully cancelled by all other values combined.","Keep a candidate and a balance that rises for the candidate and falls for another value.","When balance reaches zero choose the current value as a new candidate; the final candidate is the majority.")),
        s("Prefix Balance Point","EASY","arrays,prefix-sum","Return the first index whose values strictly to the left and strictly to the right have equal sums, or -1 when none exists.","0 <= nums.length <= 100000; values fit in int and sums fit in long.","An integer array nums.","Return the first balancing index or -1.","[1,7,3,6,5,6] -> 3\n[1,2,3] -> -1","prefixBalancePoint","int",a("nums","int[]"),cs(p("[[1,7,3,6,5,6]]","3"),p("[[1,2,3]]","-1"),h("[[2,1,-1]]","0"),h("[[0]]","0"),h("[[]]","-1"),h("[[-1,-1,0,1,1]]","-1")),hs("The total can be split into what has already been passed and what remains.","Compute the total once, then maintain a running left sum.","At each index, right is total minus left minus current; compare it before adding current to left.")),
        s("Single Number Trace","EASY","arrays,bit-manipulation,xor","Every value in nums appears exactly twice except one value. Return the unmatched value.","1 <= nums.length <= 100000; values fit in int.","An integer array nums.","Return the value occurring once.","[4,1,2,1,2] -> 4\n[9] -> 9","singleNumberTrace","int",a("nums","int[]"),cs(p("[[4,1,2,1,2]]","4"),p("[[9]]","9"),h("[[-1,-1,-7]]","-7"),h("[[0,5,0]]","5"),h("[[2,3,2,3,8]]","8"),h("[[100,100,42]]","42")),hs("Pairs have a useful cancellation property.","XORing a value with itself removes it, and XOR is order independent.","XOR every element into one accumulator; duplicate pairs vanish and leave the unique value.")),
        s("First Unique Symbol","EASY","strings,hash-map,frequency-counting","Return the index of the first character in s that occurs exactly once, or -1 if every character repeats.","0 <= s.length <= 100000; s contains ASCII characters.","A string s.","Return the first unique index or -1.","\"verdixa\" -> 0\n\"aabb\" -> -1","firstUniqueSymbol","int",a("s","String"),cs(p("[\"verdixa\"]","0"),p("[\"aabb\"]","-1"),h("[\"leetcode\"]","0"),h("[\"loveleetcode\"]","2"),h("[\"\"]","-1"),h("[\"z\"]","0")),hs("You need both frequency information and the original order.","Count every character first, then scan the string again from left to right.","The first position whose stored count is one is the answer.")),
        s("Rotated Array Locator","MEDIUM","binary-search,arrays","A strictly increasing array was rotated at an unknown pivot. Return the index of target, or -1 when absent.","0 <= nums.length <= 100000; all nums values are distinct.","An integer array nums and integer target.","Return the target index or -1.","[4,5,6,7,0,1,2], 0 -> 4\n[4,5,6,7,0,1,2], 3 -> -1","rotatedArrayLocator","int",a("nums","int[]","target","int"),cs(p("[[4,5,6,7,0,1,2],0]","4"),p("[[4,5,6,7,0,1,2],3]","-1"),h("[[1],1]","0"),h("[[1],0]","-1"),h("[[6,7,1,2,3,4,5],4]","5"),h("[[3,1],3]","0")),hs("At any midpoint, one half is still normally sorted.","Check which half is sorted, then decide whether the target belongs in that value range.","Discard the half that cannot contain target and continue like ordinary binary search.")),
        s("Peak Terrain Index","MEDIUM","binary-search,arrays","A terrain array rises to one peak and then falls. Return the index of its peak.","3 <= heights.length <= 100000; adjacent values differ; a unique peak exists.","An integer array heights.","Return the peak index.","[1,3,5,4,2] -> 2\n[0,2,1] -> 1","peakTerrainIndex","int",a("heights","int[]"),cs(p("[[1,3,5,4,2]]","2"),p("[[0,2,1]]","1"),h("[[1,2,3,4,3]]","3"),h("[[9,7,5,3]]","0"),h("[[1,2,3,4,5]]","4"),h("[[2,5,4,1]]","1")),hs("The slope at a midpoint tells you which side can still contain a peak.","Compare heights[mid] with heights[mid + 1] instead of searching for an exact value.","If the slope rises, keep the right side; otherwise keep mid and the left side.")),
        s("Minimum Capacity Scheduler","MEDIUM","binary-search-on-answer,greedy,arrays","Packages must be shipped in order within a fixed number of days. Return the smallest daily capacity that can finish the schedule.","1 <= weights.length <= 50000; 1 <= days <= weights.length.","An integer array weights and integer days.","Return the minimum capacity.","[1,2,3,1,1], 4 -> 3\n[3,2,2,4,1,4], 3 -> 6","minimumCapacityScheduler","int",a("weights","int[]","days","int"),cs(p("[[1,2,3,1,1],4]","3"),p("[[3,2,2,4,1,4],3]","6"),h("[[1,2,3,4,5,6,7,8,9,10],5]","15"),h("[[10],1]","10"),h("[[5,5,5],1]","15"),h("[[5,5,5],3]","5")),hs("Capacity is feasible in a monotonic way: a larger capacity never needs more days.","For a proposed capacity, greedily load packages until the next one would exceed it.","Binary search from the heaviest package to the total weight using that day-count check.")),
        s("Kth Largest Stream Value","MEDIUM","heap,priority-queue,arrays","Return the kth largest value in nums. Duplicate values count as separate stream entries.","1 <= k <= nums.length <= 100000.","An integer array nums and integer k.","Return the kth largest value.","[3,2,1,5,6,4], 2 -> 5\n[3,2,3,1,2,4,5,5,6], 4 -> 4","kthLargestStreamValue","int",a("nums","int[]","k","int"),cs(p("[[3,2,1,5,6,4],2]","5"),p("[[3,2,3,1,2,4,5,5,6],4]","4"),h("[[1],1]","1"),h("[[-1,-5,0],2]","-1"),h("[[2,2,2],2]","2"),h("[[9,8,7],3]","7")),hs("You only need to preserve the best k candidates seen so far.","Use a min-heap of size at most k; its top is the weakest kept candidate.","Push each value, remove the minimum when the heap exceeds k, then return the heap top.")),
        s("Merge Time Blocks","MEDIUM","intervals,sorting,arrays","Each String entry is \"start,end\" for a closed time block. Merge overlapping or touching blocks and return them in ascending order using the same format.","0 <= blocks.length <= 10000; 0 <= start <= end <= 100000.","A String[] of comma-separated intervals.","Return merged interval strings.","[\"1,3\",\"2,6\",\"8,10\"] -> [\"1,6\",\"8,10\"]\n[] -> []","mergeTimeBlocks","String[]",a("blocks","String[]"),cs(p("[[\"1,3\",\"2,6\",\"8,10\"]]","[\"1,6\",\"8,10\"]"),p("[[]]","[]"),h("[[\"1,4\",\"4,5\"]]","[\"1,5\"]"),h("[[\"5,7\",\"1,2\"]]","[\"1,2\",\"5,7\"]"),h("[[\"1,10\",\"2,3\",\"4,8\"]]","[\"1,10\"]"),h("[[\"2,2\"]]","[\"2,2\"]")),hs("Once intervals are ordered by start, only the most recent merged interval can overlap the next one.","Parse and sort blocks by start, keeping a current merged start and end.","Extend the current end when the next start is at most it; otherwise emit it and begin a new block.")),
        s("Minimum Meeting Rooms","MEDIUM","intervals,heap,sorting","Each String entry is \"start,end\" for a half-open meeting interval [start,end). Return the minimum number of rooms needed.","0 <= meetings.length <= 10000; 0 <= start < end <= 100000.","A String[] of comma-separated intervals.","Return the required room count.","[\"0,30\",\"5,10\",\"15,20\"] -> 2\n[\"7,10\",\"10,12\"] -> 1","minimumMeetingRooms","int",a("meetings","String[]"),cs(p("[[\"0,30\",\"5,10\",\"15,20\"]]","2"),p("[[\"7,10\",\"10,12\"]]","1"),h("[[]]","0"),h("[[\"1,2\",\"1,2\",\"1,2\"]]","3"),h("[[\"1,5\",\"2,3\",\"3,4\"]]","2"),h("[[\"4,9\"]]","1")),hs("A room becomes reusable as soon as its meeting end is no later than the next start.","Sort by start time and track active end times in a min-heap.","Before adding a meeting, remove every end time at most its start; the largest heap size is the answer.")),
        s("Next Greater Circular Value","MEDIUM","monotonic-stack,arrays,circular-array","For each value, return the first greater value encountered while moving right and wrapping once, or -1.","1 <= nums.length <= 100000; values fit in int.","An integer array nums.","Return an integer array of next greater values.","[1,2,1] -> [2,-1,2]\n[3,2,1] -> [-1,3,3]","nextGreaterCircularValue","int[]",a("nums","int[]"),cs(p("[[1,2,1]]","[2,-1,2]"),p("[[3,2,1]]","[-1,3,3]"),h("[[1]]","[-1]"),h("[[2,2,2]]","[-1,-1,-1]"),h("[[5,4,3,2,1]]","[-1,5,5,5,5]"),h("[[1,5,3,6,8]]","[5,6,6,8,-1]")),hs("A value waits for the first larger value that appears after it in circular order.","Maintain indices with unresolved answers in decreasing value order.","Traverse two array lengths using modulo indices; a new value resolves all smaller stack values.")),
        s("Sliding Window Maximum","MEDIUM","monotonic-deque,sliding-window,arrays","Return the maximum value in every contiguous window of length k.","1 <= k <= nums.length <= 100000.","An integer array nums and integer k.","Return window maxima in order.","[1,3,-1,-3,5,3,6,7], 3 -> [3,3,5,5,6,7]\n[1], 1 -> [1]","slidingWindowMaximum","int[]",a("nums","int[]","k","int"),cs(p("[[1,3,-1,-3,5,3,6,7],3]","[3,3,5,5,6,7]"),p("[[1],1]","[1]"),h("[[1,2,3],1]","[1,2,3]"),h("[[1,2,3],3]","[3]"),h("[[7,7,7],2]","[7,7]"),h("[[-1,-3,-2],2]","[-1,-2]")),hs("The maximum only changes when it leaves the window or a larger value arrives.","Store candidate indices in a deque with values decreasing from front to back.","Remove expired front indices, remove smaller values from the back, then the front is each window maximum.")),
        s("Subarray Target Count","MEDIUM","prefix-sum,hash-map,arrays","Return how many contiguous subarrays have sum exactly target.","nums.length <= 100000; values and answer fit in int.","An integer array nums and integer target.","Return the number of matching subarrays.","[1,1,1], 2 -> 2\n[1,-1,0], 0 -> 3","subarrayTargetCount","int",a("nums","int[]","target","int"),cs(p("[[1,1,1],2]","2"),p("[[1,-1,0],0]","3"),h("[[0,0,0],0]","6"),h("[[3,4,7,2,-3,1,4,2],7]","4"),h("[[-1,-1,1],0]","1"),h("[[],0]","0")),hs("A subarray sum can be expressed as the difference of two prefix sums.","For current prefix sum p, count how often p-target has appeared before.","Start the frequency map with prefix sum zero once, add matches before recording the current prefix.")),
        s("Longest Consecutive Chain","MEDIUM","hash-set,arrays","Return the length of the longest run of consecutive integer values present in nums, regardless of input order.","0 <= nums.length <= 100000; values fit in int.","An integer array nums.","Return the longest chain length.","[100,4,200,1,3,2] -> 4\n[0,3,7,2,5,8,4,6,0,1] -> 9","longestConsecutiveChain","int",a("nums","int[]"),cs(p("[[100,4,200,1,3,2]]","4"),p("[[0,3,7,2,5,8,4,6,0,1]]","9"),h("[[]]","0"),h("[[1]]","1"),h("[[1,2,0,1]]","3"),h("[[-2,-1,0,5]]","3")),hs("A consecutive run has one value with no predecessor.","Put all values in a hash set and only begin expansion from values whose predecessor is absent.","Walk forward from each run start; every set value is expanded from at most one start.")),
        s("Coin Combination Minimum","MEDIUM","dynamic-programming,arrays","Return the fewest coins needed to make amount, or -1 if no exact combination exists.","1 <= coins.length <= 100; 0 <= amount <= 10000; coin values are positive.","An integer array coins and integer amount.","Return the minimum count or -1.","[1,2,5], 11 -> 3\n[2], 3 -> -1","coinCombinationMinimum","int",a("coins","int[]","amount","int"),cs(p("[[1,2,5],11]","3"),p("[[2],3]","-1"),h("[[1],0]","0"),h("[[2,5,10,1],27]","4"),h("[[186,419,83,408],6249]","20"),h("[[2],0]","0")),hs("The best way to form an amount can be built from a smaller amount after choosing one coin.","Let dp[x] be the fewest coins for x, initialized as unreachable except dp[0].","For each amount, try every coin not exceeding it and relax from dp[amount-coin].")),
        s("Increasing Sequence Length","MEDIUM","dynamic-programming,binary-search,arrays","Return the length of the longest strictly increasing subsequence of nums.","0 <= nums.length <= 100000; values fit in int.","An integer array nums.","Return the maximum subsequence length.","[10,9,2,5,3,7,101,18] -> 4\n[7,7,7] -> 1","increasingSequenceLength","int",a("nums","int[]"),cs(p("[[10,9,2,5,3,7,101,18]]","4"),p("[[7,7,7]]","1"),h("[[]]","0"),h("[[0,1,0,3,2,3]]","4"),h("[[4,3,2,1]]","1"),h("[[-1,3,4,5,2,2,2,2]]","4")),hs("A shorter tail is always more promising for extending an increasing subsequence of the same length.","Maintain the smallest possible tail for each subsequence length.","Binary search the first tail that is at least each value; replace it or append when none is large enough.")),
        s("Partition Target Feasibility","MEDIUM","dynamic-programming,subset-sum,arrays","Return whether nums can be split into two groups with equal total sum.","1 <= nums.length <= 200; 0 <= nums[i] <= 100; total sum <= 20000.","An integer array nums.","Return true when an equal partition exists.","[1,5,11,5] -> true\n[1,2,3,5] -> false","partitionTargetFeasibility","boolean",a("nums","int[]"),cs(p("[[1,5,11,5]]","true"),p("[[1,2,3,5]]","false"),h("[[2,2,1,1]]","true"),h("[[1]]","false"),h("[[0,0]]","true"),h("[[3,3,3,4,5]]","true")),hs("Equal groups require finding a subset whose sum is half of the total.","If the total is odd stop early; otherwise track which sums up to half are reachable.","Process each number backward through the reachable-sum array so it cannot be used twice.")),
        s("Decode Message Ways","MEDIUM","dynamic-programming,strings","Digits encode letters using 1 through 26. Return the number of valid full decodings; zero is not a standalone code.","1 <= digits.length <= 100; digits contains only '0' through '9'; result fits in int.","A digit string.","Return the decoding count.","\"226\" -> 3\n\"06\" -> 0","decodeMessageWays","int",a("digits","String"),cs(p("[\"226\"]","3"),p("[\"06\"]","0"),h("[\"12\"]","2"),h("[\"2101\"]","1"),h("[\"11106\"]","2"),h("[\"0\"]","0")),hs("The final one or two digits determine which earlier prefixes can extend.","Track ways for the two previous prefix lengths.","Add the one-digit contribution when nonzero and the two-digit contribution when its value is 10 through 26.")),
        s("Matrix Spiral Reader","MEDIUM","matrix,simulation,arrays","Rows contains equal-length strings. Read their characters in clockwise spiral order and return the resulting string.","0 <= rows.length <= 200; every row has the same length and contains ASCII characters.","A String[] rows representing a character matrix.","Return the spiral traversal string.","[\"abc\",\"def\",\"ghi\"] -> \"abcfihgde\"\n[\"a\"] -> \"a\"","matrixSpiralReader","String",a("rows","String[]"),cs(p("[[\"abc\",\"def\",\"ghi\"]]","\"abcfihgde\""),p("[[\"a\"]]","\"a\""),h("[[]]","\"\""),h("[[\"ab\",\"cd\"]]","\"abdc\""),h("[[\"abcd\"]]","\"abcd\""),h("[[\"a\",\"b\",\"c\"]]","\"abc\"")),hs("A spiral repeatedly consumes the current outer boundary.","Keep top, bottom, left, and right bounds, shrinking one after each directional pass.","Guard the bottom-row and left-column passes after shrinking so a single row or column is not repeated.")),
        s("Connected Region Counter","MEDIUM","graphs,dfs,bfs,matrix","Rows contains '0' water and '1' land. Count four-directionally connected land regions.","0 <= rows.length <= 200; rows have equal length and contain only 0 or 1.","A String[] rows representing a binary grid.","Return the number of regions.","[\"110\",\"010\",\"001\"] -> 2\n[\"000\"] -> 0","connectedRegionCounter","int",a("rows","String[]"),cs(p("[[\"110\",\"010\",\"001\"]]","2"),p("[[\"000\"]]","0"),h("[[]]","0"),h("[[\"1\"]]","1"),h("[[\"11\",\"11\"]]","1"),h("[[\"101\",\"010\",\"101\"]]","5")),hs("Each unvisited land cell can start exactly one complete region exploration.","Use DFS or BFS to mark every four-directionally adjacent land cell reached from a start.","Scan the grid; when you find unvisited land, increment the count and flood-fill it.")),
        s("Median of Two Sorted Sequences","HARD","binary-search,arrays,divide-and-conquer","Return the median of two nondecreasing integer sequences in logarithmic time relative to the shorter sequence.","0 <= a.length + b.length <= 200000; total length is at least 1.","Two sorted integer arrays a and b.","Return the median as a double.","[1,3], [2] -> 2.0\n[1,2], [3,4] -> 2.5","medianOfTwoSortedSequences","double",a("a","int[]","b","int[]"),cs(p("[[1,3],[2]]","2.0"),p("[[1,2],[3,4]]","2.5"),h("[[],[1]]","1.0"),h("[[0,0],[0,0]]","0.0"),h("[[2],[]]","2.0"),h("[[-5,3,6],[1,2,8,10]]","3.0")),hs("Think of choosing a cut in each array so the left side contains half the values.","Binary search the cut in the shorter array and derive the other cut from the required left size.","A valid cut has every left value no larger than every right value; then compute the middle boundary values.")),
        s("Maximum Rectangle in Binary Grid","HARD","matrix,monotonic-stack,dynamic-programming","Rows contains '0' and '1'. Return the largest all-one rectangle area in the grid.","0 <= rows.length <= 200; rows have equal length at most 200.","A String[] rows representing a binary grid.","Return the largest rectangle area.","[\"10100\",\"10111\",\"11111\",\"10010\"] -> 6\n[\"0\"] -> 0","maximumRectangleInBinaryGrid","int",a("rows","String[]"),cs(p("[[\"10100\",\"10111\",\"11111\",\"10010\"]]","6"),p("[[\"0\"]]","0"),h("[[]]","0"),h("[[\"1\"]]","1"),h("[[\"11\",\"11\"]]","4"),h("[[\"101\",\"111\"]]","3")),hs("Each row can be treated as the base of a histogram of consecutive ones above it.","Update a height array per row, resetting height to zero at each zero cell.","For every updated histogram, use an increasing stack to find its largest rectangle and keep the global best.")),
        s("Longest Valid Bracket Segment","HARD","stack,dynamic-programming,strings","Return the length of the longest contiguous substring of properly matched parentheses.","0 <= s.length <= 100000; s contains only '(' and ')'.","A parenthesis string s.","Return the maximum valid length.","\")()())\" -> 4\n\"(()\" -> 2","longestValidBracketSegment","int",a("s","String"),cs(p("[\")()())\"]","4"),p("[\"(()\"]","2"),h("[\"\"]","0"),h("[\"()(()\"]","2"),h("[\"()(())\"]","6"),h("[\"((()))\"]","6")),hs("A valid segment ends at a closing parenthesis and may connect to an earlier valid segment.","A stack of unmatched boundary indices lets you measure valid spans whenever a match closes.","Seed the stack with -1; after a failed close, make that index the new boundary, otherwise use the distance to the current boundary.")),
        s("Burst Value Optimizer","HARD","dynamic-programming,interval-dp","Burst values in any order. Bursting value i earns its current nearest unburst neighbors multiplied together; virtual boundary values are 1. Return the largest total.","1 <= nums.length <= 300; 0 <= nums[i] <= 100; answer fits in int.","An integer array nums.","Return the maximum score.","[3,1,5,8] -> 167\n[1,5] -> 10","burstValueOptimizer","int",a("nums","int[]"),cs(p("[[3,1,5,8]]","167"),p("[[1,5]]","10"),h("[[7]]","7"),h("[[1,1,1]]","3"),h("[[0,1,0]]","1"),h("[[9,76,64,21]]","116718")),hs("Choosing the final value burst inside an interval makes its two neighbors fixed.","Pad the array with boundary ones and let dp[left][right] be the best score inside that open interval.","Try every possible final index between left and right, combining its two solved subintervals with its final gain.")),
        s("Palindrome Minimum Cuts","HARD","dynamic-programming,strings,palindrome","Split s into palindrome pieces using the fewest cuts. Return zero when s itself is a palindrome.","0 <= s.length <= 2000; s contains lowercase letters.","A string s.","Return the minimum number of cuts.","\"aab\" -> 1\n\"racecar\" -> 0","palindromeMinimumCuts","int",a("s","String"),cs(p("[\"aab\"]","1"),p("[\"racecar\"]","0"),h("[\"\"]","0"),h("[\"ab\"]","1"),h("[\"ababbbabbababa\"]","3"),h("[\"cdd\"]","1")),hs("A cut is useful only when the suffix after it is a palindrome piece.","Expand around every possible palindrome center while maintaining the best cut count for its right endpoint.","Initialize cuts[i] as i-1 and relax cuts[right] from cuts[left]+1 whenever s[left..right] is palindromic.")),
        s("Network Delay Minimum","HARD","graphs,shortest-path,heap,dijkstra","Nodes are numbered 1 through nodeCount. Each edge string is \"from,to,weight\". Starting at source, return the time until every node receives the signal, or -1 if any node is unreachable.","1 <= nodeCount <= 2000; edges have positive weights.","String[] edges, integer nodeCount, and integer source.","Return the maximum shortest-path distance or -1.","[\"2,1,1\",\"2,3,1\",\"3,4,1\"], 4, 2 -> 2\n[\"1,2,1\"], 2, 2 -> -1","networkDelayMinimum","int",a("edges","String[]","nodeCount","int","source","int"),cs(p("[[\"2,1,1\",\"2,3,1\",\"3,4,1\"],4,2]","2"),p("[[\"1,2,1\"],2,2]","-1"),h("[[],1,1]","0"),h("[[\"1,2,5\",\"1,3,1\",\"3,2,1\"],3,1]","2"),h("[[\"1,2,1\",\"2,3,2\",\"1,3,10\"],3,1]","3"),h("[[\"1,2,1\"],3,1]","-1")),hs("The first time a node is finalized by Dijkstra, its distance is optimal because all edges are positive.","Parse edges into adjacency lists and use a min-heap ordered by tentative distance.","Skip stale heap entries, relax outgoing edges, then take the largest finalized distance if every node was reached.")),
        s("Cheapest Route With Stop Limit","HARD","graphs,shortest-path,dynamic-programming","Cities are numbered 0 through cityCount-1. Edge strings are \"from,to,cost\". Return the cheapest route from source to destination using at most maxStops intermediate cities, or -1.","1 <= cityCount <= 200; edge costs are positive.","String[] edges, cityCount, source, destination, and maxStops.","Return the cheapest permitted cost or -1.","[\"0,1,100\",\"1,2,100\",\"0,2,500\"], 3, 0, 2, 1 -> 200\n[\"0,1,100\",\"1,2,100\",\"0,2,500\"], 3, 0, 2, 0 -> 500","cheapestRouteWithStopLimit","int",a("edges","String[]","cityCount","int","source","int","destination","int","maxStops","int"),cs(p("[[\"0,1,100\",\"1,2,100\",\"0,2,500\"],3,0,2,1]","200"),p("[[\"0,1,100\",\"1,2,100\",\"0,2,500\"],3,0,2,0]","500"),h("[[],1,0,0,0]","0"),h("[[\"0,1,5\"],3,0,2,2]","-1"),h("[[\"0,1,5\",\"1,2,5\",\"0,2,20\"],3,0,2,1]","10"),h("[[\"0,1,1\",\"1,2,1\",\"2,3,1\",\"0,3,10\"],4,0,3,1]","10")),hs("The number of used edges is part of the state, so one cheapest-per-city value is insufficient.","Relax all edges in rounds, where round r only reads distances from round r-1.","Perform maxStops+1 relaxation rounds using a copied distance array; the destination after the final round is the answer.")),
        s("Maximum Job Profit Schedule","HARD","dynamic-programming,binary-search,intervals,scheduling","Each job has matching start, end, and profit entries. Choose non-overlapping jobs to maximize total profit; a job ending at time t may precede one starting at t.","1 <= start.length = end.length = profit.length <= 100000; values fit in int.","Three integer arrays start, end, and profit.","Return the maximum profit as a long.","[1,2,3,3], [3,4,5,6], [50,10,40,70] -> 120\n[1,2,3,4,6], [3,5,10,6,9], [20,20,100,70,60] -> 150","maximumJobProfitSchedule","long",a("start","int[]","end","int[]","profit","int[]"),cs(p("[[1,2,3,3],[3,4,5,6],[50,10,40,70]]","120"),p("[[1,2,3,4,6],[3,5,10,6,9],[20,20,100,70,60]]","150"),h("[[1],[2],[10]]","10"),h("[[1,1],[2,3],[5,6]]","6"),h("[[1,2,4],[3,5,6],[50,20,100]]","150"),h("[[1,2,3],[2,3,4],[5,6,5]]","16")),hs("For each job, either take its profit plus a compatible earlier schedule or skip it.","Sort jobs by end time and find the latest job ending no later than each start with binary search.","Let dp[i] be the best profit through sorted job i; compare taking it with dp[compatible] against dp[i-1].")),
        s("Regex Pattern Matcher","HARD","dynamic-programming,strings","Return whether text fully matches pattern, where '.' matches one arbitrary character and '*' repeats the immediately preceding pattern token zero or more times.","0 <= text.length, pattern.length <= 200; pattern is syntactically valid.","A text string and a pattern string.","Return true only for a full match.","\"aab\", \"c*a*b\" -> true\n\"mississippi\", \"mis*is*p*.\" -> false","regexPatternMatcher","boolean",a("text","String","pattern","String"),cs(p("[\"aab\",\"c*a*b\"]","true"),p("[\"mississippi\",\"mis*is*p*.\"]","false"),h("[\"aa\",\"a\"]","false"),h("[\"aa\",\"a*\"]","true"),h("[\"ab\",\".*\"]","true"),h("[\"\",\"c*\"]","true")),hs("Matching must cover both complete strings, so define states on text and pattern prefixes.","When pattern has '*', it can either contribute zero copies or consume one compatible text character and stay available.","Build dp over prefix lengths, initializing empty-text matches for star pairs and applying the zero-or-more recurrence.")),
        s("Course Completion Ordering","HARD","graphs,topological-sort,bfs,dfs","Courses are numbered 0 through courseCount-1. Each prerequisite string is \"course,prerequisite\". Return the lexicographically smallest valid completion order, or an empty array when a cycle exists.","0 <= courseCount <= 2000; every prerequisite refers to a valid course.","An integer courseCount and a String[] prerequisites.","Return the deterministic course order or [].","2, [\"1,0\"] -> [0,1]\n2, [\"1,0\",\"0,1\"] -> []","courseCompletionOrdering","int[]",a("courseCount","int","prerequisites","String[]"),cs(p("[2,[\"1,0\"]]","[0,1]"),p("[2,[\"1,0\",\"0,1\"]]","[]"),h("[4,[\"1,0\",\"2,0\",\"3,1\",\"3,2\"]]","[0,1,2,3]"),h("[3,[]]","[0,1,2]"),h("[1,[]]","[0]"),h("[3,[\"1,0\",\"2,1\",\"0,2\"]]","[]")),hs("A course can be scheduled once all of its prerequisite edges have been removed.","Use in-degrees and a min-heap of currently available course numbers to enforce the lexicographic rule.","Repeatedly take the smallest zero-in-degree course, append it, and reduce its dependents; return [] unless all courses are appended."))
    ); }
    private static Spec s(String title,String difficulty,String tags,String description,String constraints,String input,String output,String examples,String name,String returns,String[][] params,List<Case> cases,String[] hints){return new Spec(title,difficulty,tags,description,constraints,input,output,examples,name,returns,params,cases,hints);}
    private static String[][] a(String... values){String[][] r=new String[values.length/2][2];for(int i=0;i<values.length;i+=2){r[i/2][0]=values[i];r[i/2][1]=values[i+1];}return r;}
    private static List<Case> cs(Case... values){return List.of(values);} private static String[] hs(String... values){return values;}
}
