int missingBeacon(vector<int> nums) { int answer=nums.size();for(int i=0;i<(int)nums.size();i++)answer^=i^nums[i];return answer; }
bool letterInventoryMatch(string s,string t) { int count[26]={};for(char c:s)count[c-'a']++;for(char c:t)count[c-'a']--;for(int n:count)if(n)return false;return true; }
vector<int> stableZeroShift(vector<int> nums) { int write=0;for(int x:nums)if(x)nums[write++]=x;while(write<(int)nums.size())nums[write++]=0;return nums; }
bool bracketBalance(string s) { vector<char> st;for(char c:s){if(c=='('||c=='['||c=='{')st.push_back(c);else{if(st.empty())return false;char a=st.back();st.pop_back();if(c==')'&&a!='('||c==']'&&a!='['||c=='}'&&a!='{')return false;}}return st.empty(); }
int longestRunOfOnes(vector<int> nums) { int run=0,best=0;for(int x:nums){run=x==1?run+1:0;best=max(best,run);}return best; }
int sortedTargetLocator(vector<int> nums,int target) { int lo=0,hi=(int)nums.size()-1;while(lo<=hi){int mid=lo+(hi-lo)/2;if(nums[mid]==target)return mid;if(nums[mid]<target)lo=mid+1;else hi=mid-1;}return -1; }
int uniqueWindowLength(string s) { vector<int> last(128,-1);int left=0,best=0;for(int i=0;i<(int)s.size();i++){left=max(left,last[(unsigned char)s[i]]+1);last[(unsigned char)s[i]]=i;best=max(best,i-left+1);}return best; }
vector<int> productWithoutPosition(vector<int> nums) { vector<int> answer(nums.size());long long product=1;for(int i=0;i<(int)nums.size();i++){answer[i]=product;if(i+1<(int)nums.size())product*=nums[i];}product=1;for(int i=(int)nums.size()-1;i>=0;i--){answer[i]*=product;if(i>0)product*=nums[i];}return answer; }
vector<int> frequencyCrown(vector<int> nums,int k) { unordered_map<int,int> counts;for(int x:nums)counts[x]++;vector<int> values;for(auto item:counts)values.push_back(item.first);sort(values.begin(),values.end(),[&](int a,int b){return counts[a]==counts[b]?a<b:counts[a]>counts[b];});values.resize(k);return values; }
int quietStreetRobber(vector<int> nums) { int older=0,previous=0;for(int x:nums){int current=max(previous,older+x);older=previous;previous=current;}return previous; }
vector<string> wellFormedParenthesisBuilder(int n) { vector<string> answer;function<void(string,int,int)> visit=[&](string text,int open,int close){if(close==n){answer.push_back(text);return;}if(open<n)visit(text+"(",open+1,close);if(close<open)visit(text+")",open,close+1);};visit("",0,0);return answer; }
bool prerequisiteRouteCheck(int courseCount,vector<string> prerequisites) { vector<vector<int>> graph(courseCount);vector<int> degree(courseCount);for(string edge:prerequisites){replace(edge.begin(),edge.end(),',',' ');istringstream in(edge);int a,b;in>>a>>b;graph[b].push_back(a);degree[a]++;}queue<int> q;for(int i=0;i<courseCount;i++)if(!degree[i])q.push(i);int count=0;while(!q.empty()){int node=q.front();q.pop();count++;for(int next:graph[node])if(--degree[next]==0)q.push(next);}return count==courseCount; }
vector<int> dailyTemperatureWait(vector<int> temperatures) { vector<int> answer(temperatures.size()),st;for(int i=0;i<(int)temperatures.size();i++){while(!st.empty()&&temperatures[st.back()]<temperatures[i]){int j=st.back();st.pop_back();answer[j]=i-j;}st.push_back(i);}return answer; }
int circularFuelDeparture(vector<int> fuel,vector<int> cost) { if(fuel.empty())return -1;long long total=0,tank=0;int start=0;for(int i=0;i<(int)fuel.size();i++){long long delta=(long long)fuel[i]-cost[i];total+=delta;tank+=delta;if(tank<0){start=i+1;tank=0;}}return total>=0?start:-1; }
int rainwaterBasin(vector<int> heights) { int lo=0,hi=(int)heights.size()-1,left=0,right=0;long long water=0;while(lo<=hi){if(left<=right){left=max(left,heights[lo]);water+=left-heights[lo++];}else{right=max(right,heights[hi]);water+=right-heights[hi--];}}if(water>INT_MAX)throw overflow_error("int return contract exceeded");return (int)water; }
int histogramSkyline(vector<int> heights) { vector<int> st;long long best=0;for(int i=0;i<=(int)heights.size();i++){int current=i<(int)heights.size()?heights[i]:0;while(!st.empty()&&heights[st.back()]>current){long long h=heights[st.back()];st.pop_back();int width=i-(st.empty()?-1:st.back())-1;best=max(best,h*width);}st.push_back(i);}if(best>INT_MAX)throw overflow_error("int return contract exceeded");return (int)best; }
int stringTransformationCost(string source,string target) { vector<int> previous(target.size()+1);iota(previous.begin(),previous.end(),0);for(int i=1;i<=(int)source.size();i++){vector<int> current(previous.size());current[0]=i;for(int j=1;j<(int)current.size();j++)current[j]=source[i-1]==target[j-1]?previous[j-1]:1+min(previous[j-1],min(previous[j],current[j-1]));previous=move(current);}return previous.back(); }
string smallestCoveringWindow(string source,string target) { if(target.empty())return "";vector<int> need(128);for(unsigned char c:target)need[c]++;int missing=target.size(),left=0,start=0,length=source.size()+1;for(int right=0;right<(int)source.size();right++){if(need[(unsigned char)source[right]]-->0)missing--;while(!missing){if(right-left+1<length){start=left;length=right-left+1;}if(++need[(unsigned char)source[left++]]>0)missing++;}}return length>(int)source.size()?"":source.substr(start,length); }
int wordMutationSteps(string beginWord,string endWord,vector<string> dictionary) { if(beginWord==endWord)return 1;unordered_set<string> remaining(dictionary.begin(),dictionary.end());if(!remaining.count(endWord))return 0;remaining.erase(beginWord);queue<pair<string,int>> q;q.push({beginWord,1});while(!q.empty()){auto [word,distance]=q.front();q.pop();for(int i=0;i<(int)word.size();i++){char old=word[i];for(char c='a';c<='z';c++){word[i]=c;if(!remaining.erase(word))continue;if(word==endWord)return distance+1;q.push({word,distance+1});}word[i]=old;}}return 0; }
int queenBoardCounter(int n) { int mask=(1<<n)-1;function<int(int,int,int)> visit=[&](int columns,int left,int right){if(columns==mask)return 1;int free=mask&~(columns|left|right),answer=0;while(free){int bit=free&-free;free-=bit;answer+=visit(columns|bit,((left|bit)<<1)&mask,(right|bit)>>1);}return answer;};return visit(0,0,0); }
int majoritySignal(vector<int> nums) { int candidate=0,balance=0;for(int x:nums){if(!balance)candidate=x;balance+=x==candidate?1:-1;}return candidate; }
int prefixBalancePoint(vector<int> nums) { long long total=accumulate(nums.begin(),nums.end(),0LL),left=0;for(int i=0;i<(int)nums.size();i++){if(left==total-left-nums[i])return i;left+=nums[i];}return -1; }
int singleNumberTrace(vector<int> nums) { int answer=0;for(int x:nums)answer^=x;return answer; }
int firstUniqueSymbol(string s) { vector<int> counts(128);for(unsigned char c:s)counts[c]++;for(int i=0;i<(int)s.size();i++)if(counts[(unsigned char)s[i]]==1)return i;return -1; }
int rotatedArrayLocator(vector<int> nums,int target) { int lo=0,hi=(int)nums.size()-1;while(lo<=hi){int mid=lo+(hi-lo)/2;if(nums[mid]==target)return mid;if(nums[lo]<=nums[mid]){if(nums[lo]<=target&&target<nums[mid])hi=mid-1;else lo=mid+1;}else{if(nums[mid]<target&&target<=nums[hi])lo=mid+1;else hi=mid-1;}}return -1; }
int peakTerrainIndex(vector<int> heights) { int lo=0,hi=(int)heights.size()-1;while(lo<hi){int mid=lo+(hi-lo)/2;if(heights[mid]<heights[mid+1])lo=mid+1;else hi=mid;}return lo; }
int minimumCapacityScheduler(vector<int> weights,int days) { long long lo=*max_element(weights.begin(),weights.end()),hi=accumulate(weights.begin(),weights.end(),0LL);while(lo<hi){long long capacity=lo+(hi-lo)/2,load=0;int used=1;for(int x:weights){if(load+x>capacity){used++;load=0;}load+=x;}if(used<=days)hi=capacity;else lo=capacity+1;}if(lo>INT_MAX)throw overflow_error("int return contract exceeded");return (int)lo; }
int kthLargestStreamValue(vector<int> nums,int k) { priority_queue<int,vector<int>,greater<int>> heap;for(int x:nums){heap.push(x);if((int)heap.size()>k)heap.pop();}return heap.top(); }
vector<string> mergeTimeBlocks(vector<string> blocks) { vector<pair<int,int>> intervals;for(string s:blocks){replace(s.begin(),s.end(),',',' ');istringstream in(s);int a,b;in>>a>>b;intervals.push_back({a,b});}sort(intervals.begin(),intervals.end());vector<pair<int,int>> merged;for(auto item:intervals){if(!merged.empty()&&item.first<=merged.back().second)merged.back().second=max(merged.back().second,item.second);else merged.push_back(item);}vector<string> answer;for(auto [a,b]:merged)answer.push_back(to_string(a)+","+to_string(b));return answer; }
int minimumMeetingRooms(vector<string> meetings) { vector<pair<int,int>> intervals;for(string s:meetings){replace(s.begin(),s.end(),',',' ');istringstream in(s);int a,b;in>>a>>b;intervals.push_back({a,b});}sort(intervals.begin(),intervals.end());priority_queue<int,vector<int>,greater<int>> heap;int best=0;for(auto [a,b]:intervals){while(!heap.empty()&&heap.top()<=a)heap.pop();heap.push(b);best=max(best,(int)heap.size());}return best; }
vector<int> nextGreaterCircularValue(vector<int> nums) { int n=nums.size();vector<int> answer(n,-1),st;for(int i=0;i<2*n;i++){while(!st.empty()&&nums[st.back()]<nums[i%n]){answer[st.back()]=nums[i%n];st.pop_back();}if(i<n)st.push_back(i);}return answer; }
vector<int> slidingWindowMaximum(vector<int> nums,int k) { vector<int> answer;deque<int> q;for(int i=0;i<(int)nums.size();i++){while(!q.empty()&&q.front()<=i-k)q.pop_front();while(!q.empty()&&nums[q.back()]<=nums[i])q.pop_back();q.push_back(i);if(i>=k-1)answer.push_back(nums[q.front()]);}return answer; }
int subarrayTargetCount(vector<int> nums,int target) { unordered_map<long long,int> counts;counts[0]=1;long long prefix=0;int answer=0;for(int x:nums){prefix+=x;auto found=counts.find(prefix-target);if(found!=counts.end())answer+=found->second;counts[prefix]++;}return answer; }
int longestConsecutiveChain(vector<int> nums) { unordered_set<long long> values(nums.begin(),nums.end());int best=0;for(long long x:values)if(!values.count(x-1)){long long end=x;while(values.count(end))end++;best=max(best,(int)(end-x));}return best; }
int coinCombinationMinimum(vector<int> coins,int amount) { vector<int> dp(amount+1,amount+1);dp[0]=0;for(int value=1;value<=amount;value++)for(int coin:coins)if(coin<=value)dp[value]=min(dp[value],dp[value-coin]+1);return dp[amount]<=amount?dp[amount]:-1; }
int increasingSequenceLength(vector<int> nums) { vector<int> tails;for(int x:nums){auto it=lower_bound(tails.begin(),tails.end(),x);if(it==tails.end())tails.push_back(x);else *it=x;}return tails.size(); }
bool partitionTargetFeasibility(vector<int> nums) { int total=accumulate(nums.begin(),nums.end(),0);if(total%2)return false;vector<bool> possible(total/2+1);possible[0]=true;for(int x:nums)for(int sum=total/2;sum>=x;sum--)possible[sum]=possible[sum]||possible[sum-x];return possible[total/2]; }
int decodeMessageWays(string digits) { int older=1,previous=digits[0]=='0'?0:1;for(int i=1;i<(int)digits.size();i++){int current=digits[i]=='0'?0:previous,pair=(digits[i-1]-'0')*10+digits[i]-'0';if(pair>=10&&pair<=26)current+=older;older=previous;previous=current;}return previous; }
string matrixSpiralReader(vector<string> rows) { if(rows.empty()||rows[0].empty())return "";int top=0,bottom=(int)rows.size()-1,left=0,right=(int)rows[0].size()-1;string out;while(top<=bottom&&left<=right){for(int j=left;j<=right;j++)out+=rows[top][j];top++;for(int i=top;i<=bottom;i++)out+=rows[i][right];right--;if(top<=bottom){for(int j=right;j>=left;j--)out+=rows[bottom][j];bottom--;}if(left<=right){for(int i=bottom;i>=top;i--)out+=rows[i][left];left++;}}return out; }
int connectedRegionCounter(vector<string> rows) { if(rows.empty()||rows[0].empty())return 0;int R=rows.size(),C=rows[0].size(),count=0;int dx[]={1,-1,0,0},dy[]={0,0,1,-1};for(int i=0;i<R;i++)for(int j=0;j<C;j++){if(rows[i][j]!='1')continue;count++;vector<pair<int,int>> st={{i,j}};rows[i][j]='0';while(!st.empty()){auto [a,b]=st.back();st.pop_back();for(int d=0;d<4;d++){int x=a+dx[d],y=b+dy[d];if(x>=0&&x<R&&y>=0&&y<C&&rows[x][y]=='1'){rows[x][y]='0';st.push_back({x,y});}}}}return count; }
double medianOfTwoSortedSequences(vector<int> a,vector<int> b) { if(a.size()>b.size())swap(a,b);int lo=0,hi=a.size(),half=(a.size()+b.size()+1)/2;while(lo<=hi){int i=(lo+hi)/2,j=half-i;long long al=i==0?LLONG_MIN:a[i-1],ar=i==(int)a.size()?LLONG_MAX:a[i],bl=j==0?LLONG_MIN:b[j-1],br=j==(int)b.size()?LLONG_MAX:b[j];if(al<=br&&bl<=ar)return (a.size()+b.size())%2?max(al,bl):(max(al,bl)+min(ar,br))/2.0;if(al>br)hi=i-1;else lo=i+1;}throw invalid_argument("empty sequences"); }
int maximumRectangleInBinaryGrid(vector<string> rows) { if(rows.empty())return 0;vector<int> heights(rows[0].size());int best=0;for(string row:rows){for(int i=0;i<(int)heights.size();i++)heights[i]=row[i]=='1'?heights[i]+1:0;vector<int> st;for(int i=0;i<=(int)heights.size();i++){int current=i<(int)heights.size()?heights[i]:0;while(!st.empty()&&heights[st.back()]>current){int h=heights[st.back()];st.pop_back();best=max(best,h*(i-(st.empty()?-1:st.back())-1));}st.push_back(i);}}return best; }
int longestValidBracketSegment(string s) { vector<int> st={-1};int best=0;for(int i=0;i<(int)s.size();i++){if(s[i]=='(')st.push_back(i);else{st.pop_back();if(st.empty())st.push_back(i);else best=max(best,i-st.back());}}return best; }
int burstValueOptimizer(vector<int> nums) { int n=nums.size()+2;vector<int> a(n,1);copy(nums.begin(),nums.end(),a.begin()+1);vector<vector<int>> dp(n,vector<int>(n));for(int width=2;width<n;width++)for(int left=0;left+width<n;left++){int right=left+width;for(int k=left+1;k<right;k++)dp[left][right]=max(dp[left][right],dp[left][k]+dp[k][right]+a[left]*a[k]*a[right]);}return dp[0][n-1]; }
int palindromeMinimumCuts(string s) { int n=s.size();if(!n)return 0;vector<vector<bool>> pal(n,vector<bool>(n));vector<int> cuts(n+1);iota(cuts.begin(),cuts.end(),-1);for(int right=0;right<n;right++)for(int left=0;left<=right;left++)if(s[left]==s[right]&&(right-left<2||pal[left+1][right-1])){pal[left][right]=true;cuts[right+1]=min(cuts[right+1],cuts[left]+1);}return cuts[n]; }
int networkDelayMinimum(vector<string> edges,int nodeCount,int source) { vector<vector<pair<int,long long>>> graph(nodeCount+1);for(string edge:edges){replace(edge.begin(),edge.end(),',',' ');istringstream in(edge);int a,b;long long w;in>>a>>b>>w;graph[a].push_back({b,w});}vector<long long> distance(nodeCount+1,LLONG_MAX);distance[source]=0;priority_queue<pair<long long,int>,vector<pair<long long,int>>,greater<pair<long long,int>>> heap;heap.push({0,source});while(!heap.empty()){auto [cost,node]=heap.top();heap.pop();if(cost!=distance[node])continue;for(auto [next,w]:graph[node])if(cost+w<distance[next]){distance[next]=cost+w;heap.push({cost+w,next});}}long long answer=0;for(int i=1;i<=nodeCount;i++){if(distance[i]==LLONG_MAX)return -1;answer=max(answer,distance[i]);}if(answer>INT_MAX)throw overflow_error("int return contract exceeded");return (int)answer; }
int cheapestRouteWithStopLimit(vector<string> edges,int cityCount,int source,int destination,int maxStops) { vector<array<long long,3>> flights;for(string edge:edges){replace(edge.begin(),edge.end(),',',' ');istringstream in(edge);long long a,b,c;in>>a>>b>>c;flights.push_back({a,b,c});}long long inf=LLONG_MAX/4;vector<long long> distance(cityCount,inf);distance[source]=0;for(int round=0;round<=maxStops;round++){auto next=distance;for(auto edge:flights)next[edge[1]]=min(next[edge[1]],distance[edge[0]]+edge[2]);distance=move(next);}if(distance[destination]==inf)return -1;if(distance[destination]>INT_MAX)throw overflow_error("int return contract exceeded");return (int)distance[destination]; }
long long maximumJobProfitSchedule(vector<int> start,vector<int> end,vector<int> profit) { int n=start.size();vector<array<int,3>> jobs;for(int i=0;i<n;i++)jobs.push_back({end[i],start[i],profit[i]});sort(jobs.begin(),jobs.end());vector<long long> dp(n+1);for(int i=0;i<n;i++){int lo=0,hi=i;while(lo<hi){int mid=(lo+hi)/2;if(jobs[mid][0]<=jobs[i][1])lo=mid+1;else hi=mid;}dp[i+1]=max(dp[i],dp[lo]+jobs[i][2]);}return dp[n]; }
bool regexPatternMatcher(string text,string pattern) { int n=text.size(),m=pattern.size();vector<vector<bool>> dp(n+1,vector<bool>(m+1));dp[0][0]=true;for(int j=2;j<=m;j++)if(pattern[j-1]=='*')dp[0][j]=dp[0][j-2];for(int i=1;i<=n;i++)for(int j=1;j<=m;j++){char token=pattern[j-1];if(token=='*')dp[i][j]=dp[i][j-2]||((pattern[j-2]=='.'||pattern[j-2]==text[i-1])&&dp[i-1][j]);else dp[i][j]=(token=='.'||token==text[i-1])&&dp[i-1][j-1];}return dp[n][m]; }
vector<int> courseCompletionOrdering(int courseCount,vector<string> prerequisites) { vector<vector<int>> graph(courseCount);vector<int> degree(courseCount);for(string edge:prerequisites){replace(edge.begin(),edge.end(),',',' ');istringstream in(edge);int a,b;in>>a>>b;graph[b].push_back(a);degree[a]++;}priority_queue<int,vector<int>,greater<int>> heap;for(int i=0;i<courseCount;i++)if(!degree[i])heap.push(i);vector<int> order;while(!heap.empty()){int node=heap.top();heap.pop();order.push_back(node);for(int next:graph[node])if(--degree[next]==0)heap.push(next);}return (int)order.size()==courseCount?order:vector<int>{}; }
string reverseString(string s) { reverse(s.begin(),s.end());return s; }
vector<int> twoSum(vector<int> nums,int target) { unordered_map<long long,int> seen;for(int i=0;i<(int)nums.size();i++){long long need=(long long)target-nums[i];if(seen.count(need))return {seen[need],i};seen[nums[i]]=i;}return {}; }
bool isValid(string s) { vector<char> st;for(char c:s){if(c=='('||c=='['||c=='{')st.push_back(c);else{if(st.empty())return false;char a=st.back();st.pop_back();if(c==')'&&a!='('||c==']'&&a!='['||c=='}'&&a!='{')return false;}}return st.empty(); }
