// FUNCTION reference methods. Standard library imports are provided by the judge wrapper.
public int missingBeacon(int[] nums) { int answer=nums.length; for(int i=0;i<nums.length;i++) answer^=i^nums[i]; return answer; }
public boolean letterInventoryMatch(String s,String t) { int[] count=new int[26]; for(char c:s.toCharArray())count[c-'a']++; for(char c:t.toCharArray())count[c-'a']--; for(int n:count)if(n!=0)return false; return true; }
public int[] stableZeroShift(int[] nums) { int write=0; for(int x:nums)if(x!=0)nums[write++]=x; while(write<nums.length)nums[write++]=0; return nums; }
public boolean bracketBalance(String s) { java.util.Deque<Character> stack=new java.util.ArrayDeque<>(); for(char c:s.toCharArray()){if(c=='('||c=='['||c=='{')stack.push(c);else{if(stack.isEmpty())return false;char a=stack.pop();if(c==')'&&a!='('||c==']'&&a!='['||c=='}'&&a!='{')return false;}}return stack.isEmpty(); }
public int longestRunOfOnes(int[] nums) { int run=0,best=0;for(int x:nums){run=x==1?run+1:0;best=Math.max(best,run);}return best; }
public int sortedTargetLocator(int[] nums,int target) { int lo=0,hi=nums.length-1;while(lo<=hi){int mid=lo+(hi-lo)/2;if(nums[mid]==target)return mid;if(nums[mid]<target)lo=mid+1;else hi=mid-1;}return -1; }
public int uniqueWindowLength(String s) { int[] last=new int[128];java.util.Arrays.fill(last,-1);int left=0,best=0;for(int i=0;i<s.length();i++){char c=s.charAt(i);left=Math.max(left,last[c]+1);last[c]=i;best=Math.max(best,i-left+1);}return best; }
public int[] productWithoutPosition(int[] nums) { int[] answer=new int[nums.length];long product=1;for(int i=0;i<nums.length;i++){answer[i]=(int)product;if(i+1<nums.length)product*=nums[i];}product=1;for(int i=nums.length-1;i>=0;i--){answer[i]=(int)(answer[i]*product);if(i>0)product*=nums[i];}return answer; }
public int[] frequencyCrown(int[] nums,int k) { java.util.Map<Integer,Integer> counts=new java.util.HashMap<>();for(int x:nums)counts.merge(x,1,Integer::sum);java.util.List<Integer> values=new java.util.ArrayList<>(counts.keySet());values.sort((a,b)->counts.get(a).equals(counts.get(b))?Integer.compare(a,b):Integer.compare(counts.get(b),counts.get(a)));return values.subList(0,k).stream().mapToInt(Integer::intValue).toArray(); }
public int quietStreetRobber(int[] nums) { int older=0,previous=0;for(int x:nums){int current=Math.max(previous,older+x);older=previous;previous=current;}return previous; }
public String[] wellFormedParenthesisBuilder(int n) { java.util.List<String> answer=new java.util.ArrayList<>();class Search {void visit(String text,int open,int close){if(close==n){answer.add(text);return;}if(open<n)visit(text+"(",open+1,close);if(close<open)visit(text+")",open,close+1);}}new Search().visit("",0,0);return answer.toArray(String[]::new); }
public boolean prerequisiteRouteCheck(int courseCount,String[] prerequisites) { java.util.List<java.util.List<Integer>> graph=new java.util.ArrayList<>();for(int i=0;i<courseCount;i++)graph.add(new java.util.ArrayList<>());int[] degree=new int[courseCount];for(String edge:prerequisites){String[] p=edge.split(",");int a=Integer.parseInt(p[0]),b=Integer.parseInt(p[1]);graph.get(b).add(a);degree[a]++;}java.util.Deque<Integer> queue=new java.util.ArrayDeque<>();for(int i=0;i<courseCount;i++)if(degree[i]==0)queue.add(i);int count=0;while(!queue.isEmpty()){int node=queue.remove();count++;for(int next:graph.get(node))if(--degree[next]==0)queue.add(next);}return count==courseCount; }
public int[] dailyTemperatureWait(int[] temperatures) { int[] answer=new int[temperatures.length];java.util.Deque<Integer> stack=new java.util.ArrayDeque<>();for(int i=0;i<temperatures.length;i++){while(!stack.isEmpty()&&temperatures[stack.peek()]<temperatures[i]){int j=stack.pop();answer[j]=i-j;}stack.push(i);}return answer; }
public int circularFuelDeparture(int[] fuel,int[] cost) { if(fuel.length==0)return -1;long total=0,tank=0;int start=0;for(int i=0;i<fuel.length;i++){long delta=(long)fuel[i]-cost[i];total+=delta;tank+=delta;if(tank<0){start=i+1;tank=0;}}return total>=0?start:-1; }
public int rainwaterBasin(int[] heights) { int lo=0,hi=heights.length-1,left=0,right=0;long water=0;while(lo<=hi){if(left<=right){left=Math.max(left,heights[lo]);water+=left-heights[lo++];}else{right=Math.max(right,heights[hi]);water+=right-heights[hi--];}}return Math.toIntExact(water); }
public int histogramSkyline(int[] heights) { java.util.Deque<Integer> stack=new java.util.ArrayDeque<>();long best=0;for(int i=0;i<=heights.length;i++){int current=i<heights.length?heights[i]:0;while(!stack.isEmpty()&&heights[stack.peek()]>current){long height=heights[stack.pop()];int width=i-(stack.isEmpty()?-1:stack.peek())-1;best=Math.max(best,height*width);}stack.push(i);}return Math.toIntExact(best); }
public int stringTransformationCost(String source,String target) { int[] previous=new int[target.length()+1];for(int j=0;j<previous.length;j++)previous[j]=j;for(int i=1;i<=source.length();i++){int[] current=new int[previous.length];current[0]=i;for(int j=1;j<current.length;j++)current[j]=source.charAt(i-1)==target.charAt(j-1)?previous[j-1]:1+Math.min(previous[j-1],Math.min(previous[j],current[j-1]));previous=current;}return previous[target.length()]; }
public String smallestCoveringWindow(String source,String target) { if(target.isEmpty())return "";int[] need=new int[128];for(char c:target.toCharArray())need[c]++;int missing=target.length(),left=0,start=0,length=source.length()+1;for(int right=0;right<source.length();right++){if(need[source.charAt(right)]-->0)missing--;while(missing==0){if(right-left+1<length){start=left;length=right-left+1;}if(++need[source.charAt(left++)]>0)missing++;}}return length>source.length()?"":source.substring(start,start+length); }
public int wordMutationSteps(String beginWord,String endWord,String[] dictionary) { if(beginWord.equals(endWord))return 1;java.util.Set<String> remaining=new java.util.HashSet<>(java.util.Arrays.asList(dictionary));if(!remaining.contains(endWord))return 0;remaining.remove(beginWord);java.util.Deque<String> queue=new java.util.ArrayDeque<>();queue.add(beginWord);int distance=1;while(!queue.isEmpty()){int size=queue.size();while(size-->0){char[] chars=queue.remove().toCharArray();for(int i=0;i<chars.length;i++){char old=chars[i];for(char c='a';c<='z';c++){chars[i]=c;String next=new String(chars);if(!remaining.remove(next))continue;if(next.equals(endWord))return distance+1;queue.add(next);}chars[i]=old;}}distance++;}return 0; }
public int queenBoardCounter(int n) { int mask=(1<<n)-1;class Search{int visit(int columns,int left,int right){if(columns==mask)return 1;int free=mask&~(columns|left|right),answer=0;while(free!=0){int bit=free&-free;free-=bit;answer+=visit(columns|bit,((left|bit)<<1)&mask,(right|bit)>>1);}return answer;}}return new Search().visit(0,0,0); }
public int majoritySignal(int[] nums) { int candidate=0,balance=0;for(int x:nums){if(balance==0)candidate=x;balance+=x==candidate?1:-1;}return candidate; }
public int prefixBalancePoint(int[] nums) { long total=0,left=0;for(int x:nums)total+=x;for(int i=0;i<nums.length;i++){if(left==total-left-nums[i])return i;left+=nums[i];}return -1; }
public int singleNumberTrace(int[] nums) { int answer=0;for(int x:nums)answer^=x;return answer; }
public int firstUniqueSymbol(String s) { int[] counts=new int[128];for(char c:s.toCharArray())counts[c]++;for(int i=0;i<s.length();i++)if(counts[s.charAt(i)]==1)return i;return -1; }
public int rotatedArrayLocator(int[] nums,int target) { int lo=0,hi=nums.length-1;while(lo<=hi){int mid=lo+(hi-lo)/2;if(nums[mid]==target)return mid;if(nums[lo]<=nums[mid]){if(nums[lo]<=target&&target<nums[mid])hi=mid-1;else lo=mid+1;}else{if(nums[mid]<target&&target<=nums[hi])lo=mid+1;else hi=mid-1;}}return -1; }
public int peakTerrainIndex(int[] heights) { int lo=0,hi=heights.length-1;while(lo<hi){int mid=lo+(hi-lo)/2;if(heights[mid]<heights[mid+1])lo=mid+1;else hi=mid;}return lo; }
public int minimumCapacityScheduler(int[] weights,int days) { long lo=0,hi=0;for(int x:weights){lo=Math.max(lo,x);hi+=x;}while(lo<hi){long capacity=lo+(hi-lo)/2,load=0;int used=1;for(int x:weights){if(load+x>capacity){used++;load=0;}load+=x;}if(used<=days)hi=capacity;else lo=capacity+1;}return Math.toIntExact(lo); }
public int kthLargestStreamValue(int[] nums,int k) { java.util.PriorityQueue<Integer> heap=new java.util.PriorityQueue<>();for(int x:nums){heap.add(x);if(heap.size()>k)heap.remove();}return heap.element(); }
public String[] mergeTimeBlocks(String[] blocks) { int[][] intervals=new int[blocks.length][2];for(int i=0;i<blocks.length;i++){String[] p=blocks[i].split(",");intervals[i]=new int[]{Integer.parseInt(p[0]),Integer.parseInt(p[1])};}java.util.Arrays.sort(intervals,java.util.Comparator.comparingInt(a->a[0]));java.util.List<int[]> merged=new java.util.ArrayList<>();for(int[] item:intervals){if(!merged.isEmpty()&&item[0]<=merged.getLast()[1])merged.getLast()[1]=Math.max(merged.getLast()[1],item[1]);else merged.add(item.clone());}return merged.stream().map(a->a[0]+","+a[1]).toArray(String[]::new); }
public int minimumMeetingRooms(String[] meetings) { int[][] intervals=new int[meetings.length][2];for(int i=0;i<meetings.length;i++){String[] p=meetings[i].split(",");intervals[i]=new int[]{Integer.parseInt(p[0]),Integer.parseInt(p[1])};}java.util.Arrays.sort(intervals,java.util.Comparator.comparingInt(a->a[0]));java.util.PriorityQueue<Integer> heap=new java.util.PriorityQueue<>();int best=0;for(int[] item:intervals){while(!heap.isEmpty()&&heap.peek()<=item[0])heap.remove();heap.add(item[1]);best=Math.max(best,heap.size());}return best; }
public int[] nextGreaterCircularValue(int[] nums) { int n=nums.length;int[] answer=new int[n];java.util.Arrays.fill(answer,-1);java.util.Deque<Integer> stack=new java.util.ArrayDeque<>();for(int i=0;i<2*n;i++){while(!stack.isEmpty()&&nums[stack.peek()]<nums[i%n])answer[stack.pop()]=nums[i%n];if(i<n)stack.push(i);}return answer; }
public int[] slidingWindowMaximum(int[] nums,int k) { int[] answer=new int[nums.length-k+1];java.util.Deque<Integer> queue=new java.util.ArrayDeque<>();for(int i=0;i<nums.length;i++){while(!queue.isEmpty()&&queue.peekFirst()<=i-k)queue.removeFirst();while(!queue.isEmpty()&&nums[queue.peekLast()]<=nums[i])queue.removeLast();queue.addLast(i);if(i>=k-1)answer[i-k+1]=nums[queue.peekFirst()];}return answer; }
public int subarrayTargetCount(int[] nums,int target) { java.util.Map<Long,Integer> counts=new java.util.HashMap<>();counts.put(0L,1);long prefix=0;int answer=0;for(int x:nums){prefix+=x;answer+=counts.getOrDefault(prefix-target,0);counts.merge(prefix,1,Integer::sum);}return answer; }
public int longestConsecutiveChain(int[] nums) { java.util.Set<Long> values=new java.util.HashSet<>();for(int x:nums)values.add((long)x);int best=0;for(long x:values)if(!values.contains(x-1)){long end=x;while(values.contains(end))end++;best=Math.max(best,(int)(end-x));}return best; }
public int coinCombinationMinimum(int[] coins,int amount) { int[] dp=new int[amount+1];java.util.Arrays.fill(dp,amount+1);dp[0]=0;for(int value=1;value<=amount;value++)for(int coin:coins)if(coin<=value)dp[value]=Math.min(dp[value],dp[value-coin]+1);return dp[amount]<=amount?dp[amount]:-1; }
public int increasingSequenceLength(int[] nums) { int[] tails=new int[nums.length];int size=0;for(int x:nums){int lo=0,hi=size;while(lo<hi){int mid=(lo+hi)/2;if(tails[mid]<x)lo=mid+1;else hi=mid;}tails[lo]=x;if(lo==size)size++;}return size; }
public boolean partitionTargetFeasibility(int[] nums) { int total=0;for(int x:nums)total+=x;if(total%2!=0)return false;boolean[] possible=new boolean[total/2+1];possible[0]=true;for(int x:nums)for(int sum=total/2;sum>=x;sum--)possible[sum]|=possible[sum-x];return possible[total/2]; }
public int decodeMessageWays(String digits) { int older=1,previous=digits.charAt(0)=='0'?0:1;for(int i=1;i<digits.length();i++){int current=digits.charAt(i)=='0'?0:previous;int pair=(digits.charAt(i-1)-'0')*10+digits.charAt(i)-'0';if(pair>=10&&pair<=26)current+=older;older=previous;previous=current;}return previous; }
public String matrixSpiralReader(String[] rows) { if(rows.length==0||rows[0].isEmpty())return "";int top=0,bottom=rows.length-1,left=0,right=rows[0].length()-1;StringBuilder out=new StringBuilder();while(top<=bottom&&left<=right){for(int j=left;j<=right;j++)out.append(rows[top].charAt(j));top++;for(int i=top;i<=bottom;i++)out.append(rows[i].charAt(right));right--;if(top<=bottom){for(int j=right;j>=left;j--)out.append(rows[bottom].charAt(j));bottom--;}if(left<=right){for(int i=bottom;i>=top;i--)out.append(rows[i].charAt(left));left++;}}return out.toString(); }
public int connectedRegionCounter(String[] rows) { if(rows.length==0||rows[0].isEmpty())return 0;int R=rows.length,C=rows[0].length(),count=0;char[][] grid=new char[R][];for(int i=0;i<R;i++)grid[i]=rows[i].toCharArray();int[] dx={1,-1,0,0},dy={0,0,1,-1};for(int i=0;i<R;i++)for(int j=0;j<C;j++){if(grid[i][j]!='1')continue;count++;java.util.Deque<int[]> stack=new java.util.ArrayDeque<>();stack.push(new int[]{i,j});grid[i][j]='0';while(!stack.isEmpty()){int[] cell=stack.pop();for(int d=0;d<4;d++){int x=cell[0]+dx[d],y=cell[1]+dy[d];if(x>=0&&x<R&&y>=0&&y<C&&grid[x][y]=='1'){grid[x][y]='0';stack.push(new int[]{x,y});}}}}return count; }
public double medianOfTwoSortedSequences(int[] a,int[] b) { if(a.length>b.length){int[] temp=a;a=b;b=temp;}int lo=0,hi=a.length,half=(a.length+b.length+1)/2;while(lo<=hi){int i=(lo+hi)/2,j=half-i;long al=i==0?Long.MIN_VALUE:a[i-1],ar=i==a.length?Long.MAX_VALUE:a[i],bl=j==0?Long.MIN_VALUE:b[j-1],br=j==b.length?Long.MAX_VALUE:b[j];if(al<=br&&bl<=ar)return (a.length+b.length)%2==1?Math.max(al,bl):(Math.max(al,bl)+Math.min(ar,br))/2.0;if(al>br)hi=i-1;else lo=i+1;}throw new IllegalArgumentException(); }
public int maximumRectangleInBinaryGrid(String[] rows) { if(rows.length==0)return 0;int[] heights=new int[rows[0].length()];int best=0;for(String row:rows){for(int i=0;i<heights.length;i++)heights[i]=row.charAt(i)=='1'?heights[i]+1:0;java.util.Deque<Integer> stack=new java.util.ArrayDeque<>();for(int i=0;i<=heights.length;i++){int current=i<heights.length?heights[i]:0;while(!stack.isEmpty()&&heights[stack.peek()]>current){int h=heights[stack.pop()];best=Math.max(best,h*(i-(stack.isEmpty()?-1:stack.peek())-1));}stack.push(i);}}return best; }
public int longestValidBracketSegment(String s) { java.util.Deque<Integer> stack=new java.util.ArrayDeque<>();stack.push(-1);int best=0;for(int i=0;i<s.length();i++){if(s.charAt(i)=='(')stack.push(i);else{stack.pop();if(stack.isEmpty())stack.push(i);else best=Math.max(best,i-stack.peek());}}return best; }
public int burstValueOptimizer(int[] nums) { int n=nums.length+2;int[] a=new int[n];a[0]=a[n-1]=1;System.arraycopy(nums,0,a,1,nums.length);int[][] dp=new int[n][n];for(int width=2;width<n;width++)for(int left=0;left+width<n;left++){int right=left+width;for(int k=left+1;k<right;k++)dp[left][right]=Math.max(dp[left][right],dp[left][k]+dp[k][right]+a[left]*a[k]*a[right]);}return dp[0][n-1]; }
public int palindromeMinimumCuts(String s) { int n=s.length();if(n==0)return 0;boolean[][] pal=new boolean[n][n];int[] cuts=new int[n+1];for(int i=0;i<=n;i++)cuts[i]=i-1;for(int right=0;right<n;right++)for(int left=0;left<=right;left++)if(s.charAt(left)==s.charAt(right)&&(right-left<2||pal[left+1][right-1])){pal[left][right]=true;cuts[right+1]=Math.min(cuts[right+1],cuts[left]+1);}return cuts[n]; }
public int networkDelayMinimum(String[] edges,int nodeCount,int source) { java.util.List<java.util.List<long[]>> graph=new java.util.ArrayList<>();for(int i=0;i<=nodeCount;i++)graph.add(new java.util.ArrayList<>());for(String edge:edges){String[] p=edge.split(",");graph.get(Integer.parseInt(p[0])).add(new long[]{Long.parseLong(p[1]),Long.parseLong(p[2])});}long[] distance=new long[nodeCount+1];java.util.Arrays.fill(distance,Long.MAX_VALUE);distance[source]=0;java.util.PriorityQueue<long[]> heap=new java.util.PriorityQueue<>(java.util.Comparator.comparingLong(a->a[0]));heap.add(new long[]{0,source});while(!heap.isEmpty()){long[] item=heap.remove();int node=(int)item[1];if(item[0]!=distance[node])continue;for(long[] edge:graph.get(node)){int next=(int)edge[0];long cost=item[0]+edge[1];if(cost<distance[next]){distance[next]=cost;heap.add(new long[]{cost,next});}}}long answer=0;for(int i=1;i<=nodeCount;i++){if(distance[i]==Long.MAX_VALUE)return -1;answer=Math.max(answer,distance[i]);}return Math.toIntExact(answer); }
public int cheapestRouteWithStopLimit(String[] edges,int cityCount,int source,int destination,int maxStops) { long[][] flights=new long[edges.length][3];for(int i=0;i<edges.length;i++){String[] p=edges[i].split(",");for(int j=0;j<3;j++)flights[i][j]=Long.parseLong(p[j]);}long inf=Long.MAX_VALUE/4;long[] distance=new long[cityCount];java.util.Arrays.fill(distance,inf);distance[source]=0;for(int round=0;round<=maxStops;round++){long[] next=distance.clone();for(long[] edge:flights)next[(int)edge[1]]=Math.min(next[(int)edge[1]],distance[(int)edge[0]]+edge[2]);distance=next;}return distance[destination]==inf?-1:Math.toIntExact(distance[destination]); }
public long maximumJobProfitSchedule(int[] start,int[] end,int[] profit) { int n=start.length;int[][] jobs=new int[n][3];for(int i=0;i<n;i++)jobs[i]=new int[]{end[i],start[i],profit[i]};java.util.Arrays.sort(jobs,java.util.Comparator.comparingInt(a->a[0]));long[] dp=new long[n+1];for(int i=0;i<n;i++){int lo=0,hi=i;while(lo<hi){int mid=(lo+hi)/2;if(jobs[mid][0]<=jobs[i][1])lo=mid+1;else hi=mid;}dp[i+1]=Math.max(dp[i],dp[lo]+jobs[i][2]);}return dp[n]; }
public boolean regexPatternMatcher(String text,String pattern) { int n=text.length(),m=pattern.length();boolean[][] dp=new boolean[n+1][m+1];dp[0][0]=true;for(int j=2;j<=m;j++)if(pattern.charAt(j-1)=='*')dp[0][j]=dp[0][j-2];for(int i=1;i<=n;i++)for(int j=1;j<=m;j++){char token=pattern.charAt(j-1);if(token=='*')dp[i][j]=dp[i][j-2]||((pattern.charAt(j-2)=='.'||pattern.charAt(j-2)==text.charAt(i-1))&&dp[i-1][j]);else dp[i][j]=(token=='.'||token==text.charAt(i-1))&&dp[i-1][j-1];}return dp[n][m]; }
public int[] courseCompletionOrdering(int courseCount,String[] prerequisites) { java.util.List<java.util.List<Integer>> graph=new java.util.ArrayList<>();for(int i=0;i<courseCount;i++)graph.add(new java.util.ArrayList<>());int[] degree=new int[courseCount];for(String edge:prerequisites){String[] p=edge.split(",");int a=Integer.parseInt(p[0]),b=Integer.parseInt(p[1]);graph.get(b).add(a);degree[a]++;}java.util.PriorityQueue<Integer> heap=new java.util.PriorityQueue<>();for(int i=0;i<courseCount;i++)if(degree[i]==0)heap.add(i);int[] order=new int[courseCount];int count=0;while(!heap.isEmpty()){int node=heap.remove();order[count++]=node;for(int next:graph.get(node))if(--degree[next]==0)heap.add(next);}return count==courseCount?order:new int[0]; }
public String reverseString(String s) { return new StringBuilder(s).reverse().toString(); }
public int[] twoSum(int[] nums,int target) { java.util.Map<Long,Integer> seen=new java.util.HashMap<>();for(int i=0;i<nums.length;i++){long need=(long)target-nums[i];if(seen.containsKey(need))return new int[]{seen.get(need),i};seen.put((long)nums[i],i);}return new int[0]; }
public boolean isValid(String s) { java.util.Deque<Character> stack=new java.util.ArrayDeque<>();for(char c:s.toCharArray()){if(c=='('||c=='['||c=='{')stack.push(c);else{if(stack.isEmpty())return false;char a=stack.pop();if(c==')'&&a!='('||c==']'&&a!='['||c=='}'&&a!='{')return false;}}return stack.isEmpty(); }
