package com.leetcode.backend.controller;
import com.leetcode.backend.model.*; import com.leetcode.backend.repository.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*; import java.util.stream.*;
@RestController @RequestMapping("/api/analytics") public class AnalyticsController {
 private final UserRepository users;private final SubmissionRepository submissions;private final ProblemRepository problems;private final ContestRegistrationRepository contests;private final UserCertificateRepository certificates;private final AssessmentRegistrationRepository assessments;
 AnalyticsController(UserRepository u,SubmissionRepository s,ProblemRepository p,ContestRegistrationRepository c,UserCertificateRepository cert,AssessmentRegistrationRepository a){users=u;submissions=s;problems=p;contests=c;certificates=cert;assessments=a;}
 @GetMapping("/me") public Map<String,Object> mine(Authentication a){return report(users.findByUsername(a.getName()).orElseThrow());}
 @GetMapping("/users/{id}") public Map<String,Object> user(@PathVariable Long id,Authentication a){if(a.getAuthorities().stream().noneMatch(x->x.getAuthority().equals("ROLE_ADMIN")))throw new AccessDeniedException("Admin required.");return report(users.findById(id).orElseThrow());}
 private Map<String,Object> report(User u){List<Submission> all=submissions.findByUserIdOrderBySubmittedAtDesc(u.getId());Set<Long> solved=all.stream().filter(this::accepted).map(s->s.getProblem().getId()).collect(Collectors.toSet());Map<Long,Problem> solvedProblems=problems.findAllById(solved).stream().collect(Collectors.toMap(Problem::getId,x->x));long accepted=all.stream().filter(this::accepted).count();Map<String,Object> r=new LinkedHashMap<>();r.put("totalSolved",solved.size());r.put("easySolved",solved.stream().map(solvedProblems::get).filter(Objects::nonNull).filter(p->"EASY".equalsIgnoreCase(p.getDifficulty())).count());r.put("mediumSolved",solved.stream().map(solvedProblems::get).filter(Objects::nonNull).filter(p->"MEDIUM".equalsIgnoreCase(p.getDifficulty())).count());r.put("hardSolved",solved.stream().map(solvedProblems::get).filter(Objects::nonNull).filter(p->"HARD".equalsIgnoreCase(p.getDifficulty())).count());r.put("totalSubmissions",all.size());r.put("acceptedSubmissions",accepted);r.put("failedSubmissions",all.size()-accepted);r.put("acceptanceRate",all.isEmpty()?0:Math.round(accepted*100.0/all.size()));r.put("languageUsage",all.stream().collect(Collectors.groupingBy(Submission::getLanguage,TreeMap::new,Collectors.counting())));r.put("contestParticipation",contests.findWithContestByUserId(u.getId()).size());r.put("certificatesEarned",certificates.findByUserIdOrderByMilestoneAsc(u.getId()).size());r.put("assessmentParticipation",assessments.findAll().stream().filter(x->x.getUser().getId().equals(u.getId())).count());r.put("timeline",timeline(all));r.put("heatmap",heatmap(all));r.put("lastUpdated",Instant.now());return r;}
 private List<Map<String,Object>> timeline(List<Submission> all){Map<LocalDate,List<Submission>> days=all.stream().collect(Collectors.groupingBy(s->s.getSubmittedAt().toLocalDate(),TreeMap::new,Collectors.toList()));Set<Long> seen=new HashSet<>();List<Map<String,Object>> result=new ArrayList<>();for(var e:days.entrySet()){long ac=e.getValue().stream().filter(this::accepted).count();long newly=e.getValue().stream().filter(this::accepted).map(s->s.getProblem().getId()).filter(seen::add).count();result.add(Map.of("date",e.getKey(),"submissions",e.getValue().size(),"accepted",ac,"failed",e.getValue().size()-ac,"problemsSolved",newly));}return result;}
 private Map<String,Object> heatmap(List<Submission> all){LocalDate end=LocalDate.now(),start=end.minusDays(364);Map<LocalDate,List<Submission>> days=all.stream().filter(s->!s.getSubmittedAt().toLocalDate().isBefore(start)).collect(Collectors.groupingBy(s->s.getSubmittedAt().toLocalDate()));List<Map<String,Object>> cells=new ArrayList<>();for(LocalDate d=start;!d.isAfter(end);d=d.plusDays(1)){List<Submission>x=days.getOrDefault(d,List.of());long ac=x.stream().filter(this::accepted).count();long solved=x.stream().filter(this::accepted).map(s->s.getProblem().getId()).distinct().count();cells.add(Map.of("date",d,"submissions",x.size(),"accepted",ac,"problemsSolved",solved));}Set<LocalDate> active=days.keySet();return Map.of("days",cells,"activeDays",active.size(),"currentStreak",streak(active,end),"longestStreak",longest(active));}
 private boolean accepted(Submission s){return "ACCEPTED".equals(s.getStatus());}private int streak(Set<LocalDate>x,LocalDate d){if(!x.contains(d))d=d.minusDays(1);int n=0;while(x.contains(d)){n++;d=d.minusDays(1);}return n;}private int longest(Set<LocalDate>x){int best=0;for(LocalDate d:x){if(x.contains(d.minusDays(1)))continue;int n=0;while(x.contains(d)){n++;d=d.plusDays(1);}best=Math.max(best,n);}return best;}
}
