package com.leetcode.backend.controller;
import com.leetcode.backend.dto.RunCodeRequest; import com.leetcode.backend.dto.RunCodeResponse; import com.leetcode.backend.dto.SubmissionResponse; import com.leetcode.backend.service.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/assessment-sessions") public class AssessmentSessionController {
 private final AssessmentService service; private final AssessmentAccessService access; private final RunCodeService runner; AssessmentSessionController(AssessmentService s,AssessmentAccessService a,RunCodeService r){service=s;access=a;runner=r;}
 private String name(Authentication auth,String grant,Long session){return grant!=null&&!grant.isBlank()?access.participantForSession(grant,session).username():auth==null?null:auth.getName();}
 @PostMapping("/{id}/mcq-answer") public Map<String,Object> mcq(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id,@RequestBody Map<String,Integer> body){return service.submitMcq(name(a,grant,id),id,body.getOrDefault("questionIndex",-1),body.getOrDefault("selectedOption",-1));}
 @PostMapping("/{id}/heartbeat") public Map<String,Object> heartbeat(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id){return service.heartbeat(name(a,grant,id),id);}
 @PostMapping("/{id}/arm") public Map<String,Object> arm(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id){return service.armProctoring(name(a,grant,id),id);}
 @PostMapping("/{id}/proctor-event") public Map<String,Object> event(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id,@RequestBody Map<String,String>b){return service.proctor(name(a,grant,id),id,b.get("type"),b.get("metadata"));}
 @PostMapping("/{id}/finish") public Map<String,Object> finish(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id){return service.finish(name(a,grant,id),id);}
 @PostMapping("/{id}/run") public RunCodeResponse run(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id,@RequestBody RunCodeRequest request){service.authorizeRun(name(a,grant,id),id,request==null?null:request.getProblemId());return runner.run(request);}
 @PostMapping("/{id}/submissions") public SubmissionResponse submit(Authentication a,@RequestHeader(value="X-Assessment-Access",required=false) String grant,@PathVariable Long id,@RequestParam Long problemId,@RequestParam String language,@RequestBody String code){return service.submit(name(a,grant,id),id,problemId,language,code);}
}
