package com.leetcode.backend.controller;
import com.leetcode.backend.dto.*; import com.leetcode.backend.service.ContestService; import com.leetcode.backend.service.ProblemService; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/contests") public class ContestController { private final ContestService service; private final ProblemService problemService; public ContestController(ContestService s,ProblemService p){service=s;problemService=p;}
 @GetMapping public List<ContestResponse> list(Authentication a){boolean admin=a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN"));return admin?service.adminList():service.list(a.getName());} @GetMapping("/{id}") public ContestResponse get(@PathVariable Long id,Authentication a){return service.get(id,a.getName());}
 @PostMapping public ResponseEntity<ContestResponse> create(@Valid @RequestBody ContestRequest r,Authentication a){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(r,a.getName()));} @PutMapping("/{id}") public ContestResponse update(@PathVariable Long id,@Valid @RequestBody ContestRequest r){return service.update(id,r);}
 @PostMapping("/{id}/register") @ResponseStatus(HttpStatus.NO_CONTENT) public void register(@PathVariable Long id,@RequestBody(required=false) Map<String,String> body,Authentication a){service.register(id,body==null?null:body.get("accessCode"),a.getName());}
 @GetMapping("/{id}/problems") public List<ContestProblemResponse> problems(@PathVariable Long id,Authentication a){return service.problems(id,a.getName());} @PostMapping("/{id}/problems") public ResponseEntity<ContestProblemResponse> addProblem(@PathVariable Long id,@Valid @RequestBody ContestProblemRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.addProblem(id,r));}
 @GetMapping("/{id}/problems/{problemId}") public com.leetcode.backend.dto.ProblemDetailResponse problem(@PathVariable Long id,@PathVariable Long problemId,Authentication a){service.assertProblemAccess(id,problemId,a.getName());return problemService.getProblemDetail(problemId,false);}
 @GetMapping("/{id}/leaderboard") public List<ContestStandingResponse> standings(@PathVariable Long id){return service.standings(id);}
}
