package com.leetcode.backend.controller;
import com.leetcode.backend.model.*; import com.leetcode.backend.repository.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/collections") public class CuratedCollectionController {
 final CuratedCollectionRepository collections; final CuratedCollectionItemRepository items; final ProblemRepository problems;
 CuratedCollectionController(CuratedCollectionRepository c,CuratedCollectionItemRepository i,ProblemRepository p){collections=c;items=i;problems=p;}
 void admin(Authentication a){if(a.getAuthorities().stream().noneMatch(x->x.getAuthority().equals("ROLE_ADMIN")))throw new org.springframework.security.access.AccessDeniedException("Admin required.");}
 @GetMapping public List<CuratedCollection> all(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN"))?collections.findAll():collections.findByPublishedTrue();}
 @PostMapping public CuratedCollection create(@RequestBody CuratedCollection b,Authentication a){admin(a);return collections.save(b);}
 @PutMapping("/{id}") public CuratedCollection update(@PathVariable Long id,@RequestBody CuratedCollection b,Authentication a){admin(a);CuratedCollection c=collections.findById(id).orElseThrow();c.setTitle(b.getTitle());c.setDescription(b.getDescription());c.setPublished(b.isPublished());return collections.save(c);}
 @DeleteMapping("/{id}") public void delete(@PathVariable Long id,Authentication a){admin(a);collections.delete(collections.findById(id).orElseThrow());}
 @PostMapping("/{id}/problems/{problemId}") public CuratedCollection add(@PathVariable Long id,@PathVariable Long problemId,Authentication a){admin(a);if(items.existsByCollectionIdAndProblemId(id,problemId))throw new IllegalArgumentException("Problem already exists in collection.");CuratedCollection c=collections.findById(id).orElseThrow();CuratedCollectionItem i=new CuratedCollectionItem();i.setCollection(c);i.setProblem(problems.findById(problemId).orElseThrow());i.setPosition(c.getItems().size());items.save(i);return collections.findById(id).orElseThrow();}
 @DeleteMapping("/{id}/problems/{problemId}") public void remove(@PathVariable Long id,@PathVariable Long problemId,Authentication a){admin(a);CuratedCollection c=collections.findById(id).orElseThrow();c.getItems().removeIf(i->i.getProblem().getId().equals(problemId));collections.save(c);}
 @PutMapping("/{id}/problems/order") public CuratedCollection reorder(@PathVariable Long id,@RequestBody List<Long> ids,Authentication a){admin(a);CuratedCollection c=collections.findById(id).orElseThrow();if(ids.size()!=c.getItems().size()||!new HashSet<>(ids).equals(c.getItems().stream().map(i->i.getProblem().getId()).collect(java.util.stream.Collectors.toSet())))throw new IllegalArgumentException("Order must contain every problem exactly once.");for(int n=0;n<ids.size();n++){Long pid=ids.get(n);c.getItems().stream().filter(i->i.getProblem().getId().equals(pid)).findFirst().orElseThrow().setPosition(n);}return collections.save(c);}
}
