import { Braces, Code2, Eye, EyeOff, FileText, Plus, Settings2, Trash2 } from "lucide-react";

export const VALUE_TYPES = ["int", "Integer", "long", "double", "boolean", "String", "int[]", "long[]", "double[]", "String[]"];

export function AuthoringSection({ number, icon: Icon, title, description, children, className = "" }) {
  return <section className={`vx-author-section ${className}`}>
    <header><span className="vx-author-number">{number}</span><div className="vx-author-icon"><Icon size={17}/></div><div><h2>{title}</h2><p>{description}</p></div></header>
    <div className="vx-author-section-body">{children}</div>
  </section>;
}

export function ProblemBasicsSection({ form, setForm, errors }) {
  const change = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
  return <AuthoringSection number="01" icon={Settings2} title="Basic information" description="Define how the problem is identified, categorized, and published.">
    <div className="vx-author-grid">
      <label className="vx-author-field vx-author-span" htmlFor="title"><span>Problem title <b>Required</b></span><input id="title" name="title" value={form.title} onChange={change} placeholder="e.g. Minimum Window Substring" aria-invalid={Boolean(errors.title)} aria-describedby={errors.title ? "title-error" : undefined}/>{errors.title && <small id="title-error" className="is-error">{errors.title}</small>}</label>
      <label className="vx-author-field" htmlFor="difficulty"><span>Difficulty</span><select id="difficulty" name="difficulty" value={form.difficulty} onChange={change}><option value="EASY">Easy</option><option value="MEDIUM">Medium</option><option value="HARD">Hard</option></select></label>
      <label className="vx-author-field" htmlFor="tags"><span>Topics / tags</span><input id="tags" name="tags" value={form.tags} onChange={change} placeholder="arrays, sliding-window, hashmap"/><small>Separate tags with commas.</small></label>
      <fieldset className="vx-author-field vx-author-span vx-mode-choice"><legend>Execution mode</legend><label className={form.executionMode === "STDIN" ? "active" : ""}><input type="radio" name="executionMode" value="STDIN" checked={form.executionMode === "STDIN"} onChange={change}/><Code2 size={17}/><span><strong>STDIN program</strong><small>Judge complete programs using raw input and output.</small></span></label><label className={form.executionMode === "FUNCTION" ? "active" : ""}><input type="radio" name="executionMode" value="FUNCTION" checked={form.executionMode === "FUNCTION"} onChange={change}/><Braces size={17}/><span><strong>Function contract</strong><small>Wrap and invoke a solution-only function per language.</small></span></label></fieldset>
      <label className="vx-publish-control vx-author-span"><input type="checkbox" name="active" checked={form.active} onChange={change}/><span><strong>{form.active ? "Published and available" : "Saved as inactive draft"}</strong><small>{form.active ? "Users can discover and solve this problem." : "Only administrators can access this problem."}</small></span></label>
    </div>
  </AuthoringSection>;
}

export function ProblemStatementSection({ form, setForm, errors }) {
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  return <AuthoringSection number="02" icon={FileText} title="Problem statement" description="Write the complete contract solvers will read before opening the editor.">
    <div className="vx-author-grid">
      <label className="vx-author-field vx-author-span" htmlFor="description"><span>Description <b>Required</b></span><textarea id="description" name="description" rows="9" value={form.description} onChange={change} placeholder="Explain the goal, inputs, and expected outcome clearly…" aria-invalid={Boolean(errors.description)} aria-describedby={errors.description ? "description-error" : undefined}/>{errors.description && <small id="description-error" className="is-error">{errors.description}</small>}</label>
      <label className="vx-author-field" htmlFor="inputFormat"><span>Input format</span><textarea id="inputFormat" name="inputFormat" rows="6" value={form.inputFormat} onChange={change} placeholder="Describe each input line and value…"/></label>
      <label className="vx-author-field" htmlFor="outputFormat"><span>Output format</span><textarea id="outputFormat" name="outputFormat" rows="6" value={form.outputFormat} onChange={change} placeholder="Describe the expected output…"/></label>
      <label className="vx-author-field" htmlFor="constraints"><span>Constraints</span><textarea id="constraints" name="constraints" rows="6" value={form.constraints} onChange={change} placeholder={'1 ≤ n ≤ 100000\n-10⁹ ≤ values[i] ≤ 10⁹'}/></label>
      <label className="vx-author-field" htmlFor="examples"><span>Examples</span><textarea id="examples" name="examples" rows="6" value={form.examples} onChange={change} placeholder={'Input: nums = [2,7,11,15], target = 9\nOutput: [0,1]'}/></label>
    </div>
  </AuthoringSection>;
}

export function ExecutionSection({ form, setForm, templates, setTemplates, starterLanguage, setStarterLanguage }) {
  const signature = form.functionSignature;
  const updateSignature = (patch) => setForm((current) => ({ ...current, functionSignature: { ...current.functionSignature, ...patch } }));
  const updateParameter = (index, patch) => updateSignature({ parameters: signature.parameters.map((item, position) => position === index ? { ...item, ...patch } : item) });
  return <AuthoringSection number="03" icon={Code2} title="Execution configuration" description="Keep language templates and the judge contract aligned.">
    {form.executionMode === "FUNCTION" && <div className="vx-contract-panel"><div className="vx-author-grid"><label className="vx-author-field"><span>Function name <b>Required</b></span><input value={signature.functionName} onChange={(event) => updateSignature({ functionName: event.target.value })} placeholder="solve" required/></label><label className="vx-author-field"><span>Return type</span><select value={signature.returnType} onChange={(event) => updateSignature({ returnType: event.target.value })}>{VALUE_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label></div><div className="vx-parameter-head"><div><strong>Ordered parameters</strong><small>Argument order is used by every language wrapper.</small></div><button type="button" className="secondary-button" onClick={() => updateSignature({ parameters: [...signature.parameters, { name: "", type: "String", parameterOrder: signature.parameters.length }] })}><Plus size={15}/>Add parameter</button></div><div className="vx-parameter-list">{signature.parameters.length === 0 && <p>No parameters configured.</p>}{signature.parameters.map((parameter, index) => <div className="vx-parameter-row" key={index}><span>{String(index + 1).padStart(2, "0")}</span><label><span className="sr-only">Parameter {index + 1} name</span><input aria-label={`Parameter ${index + 1} name`} value={parameter.name} onChange={(event) => updateParameter(index, { name: event.target.value })} placeholder="name" required/></label><label><span className="sr-only">Parameter {index + 1} type</span><select aria-label={`Parameter ${index + 1} type`} value={parameter.type} onChange={(event) => updateParameter(index, { type: event.target.value })}>{VALUE_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label><button type="button" aria-label={`Remove parameter ${index + 1}`} onClick={() => updateSignature({ parameters: signature.parameters.filter((_, position) => position !== index) })}><Trash2 size={15}/></button></div>)}</div></div>}
    <div className="vx-code-workbench"><div className="vx-language-tabs" role="tablist" aria-label="Starter code language">{[["java", "Java 21"], ["cpp", "C++17"], ["python", "Python 3"]].map(([key, label]) => <button type="button" role="tab" aria-selected={starterLanguage === key} className={starterLanguage === key ? "active" : ""} key={key} onClick={() => setStarterLanguage(key)}>{label}</button>)}</div><label className="vx-author-field" htmlFor="starter-code"><span>Starter code — {starterLanguage === "cpp" ? "C++17" : starterLanguage[0].toUpperCase() + starterLanguage.slice(1)}</span><textarea id="starter-code" className="vx-code-field" rows="14" spellCheck="false" value={templates[starterLanguage]} onChange={(event) => setTemplates((current) => ({ ...current, [starterLanguage]: event.target.value }))} placeholder="Provide the initial code shown in the solver…"/></label></div>
  </AuthoringSection>;
}

export function TestCaseEditor({ mode, cases, setCases, removeCase }) {
  const update = (index, patch) => setCases((items) => items.map((item, position) => position === index ? { ...item, ...patch } : item));
  return <AuthoringSection number="04" icon={Braces} title="Test cases" description="Author visible samples and hidden judge coverage in the same reviewable workspace.">
    <div className="vx-testcase-toolbar"><div><strong>{cases.length} {cases.length === 1 ? "case" : "cases"}</strong><span>At least one visible sample is recommended.</span></div><button type="button" className="secondary-button" onClick={() => setCases((items) => [...items, { inputData: "", expectedOutput: "", functionArguments: "", hidden: false }])}><Plus size={15}/>Add test case</button></div>
    <div className="vx-testcase-list">{cases.length === 0 && <div className="vx-testcase-empty"><Braces size={20}/><strong>No test cases yet</strong><p>Add cases now, or manage them after saving the problem.</p></div>}{cases.map((testCase, index) => <article className="vx-testcase-card" key={testCase.id || `draft-${index}`}><header><div><span>CASE {String(index + 1).padStart(2, "0")}</span><strong>{testCase.hidden ? "Hidden judge case" : "Visible sample"}</strong></div><div><button type="button" className="vx-visibility-button" onClick={() => update(index, { hidden: !testCase.hidden })}>{testCase.hidden ? <EyeOff size={14}/> : <Eye size={14}/>} {testCase.hidden ? "Hidden" : "Visible"}</button><button type="button" className="vx-delete-icon" aria-label={`Remove test case ${index + 1}`} onClick={() => removeCase(testCase, index)}><Trash2 size={15}/></button></div></header><div className="vx-author-grid"><label className="vx-author-field"><span>{mode === "FUNCTION" ? "Function arguments (JSON array)" : "Input"}</span><textarea rows="5" value={mode === "FUNCTION" ? (testCase.functionArguments || testCase.inputData || "") : (testCase.inputData || "")} onChange={(event) => update(index, mode === "FUNCTION" ? { functionArguments: event.target.value, inputData: event.target.value } : { inputData: event.target.value })} placeholder={mode === "FUNCTION" ? '[value1, value2]' : "Input supplied to the program"} required/></label><label className="vx-author-field"><span>Expected output</span><textarea rows="5" value={testCase.expectedOutput || ""} onChange={(event) => update(index, { expectedOutput: event.target.value })} placeholder="Expected normalized output" required/></label></div></article>)}</div>
  </AuthoringSection>;
}
