import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { CalendarDays, CheckCircle2, ClipboardList, LoaderCircle, Plus, Search, Trash2, Users, X } from "lucide-react";
import api from "../services/api";
import AdminShell from "../components/AdminShell";
import { EmptyState, LoadingState } from "../components/PageState";
import StatusPill from "../components/StatusPill";

const empty = { title:"", slug:"", description:"", rulesText:"", startAt:"", endAt:"", visibility:"PUBLIC", accessCode:"", status:"UPCOMING", accent:"#a92d43" };
const formatDate = (value) => value ? new Date(value).toLocaleString() : "Not available";
const statusLabel = (status) => status === "LIVE" ? "Live" : status === "ENDED" ? "Ended" : "Upcoming";

function ContestCreateForm({ problems, onCreated }) {
  const [form, setForm] = useState(empty), [selection, setSelection] = useState({}), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const toggleProblem = (id) => setSelection((current) => { const next = { ...current }; if (next[id]) delete next[id]; else next[id] = 100; return next; });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const created = await api.post("/contests", form); for (const [id, points] of Object.entries(selection)) await api.post(`/contests/${created.data.id}/problems`, { problemId:Number(id), points:Number(points) || 100 }); setForm(empty); setSelection({}); onCreated(created.data.id); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to create the contest and attach its selected problems."); } finally { setSaving(false); } };
  return <details className="admin-contest-create"><summary><Plus size={15}/> Create a contest</summary><form className="vx-admin-contest-form" onSubmit={submit}>
    <div className="vx-admin-form-heading"><span>New contest</span><small>Timing and access are enforced by the server.</small></div>{error && <div className="dashboard-error" role="alert">{error}</div>}
    {[['title','Title'],['slug','URL slug'],['startAt','Start time'],['endAt','End time']].map(([name, label]) => <label key={name}>{label}<input required type={name.endsWith("At") ? "datetime-local" : "text"} value={form[name]} onChange={(event) => setForm({ ...form, [name]:event.target.value })}/></label>)}
    <label className="vx-form-span">Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description:event.target.value })}/></label><label>Visibility<select value={form.visibility} onChange={(event) => setForm({ ...form, visibility:event.target.value })}><option>PUBLIC</option><option>PRIVATE</option></select></label>{form.visibility === "PRIVATE" && <label>Access code<input required value={form.accessCode} onChange={(event) => setForm({ ...form, accessCode:event.target.value })}/></label>}
    <fieldset className="vx-problem-picker"><legend>Contest problem set <span>{Object.keys(selection).length} selected</span></legend>{problems.length === 0 ? <div className="vx-guidance-empty">No problems are available to add.</div> : <div className="vx-problem-picker-list">{problems.map((problem, index) => { const selected = Object.hasOwn(selection, problem.id); return <div className={selected ? "selected" : ""} key={problem.id}><label><input type="checkbox" checked={selected} onChange={() => toggleProblem(problem.id)}/><span className="vx-problem-letter">{String.fromCharCode(65 + index)}</span><span><strong>{problem.title}</strong><small>{problem.difficulty}</small></span></label>{selected && <label className="vx-points-input"><span>Points</span><input type="number" min="1" value={selection[problem.id]} onChange={(event) => setSelection((current) => ({ ...current, [problem.id]:event.target.value }))}/></label>}</div>; })}</div>}</fieldset>
    <button className="primary-button" disabled={saving}>{saving ? "Creating contest…" : "Create contest"}</button>
  </form></details>;
}

export default function AdminContests() {
  const [items, setItems] = useState([]), [problems, setProblems] = useState([]), [selectedContestId, setSelectedContestId] = useState(null), [detail, setDetail] = useState(null), [loading, setLoading] = useState(true), [detailLoading, setDetailLoading] = useState(false), [error, setError] = useState(""), [detailError, setDetailError] = useState(""), [search, setSearch] = useState(""), [confirming, setConfirming] = useState(false), [deleting, setDeleting] = useState(false);
  const load = async (preferredId = null) => { setLoading(true); setError(""); const [contestResult, problemResult] = await Promise.allSettled([api.get("/admin/contests"), api.get("/problems/admin/page", { params:{ page:0, size:100 } })]); if (contestResult.status === "fulfilled") { const contests = contestResult.value.data || []; setItems(contests); setSelectedContestId((current) => preferredId ?? (contests.some((item) => item.id === current) ? current : contests[0]?.id ?? null)); } else setError(contestResult.reason?.response?.data?.message || "Unable to load the contest registry."); if (problemResult.status === "fulfilled") setProblems(problemResult.value.data?.content || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!selectedContestId) { setDetail(null); return; } let active = true; setDetailLoading(true); setDetailError(""); api.get(`/admin/contests/${selectedContestId}`).then((response) => active && setDetail(response.data)).catch((requestError) => active && setDetailError(requestError.response?.data?.message || "Unable to load this contest.")).finally(() => active && setDetailLoading(false)); return () => { active = false; }; }, [selectedContestId]);
  const registrations = useMemo(() => (detail?.registrations || []).filter((registration) => `${registration.username} ${registration.email || ""}`.toLowerCase().includes(search.toLowerCase())), [detail, search]);
  const removeContest = async () => { if (!detail) return; setDeleting(true); setDetailError(""); try { await api.delete(`/admin/contests/${detail.id}`); const index = items.findIndex((item) => item.id === detail.id), nextItems = items.filter((item) => item.id !== detail.id); setItems(nextItems); setConfirming(false); setDetail(null); setSearch(""); setSelectedContestId(nextItems[index]?.id ?? nextItems[index - 1]?.id ?? null); } catch (requestError) { setConfirming(false); setDetailError(requestError.response?.data?.message || "Unable to delete this contest."); } finally { setDeleting(false); } };
  return <AdminShell title="Contests" description="A clear control room for contest setup, participation, and progress.">{error && <div className="dashboard-error" role="alert">{error}</div>}<ContestCreateForm problems={problems} onCreated={(id) => load(id)}/><section className="admin-contest-workspace" aria-label="Contest administration">
    <aside className="admin-contest-list-panel"><div className="admin-contest-panel-head"><div><p className="vx-eyebrow">Competition registry</p><h2>All contests</h2></div><span>{items.length}</span></div>{loading ? <LoadingState label="Loading contests"/> : items.length === 0 ? <EmptyState title="No contests">Create the first competition to begin managing it here.</EmptyState> : <div className="admin-contest-list" role="list">{items.map((contest) => <button type="button" role="listitem" aria-label={`Select ${contest.title}`} aria-pressed={selectedContestId === contest.id} className={selectedContestId === contest.id ? "selected" : ""} onClick={() => setSelectedContestId(contest.id)} key={contest.id}><span className="admin-contest-list-title"><strong>{contest.title}</strong><StatusPill value={contest.status}/></span><time>{formatDate(contest.startTime)} — {formatDate(contest.endTime)}</time><span className="admin-contest-list-meta"><ClipboardList size={13}/>{contest.problemCount} problems <Users size={13}/>{contest.registrationCount} registered</span></button>)}</div>}</aside>
    <section className="admin-contest-detail-panel" aria-live="polite">{!selectedContestId && !loading && <EmptyState title="Select a contest">Choose a contest from the registry to inspect its problems and registered users.</EmptyState>}{detailLoading && <LoadingState label="Loading contest details"/>}{detailError && <div className="dashboard-error" role="alert">{detailError}</div>}{detail && !detailLoading && <>
      <header className="admin-contest-detail-head"><div><p className="vx-eyebrow">Contest overview</p><div className="admin-contest-title"><h2>{detail.title}</h2><StatusPill value={detail.status}/></div><p>{detail.description || "No description was provided for this contest."}</p><time><CalendarDays size={15}/>{formatDate(detail.startTime)} — {formatDate(detail.endTime)}</time></div><button className="admin-contest-delete" type="button" onClick={() => setConfirming(true)}><Trash2 size={15}/> Delete contest</button></header>
      <div className="admin-contest-summary"><article><ClipboardList size={17}/><span>Total problems</span><strong>{detail.problemCount}</strong></article><article><Users size={17}/><span>Registered users</span><strong>{detail.registrationCount}</strong></article><article><CheckCircle2 size={17}/><span>Contest status</span><strong>{statusLabel(detail.status)}</strong></article></div>
      <section className="admin-contest-section"><div className="admin-contest-section-head"><div><p className="vx-eyebrow">Problem set</p><h3>Assigned problems</h3></div><span>{detail.problemCount} total</span></div>{detail.problems.length === 0 ? <div className="vx-guidance-empty">No problems have been assigned to this contest.</div> : <div className="admin-contest-problem-table">{detail.problems.map((problem) => <article key={problem.id}><b>{problem.order}</b><div><Link to={`/admin/problems/edit/${problem.id}`}>{problem.title}</Link><span>{problem.tags?.map((tag) => <i key={tag}>{tag}</i>)}</span></div><StatusPill value={problem.difficulty}/></article>)}</div>}</section>
      <section className="admin-contest-section"><div className="admin-contest-section-head"><div><p className="vx-eyebrow">Participant record</p><h3>Registered users</h3></div><label className="admin-contest-search"><Search size={15}/><span className="sr-only">Search registered users</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users"/></label></div>{detail.registrations.length === 0 ? <div className="vx-guidance-empty">No users have registered for this contest.</div> : <div className="admin-contest-registration-table"><div className="admin-contest-registration-head"><span>User</span><span>Registered</span><span>Solved</span><span>Progress</span></div>{registrations.map((registration) => { const percent = registration.totalProblems ? Math.round((registration.solvedCount / registration.totalProblems) * 100) : 0; return <article key={registration.userId}><div><strong>{registration.username}</strong><small>{registration.email || "No email available"}</small></div><time>{formatDate(registration.registeredAt)}</time><strong>{registration.solvedCount}</strong><div className="admin-contest-progress"><span aria-label={`${registration.solvedCount} of ${registration.totalProblems} solved`}><i style={{ width:`${percent}%` }}/></span><small>{registration.solvedCount} / {registration.totalProblems} solved</small></div></article>; })}</div>}{detail.registrations.length > 0 && registrations.length === 0 && <div className="vx-guidance-empty">No registered users match that search.</div>}</section>
    </>}</section></section>
    {confirming && detail && <div className="admin-contest-dialog-backdrop" role="presentation"><section className="admin-contest-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-contest-title"><button className="admin-contest-dialog-close" type="button" onClick={() => setConfirming(false)} aria-label="Close delete confirmation"><X size={18}/></button><Trash2 aria-hidden="true"/><p className="vx-eyebrow">Destructive action</p><h2 id="delete-contest-title">Delete “{detail.title}”?</h2><p>This removes its registrations and contest-specific problem links. Users, global problems, and normal submission history will not be deleted.</p><div><button className="secondary-button" type="button" disabled={deleting} onClick={() => setConfirming(false)}>Cancel</button><button className="admin-contest-delete" type="button" disabled={deleting} onClick={removeContest}>{deleting ? <><LoaderCircle className="admin-contest-spin" size={15}/> Deleting…</> : <><Trash2 size={15}/> Delete contest</>}</button></div></section></div>}
  </AdminShell>;
}
