import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, CalendarDays, CheckCircle2, Code2, Flame, Trophy, UserRound } from "lucide-react";
import api from "../services/api";

const formatDate = (value) => value ? new Date(value).toLocaleString() : "No activity recorded";
const displayLanguage = (value) => ({ cpp: "C++", python: "Python", java: "Java" }[String(value).toLowerCase()] || value);
const Metric = ({ label, value, tone = "neutral" }) => <article className={`admin-user-metric admin-user-metric--${tone}`}><span>{label}</span><strong>{value ?? "—"}</strong></article>;

export default function AdminUserDetail() {
  const { id } = useParams(); const navigate = useNavigate();
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { setData(null); setError(""); api.get(`/admin/users/${id}/analytics`).then((response) => setData(response.data)).catch(() => setError("Unable to load user analytics.")); }, [id]);
  const languages = useMemo(() => Object.entries(data?.languageUsage || {}).sort(([, a], [, b]) => b - a), [data]);
  const languageTotal = languages.reduce((total, [, count]) => total + count, 0);
  if (error) return <main className="user-page-container admin-user-analytics"><button className="admin-user-back" onClick={() => navigate("/admin/users")}><ArrowLeft size={16} /> Back to users</button><p className="dashboard-error" role="alert">{error}</p></main>;
  if (!data) return <main className="user-page-container admin-user-analytics"><p className="admin-user-loading">Loading user analytics...</p></main>;
  const solvedMix = [["Easy", data.easySolved, "easy"], ["Medium", data.mediumSolved, "medium"], ["Hard", data.hardSolved, "hard"]];
  return <main className="user-page-container admin-user-analytics">
    <button className="admin-user-back" onClick={() => navigate("/admin/users")}><ArrowLeft size={16} /> Back to users</button>
    <header className="admin-user-hero"><div className="admin-user-identity"><div className="admin-user-avatar"><UserRound size={24} /></div><div><p className="admin-user-kicker">User intelligence report</p><h1>{data.username}</h1><p><b className="admin-user-role">{data.role}</b> account <i /> Last activity {formatDate(data.lastCodingActivity)}</p></div></div><div className="admin-user-hero-stat"><Trophy size={18} /><span>Problems solved</span><strong>{data.solvedTotal ?? 0}</strong><small>Lifetime completions</small></div></header>
    <section className="admin-user-overview"><div className="admin-user-metrics"><Metric label="Total submissions" value={data.totalSubmissions} /><Metric label="Accepted" value={data.acceptedSubmissions} tone="success" /><Metric label="Acceptance rate" value={`${data.acceptanceRate ?? 0}%`} tone="accent" /><Metric label="Active days" value={data.activeDays} /></div><aside className="admin-user-streaks"><div><Flame size={17} /><span>Current streak</span><strong>{data.currentStreak ?? 0}<small> days</small></strong></div><div><CalendarDays size={17} /><span>Longest streak</span><strong>{data.longestStreak ?? 0}<small> days</small></strong></div></aside></section>
    <section className="admin-user-section"><div className="admin-user-section-heading"><div><p className="admin-user-kicker">Completion profile</p><h2>Solved by difficulty</h2></div><span>{data.solvedTotal ?? 0} total solved</span></div><div className="admin-user-difficulty-grid">{solvedMix.map(([label, count, tone]) => <article className={`admin-user-difficulty admin-user-difficulty--${tone}`} key={label}><span>{label}</span><strong>{count ?? 0}</strong><div><i style={{ width: `${data.solvedTotal ? Math.round(((count || 0) / data.solvedTotal) * 100) : 0}%` }} /></div></article>)}</div></section>
    <section className="admin-user-two-column"><div className="admin-user-section"><div className="admin-user-section-heading"><div><p className="admin-user-kicker">Submission tooling</p><h2>Language usage</h2></div><Code2 size={19} /></div>{languages.length ? <div className="admin-user-language-list">{languages.map(([language, count]) => <div key={language}><div><strong>{displayLanguage(language)}</strong><span>{count} submissions</span></div><div className="admin-user-language-track"><i style={{ width: `${Math.round((count / languageTotal) * 100)}%` }} /></div><b>{Math.round((count / languageTotal) * 100)}%</b></div>)}</div> : <p className="admin-user-empty">No submissions yet.</p>}</div><div className="admin-user-section"><div className="admin-user-section-heading"><div><p className="admin-user-kicker">Recent signal</p><h2>Activity summary</h2></div><CheckCircle2 size={19} /></div><div className="admin-user-summary"><div><span>Attempts</span><strong>{data.totalSubmissions ?? 0}</strong></div><div><span>Successful</span><strong>{data.acceptedSubmissions ?? 0}</strong></div><div><span>Active days</span><strong>{data.activeDays ?? 0}</strong></div></div></div></section>
    <section className="admin-user-section admin-user-activity"><div className="admin-user-section-heading"><div><p className="admin-user-kicker">Submission trail</p><h2>Recent activity</h2></div><span>{data.recentSubmissions?.length || 0} latest records</span></div>{data.recentSubmissions?.length ? <div className="admin-user-activity-list"><div className="admin-user-activity-column-head" aria-hidden="true"><span>Challenge</span><span>Result</span><span>Language</span><span>Submitted</span></div>{data.recentSubmissions.map((submission) => <article key={submission.id}><div className="admin-user-activity-icon"><Code2 size={16} /></div><strong>{submission.problemTitle}</strong><span className={`admin-user-verdict admin-user-verdict--${String(submission.status).toLowerCase()}`}>{String(submission.status).replaceAll("_", " ")}</span><span>{displayLanguage(submission.language)}</span><time>{formatDate(submission.submittedAt)}</time></article>)}</div> : <p className="admin-user-empty">No recent activity.</p>}</section>
  </main>;
}
