import { useState } from "react";
import { ArrowRight, Lock, User } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import api from "../services/api";
import BrandLogo from "../components/BrandLogo";

export default function Login() {
  const navigate = useNavigate(); const [form, setForm] = useState({ username: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(""); setLoading(true); try { const response = await api.post("/auth/login", form); const { token, username, role } = response.data; localStorage.setItem("algosphere_token", token); localStorage.setItem("algosphere_username", username); localStorage.setItem("algosphere_role", role); window.dispatchEvent(new Event("verdixa-authenticated")); navigate(role === "ADMIN" ? "/admin" : "/dashboard"); } catch (reason) { setError([401,403].includes(reason.response?.status) ? "Invalid username or password." : "Unable to connect to Verdixa server."); } finally { setLoading(false); } };
  return <main className="vx-auth"><section className="vx-auth-manifest"><div className="vx-auth-brand"><BrandLogo/><span>VERDIXA / 01</span></div><div><p className="vx-eyebrow">Engineering practice</p><h1>Precision is<br/>a habit.</h1><p>Code. Execute. Evolve.</p></div><small>Java · C++ · Python<br/>Deterministic judging</small></section><section className="vx-auth-form"><div><span className="vx-section-meta">Secure workspace access</span><h2>Welcome back</h2><p>Continue where your last problem left off.</p>{error && <div className="error-message" role="alert">{error}</div>}<form onSubmit={submit}><label>Username<div className="input-wrapper"><User size={17}/><input name="username" autoComplete="username" value={form.username} onChange={(event) => setForm({...form, username:event.target.value})} required placeholder="Your username"/></div></label><label>Password<div className="input-wrapper"><Lock size={17}/><input name="password" type="password" autoComplete="current-password" value={form.password} onChange={(event) => setForm({...form, password:event.target.value})} required placeholder="Your password"/></div></label><button className="login-button" disabled={loading}>{loading ? "Signing in…" : "Enter workspace"}<ArrowRight size={17}/></button></form><p className="register-link">New to Verdixa? <Link to="/register">Create an account</Link></p></div></section></main>;
}
