import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, expect, test, vi } from "vitest";
vi.mock("@monaco-editor/react", () => ({ default: ({ value }) => <textarea aria-label="Code editor" value={value} readOnly /> }));
vi.mock("../services/api", () => ({ default: { get: vi.fn(), post: vi.fn(), put: vi.fn(), delete: vi.fn() } }));
import api from "../services/api";
import ProblemSolver from "./ProblemSolver";
const renderSolver=()=>render(<MemoryRouter initialEntries={["/problems/2"]}><Routes><Route path="/problems/:id" element={<ProblemSolver/>}/></Routes></MemoryRouter>);
beforeEach(()=>{localStorage.setItem("algosphere_token","test");vi.clearAllMocks();api.get.mockImplementation((url)=>{if(url==="/problems/2")return Promise.resolve({data:{id:2,title:"Reverse String",description:"Reverse a string.",difficulty:"EASY",tags:"String",executionMode:"FUNCTION",functionSignature:{functionName:"reverseString",returnType:"String",parameters:[{name:"s",type:"String"}]}}});if(url==="/bookmarks/2")return Promise.resolve({data:false});if(url==="/users/me")return Promise.resolve({data:{id:1}});if(url.includes("/submissions/"))return Promise.resolve({data:[]});return Promise.resolve({data:[]});});});
test("FUNCTION problem renders title, signature and editor without crashing",async()=>{renderSolver();expect(screen.getByText("Loading problem...")).toBeInTheDocument();expect(await screen.findByText("Reverse String")).toBeInTheDocument();expect(screen.getByText(/reverseString\(s: String\)/)).toBeInTheDocument();expect(screen.getByLabelText("Code editor")).toBeInTheDocument();});
test("FUNCTION custom input builder derives the ordered parameter",async()=>{renderSolver();await screen.findByText("Reverse String");expect(screen.getAllByPlaceholderText('"hello"')).toHaveLength(2);expect(screen.getByText("Run Input")).toBeInTheDocument();expect(screen.getByText("Run All Inputs")).toBeInTheDocument();expect(screen.getByText("+ Add Custom Input")).toBeInTheDocument();});
test("missing FUNCTION metadata remains renderable with an admin-facing warning",async()=>{api.get.mockImplementation((url)=>url==="/problems/2"?Promise.resolve({data:{id:2,title:"Legacy Function",description:"x",difficulty:"EASY",executionMode:"FUNCTION"}}):Promise.resolve({data:[]}));renderSolver();expect(await screen.findByText("Legacy Function")).toBeInTheDocument();expect(screen.getAllByText(/Function configuration unavailable/).length).toBeGreaterThan(0);});
test("problem load failure shows recovery UI",async()=>{api.get.mockRejectedValue(new Error("network"));renderSolver();expect(await screen.findByText("Problem unavailable")).toBeInTheDocument();expect(screen.getByText("Back to Problems")).toBeInTheDocument();});
test("detail failures are classified instead of being presented as an unavailable problem",async()=>{api.get.mockRejectedValue({response:{status:404}});renderSolver();expect(await screen.findByText("Problem not found or no longer published.")).toBeInTheDocument();expect(screen.getByText("Retry")).toBeInTheDocument();});
test("forbidden detail requests preserve the session and explain access",async()=>{api.get.mockRejectedValue({response:{status:403}});renderSolver();expect(await screen.findByText("You do not have access to this problem.")).toBeInTheDocument();expect(localStorage.getItem("algosphere_token")).toBe("test");});
test("Python displays snake_case signature and solution-only starter",async()=>{renderSolver();await screen.findByText("Reverse String");fireEvent.change(screen.getByRole("combobox"),{target:{value:"python"}});expect(screen.getByText(/reverse_string\(s: String\)/)).toBeInTheDocument();expect(screen.getByLabelText("Code editor").value).toContain("def reverse_string(s):");expect(screen.getByLabelText("Code editor").value).not.toContain("def main");expect(screen.getAllByPlaceholderText('"hello"')).toHaveLength(2);});
test("successful Submit renders verdict and refreshes history",async()=>{api.post.mockResolvedValue({data:{id:9,status:"ACCEPTED",passedTestCases:5,totalTestCases:5,executionTimeMs:4}});renderSolver();await screen.findByText("Reverse String");fireEvent.click(screen.getByText("Submit"));expect(await screen.findByText("ACCEPTED")).toBeInTheDocument();await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/submissions?problemId=2&language=java",expect.any(String),expect.any(Object)));expect(api.get.mock.calls.filter(([url])=>url.includes("/submissions/user/")).length).toBeGreaterThan(1);});
test("Submit API error displays the safe backend message",async()=>{api.post.mockRejectedValue({response:{status:400,data:{message:"Problem configuration is incomplete."}}});renderSolver();await screen.findByText("Reverse String");fireEvent.click(screen.getByText("Submit"));expect(await screen.findByText("Problem configuration is incomplete.")).toBeInTheDocument();});
test("STDIN problem renders full-program editor and stdin input only",async()=>{api.get.mockImplementation((url)=>url==="/problems/2"?Promise.resolve({data:{id:2,title:"Echo",description:"Echo input",difficulty:"EASY",executionMode:"STDIN",starterCode:JSON.stringify({java:"public class Main {}",cpp:"int main() {}",python:"def main():\n    print(input())\n\nif __name__ == '__main__':\n    main()"})}}):url==="/bookmarks/2"?Promise.resolve({data:false}):url==="/users/me"?Promise.resolve({data:{id:1}}):Promise.resolve({data:[]}));renderSolver();await screen.findByText("Echo");fireEvent.change(screen.getByRole("combobox"),{target:{value:"python"}});expect(screen.getByLabelText("Code editor").value).toContain("def main()");expect(screen.getByText(/Provide stdin for Run Code/)).toBeInTheDocument();expect(screen.getByPlaceholderText("Example: hello")).toBeInTheDocument();expect(screen.queryByText("+ Add Custom Input")).not.toBeInTheDocument();});

test("hints show per-hint locked progress without leaking content",async()=>{api.get.mockImplementation((url)=>url==="/problems/2/hints"?Promise.resolve({data:{total:2,unlocked:0,attempts:2,hints:[{id:1,orderIndex:1,revealed:false,available:false,locked:true,attemptsRequired:3,attemptsRemaining:1,penaltyPoints:0},{id:2,orderIndex:2,revealed:false,available:false,locked:true,attemptsRequired:6,attemptsRemaining:4,penaltyPoints:0}]}}):url==="/problems/2"?Promise.resolve({data:{id:2,title:"Hint problem",description:"x",difficulty:"EASY",executionMode:"STDIN"}}):url==="/bookmarks/2"?Promise.resolve({data:false}):url==="/users/me"?Promise.resolve({data:{id:1}}):Promise.resolve({data:[]}));renderSolver();await screen.findByText("Hint problem");fireEvent.click(screen.getByRole("tab",{name:/Hints/}));expect(screen.getByText("2 of 3 attempts completed")).toBeInTheDocument();expect(screen.getByText("Available after 1 more attempt.")).toBeInTheDocument();expect(screen.queryByText("Secret hint")).not.toBeInTheDocument();});

test("second hint stays locked until six attempts",async()=>{api.get.mockImplementation((url)=>url==="/problems/2/hints"?Promise.resolve({data:{total:2,unlocked:1,attempts:5,hints:[{id:1,title:"First",content:"First content",revealed:true,available:true,attemptsRequired:3,attemptsRemaining:0,penaltyPoints:0},{id:2,revealed:false,available:false,locked:true,attemptsRequired:6,attemptsRemaining:1,penaltyPoints:0}]}}):url==="/problems/2"?Promise.resolve({data:{id:2,title:"Milestones",description:"x",difficulty:"EASY",executionMode:"STDIN"}}):url==="/bookmarks/2"?Promise.resolve({data:false}):url==="/users/me"?Promise.resolve({data:{id:1}}):Promise.resolve({data:[]}));renderSolver();await screen.findByText("Milestones");fireEvent.click(screen.getByRole("tab",{name:/Hints/}));expect(screen.getByText("First content")).toBeInTheDocument();expect(screen.getByText("5 of 6 attempts completed")).toBeInTheDocument();});

test("available hint can be revealed and refreshed from persisted server state",async()=>{let revealed=false;api.get.mockImplementation((url)=>url==="/problems/2/hints"?Promise.resolve({data:{total:1,unlocked:revealed?1:0,attempts:3,hints:[{id:1,title:revealed?"Direction":null,content:revealed?"Use a map":null,revealed,available:true,locked:false,attemptsRequired:3,attemptsRemaining:0,penaltyPoints:0}]}}):url==="/problems/2"?Promise.resolve({data:{id:2,title:"Reveal",description:"x",difficulty:"EASY",executionMode:"STDIN"}}):url==="/bookmarks/2"?Promise.resolve({data:false}):url==="/users/me"?Promise.resolve({data:{id:1}}):Promise.resolve({data:[]}));api.post.mockImplementation(()=>{revealed=true;return Promise.resolve({data:{}})});renderSolver();await screen.findByText("Reveal");fireEvent.click(screen.getByRole("tab",{name:/Hints/}));fireEvent.click(screen.getByRole("button",{name:"Reveal hint"}));expect(await screen.findByText("Use a map")).toBeInTheDocument();expect(api.get.mock.calls.filter(([url])=>url==="/problems/2/hints")).toHaveLength(2);});
