import { useEffect, useState } from "react";
import { ArrowLeft, BookOpenCheck, Loader2, Save, Sparkles } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import AdminShell from "../components/AdminShell";
import EditorialContent from "../components/EditorialContent";
import { ExecutionSection, ProblemBasicsSection, ProblemStatementSection, TestCaseEditor } from "../components/admin/ProblemAuthoringSections";
import api from "../services/api";

const emptyForm = { title: "", difficulty: "EASY", tags: "", description: "", inputFormat: "", outputFormat: "", constraints: "", examples: "", active: false, executionMode: "STDIN", functionSignature: { functionName: "", returnType: "String", parameters: [] } };
const emptyEditorial = { title: "", intuition: "", keyObservations: "", correctness: "", referenceGuidance: "", approach: "", algorithmExplanation: "", edgeCases: "", timeComplexity: "", spaceComplexity: "", javaSolution: "", cppSolution: "", pythonSolution: "", published: false };
const messageOf = (error, fallback) => error.response?.data?.message || fallback;

function GuidanceSection({ id, hints, setHints, editorial, setEditorial, saving, setSaving, setStatus }) {
  const saveHint = async (hint, index) => {
    if (!hint.title?.trim() || !hint.content?.trim()) return setStatus({ type: "error", text: "Hint title and guidance are required." });
    setSaving(true); setStatus(null);
    try { const payload = { title: hint.title.trim(), content: hint.content.trim(), penaltyPoints: Number(hint.penaltyPoints) || 0, active: hint.active !== false }; const response = hint.id ? await api.put(`/problems/${id}/hints/${hint.id}`, payload) : await api.post(`/problems/${id}/hints`, payload); setHints((items) => items.map((item, position) => position === index ? response.data : item)); setStatus({ type: "success", text: `Hint ${index + 1} saved.` }); }
    catch (error) { setStatus({ type: "error", text: messageOf(error, "Unable to save this hint.") }); } finally { setSaving(false); }
  };
  const removeHint = async (hint, index) => { if (hint.id && !window.confirm("Delete this hint? This cannot be undone.")) return; setSaving(true); try { if (hint.id) await api.delete(`/problems/${id}/hints/${hint.id}`); setHints((items) => items.filter((_, position) => position !== index)); setStatus({ type: "success", text: "Hint removed." }); } catch (error) { setStatus({ type: "error", text: messageOf(error, "Unable to remove this hint.") }); } finally { setSaving(false); } };
  const saveEditorial = async () => { const required = ["title", "intuition", "approach", "algorithmExplanation", "timeComplexity", "spaceComplexity", "javaSolution", "cppSolution", "pythonSolution"]; if (required.some((field) => !String(editorial[field] || "").trim())) return setStatus({ type: "error", text: "Complete every required editorial field before saving." }); setSaving(true); setStatus(null); try { const { data } = await api.put(`/problems/${id}/editorial`, editorial); setEditorial(data); setStatus({ type: "success", text: "Editorial saved successfully." }); } catch (error) { setStatus({ type: "error", text: messageOf(error, "Unable to save the editorial.") }); } finally { setSaving(false); } };
  return <section className="vx-author-section"><header><span className="vx-author-number">05</span><div className="vx-author-icon"><Sparkles size={17}/></div><div><h2>Editorial & guidance</h2><p>Progressive hints and a structured reference solution for post-attempt learning.</p></div></header><div className="vx-author-section-body">
    {!id ? <div className="vx-author-notice"><BookOpenCheck size={18}/><div><strong>Available after the first save</strong><p>Create the problem and this workspace will reopen with guidance controls enabled.</p></div></div> : <div className="vx-guidance-workspace"><div className="vx-guidance-heading"><div><strong>Progressive hints</strong><small>{hints.length} configured · available after the third attempt</small></div><button type="button" className="secondary-button" onClick={() => setHints((items) => [...items, { title: "", content: "", penaltyPoints: 0, active: true }])}>Add hint</button></div><div className="vx-hint-editor-list">{hints.length === 0 && <div className="vx-guidance-empty">No hints configured yet.</div>}{hints.map((hint, index) => <article className="vx-hint-editor" key={hint.id || index}><header><strong>Hint {index + 1}</strong><small>{hint.id ? "Saved" : "Draft"}</small></header><label>Title<input value={hint.title || ""} onChange={(event) => setHints((items) => items.map((item, position) => position === index ? { ...item, title: event.target.value } : item))}/></label><label className="vx-form-span">Guidance<textarea rows="4" value={hint.content || ""} onChange={(event) => setHints((items) => items.map((item, position) => position === index ? { ...item, content: event.target.value } : item))}/></label><label>Penalty points<input type="number" min="0" value={hint.penaltyPoints ?? 0} onChange={(event) => setHints((items) => items.map((item, position) => position === index ? { ...item, penaltyPoints: event.target.value } : item))}/></label><label className="checkbox-label"><input type="checkbox" checked={hint.active !== false} onChange={(event) => setHints((items) => items.map((item, position) => position === index ? { ...item, active: event.target.checked } : item))}/><span>Available when unlocked</span></label><div className="vx-hint-actions"><button type="button" className="secondary-button" disabled={saving} onClick={() => saveHint(hint, index)}>Save hint</button><button type="button" className="danger-button" disabled={saving} onClick={() => removeHint(hint, index)}>Delete</button></div></article>)}</div>
      <details className="vx-editorial-disclosure"><summary>Technical editorial <span>{editorial.published ? "Published" : "Draft"}</span></summary><div className="vx-editorial-editor"><label className="vx-publish-control"><input type="checkbox" checked={Boolean(editorial.published)} onChange={(event) => setEditorial((value) => ({ ...value, published: event.target.checked }))}/><span><strong>Publish editorial</strong><small>Make the completed editorial eligible for user access.</small></span></label><div className="vx-author-grid">{[["title", "Title", 1], ["intuition", "Intuition", 5], ["keyObservations", "Key observations", 4], ["correctness", "Correctness", 4], ["referenceGuidance", "Reference guidance", 4], ["approach", "Approach", 5], ["algorithmExplanation", "Algorithm", 5], ["edgeCases", "Edge cases", 4], ["timeComplexity", "Time complexity", 3], ["spaceComplexity", "Space complexity", 3]].map(([field, label, rows]) => <label className={`vx-author-field ${["title", "intuition", "approach", "algorithmExplanation"].includes(field) ? "vx-author-span" : ""}`} key={field}><span>{label}</span>{rows === 1 ? <input value={editorial[field] || ""} onChange={(event) => setEditorial((value) => ({ ...value, [field]: event.target.value }))}/> : <textarea rows={rows} value={editorial[field] || ""} onChange={(event) => setEditorial((value) => ({ ...value, [field]: event.target.value }))}/>}</label>)}</div><div className="vx-editorial-code-grid">{[["javaSolution", "Java"], ["cppSolution", "C++17"], ["pythonSolution", "Python"]].map(([field, label]) => <label className="vx-author-field" key={field}><span>{label} solution</span><textarea className="vx-code-field" rows="10" value={editorial[field] || ""} onChange={(event) => setEditorial((value) => ({ ...value, [field]: event.target.value }))}/></label>)}</div><details><summary>Preview editorial</summary><EditorialContent editorial={editorial}/></details><button type="button" className="primary-button" disabled={saving} onClick={saveEditorial}>{saving ? "Saving…" : "Save editorial"}</button></div></details>
    </div>}
  </div></section>;
}

export default function ProblemForm() {
  const navigate = useNavigate(); const location = useLocation(); const { id } = useParams(); const isEditMode = Boolean(id);
  const [loading, setLoading] = useState(isEditMode), [saving, setSaving] = useState(false), [guidanceSaving, setGuidanceSaving] = useState(false);
  const [form, setForm] = useState(emptyForm), [starterLanguage, setStarterLanguage] = useState("java"), [templates, setTemplates] = useState({ java: "", cpp: "", python: "" });
  const [testCases, setTestCases] = useState([]), [deletedTestCaseIds, setDeletedTestCaseIds] = useState([]), [hints, setHints] = useState([]), [editorial, setEditorial] = useState(emptyEditorial);
  const [errors, setErrors] = useState({}), [status, setStatus] = useState(location.state?.status ? { type: "success", text: location.state.status } : null);

  useEffect(() => { if (localStorage.getItem("algosphere_role") !== "ADMIN") { navigate("/dashboard"); return; } if (!isEditMode) return; let active = true; Promise.all([api.get(`/problems/${id}`), api.get(`/problems/${id}/testcases/all`), api.get(`/problems/${id}/hints/admin`).catch(() => ({ data: [] })), api.get(`/problems/${id}/editorial`).catch(() => ({ data: emptyEditorial }))]).then(([problemResult, casesResult, hintsResult, editorialResult]) => { if (!active) return; const problem = problemResult.data; setForm({ ...emptyForm, ...problem, functionSignature: problem.functionSignature || emptyForm.functionSignature }); try { const parsed = JSON.parse(problem.starterCode || "{}"); setTemplates((current) => ({ ...current, ...(parsed && typeof parsed === "object" ? parsed : { java: problem.starterCode || "" }) })); } catch { setTemplates((current) => ({ ...current, java: problem.starterCode || "" })); } setTestCases(casesResult.data || []); setHints(hintsResult.data || []); setEditorial((current) => ({ ...current, ...editorialResult.data })); }).catch((error) => setStatus({ type: "error", text: messageOf(error, "Unable to load this problem.") })).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id, isEditMode, navigate]);

  const validate = () => { const next = {}; if (!form.title.trim()) next.title = "Enter a problem title."; if (!form.description.trim()) next.description = "Enter the complete problem description."; if (form.executionMode === "FUNCTION" && !form.functionSignature.functionName.trim()) next.functionName = "Enter a function name."; testCases.forEach((item, index) => { const input = form.executionMode === "FUNCTION" ? (item.functionArguments || item.inputData) : item.inputData; if (!input?.trim() || !item.expectedOutput?.trim()) next.testCases = `Complete the input and expected output for test case ${index + 1}.`; }); setErrors(next); if (Object.keys(next).length) setStatus({ type: "error", text: Object.values(next)[0] }); return Object.keys(next).length === 0; };
  const testCasePayload = (item) => ({ inputData: item.inputData, expectedOutput: item.expectedOutput, functionArguments: form.executionMode === "FUNCTION" ? (item.functionArguments || item.inputData) : null, hidden: Boolean(item.hidden) });
  const persistCases = async (problemId) => { for (const deletedId of deletedTestCaseIds) await api.delete(`/problems/${problemId}/testcases/${deletedId}`); for (const testCase of testCases) { const payload = testCasePayload(testCase); if (testCase.id) await api.put(`/problems/${problemId}/testcases/${testCase.id}`, payload); else await api.post(`/problems/${problemId}/testcases`, payload); } };
  const submit = async (event) => { event.preventDefault(); if (!validate()) return; setSaving(true); setStatus(null); const payload = { title: form.title.trim(), difficulty: form.difficulty, tags: form.tags.trim(), description: form.description.trim(), inputFormat: form.inputFormat.trim(), outputFormat: form.outputFormat.trim(), constraints: form.constraints.trim(), examples: form.examples.trim(), starterCode: JSON.stringify(templates), active: form.active, executionMode: form.executionMode, functionSignature: form.executionMode === "FUNCTION" ? { ...form.functionSignature, parameters: form.functionSignature.parameters.map((parameter, index) => ({ ...parameter, parameterOrder: index })) } : null }; try { const response = isEditMode ? await api.put(`/problems/${id}`, payload) : await api.post("/problems", payload); const problemId = id || response.data.id; await persistCases(problemId); if (isEditMode) { setDeletedTestCaseIds([]); setStatus({ type: "success", text: "Problem and test cases updated successfully." }); } else navigate(`/admin/problems/edit/${problemId}`, { replace: true, state: { status: "Problem created successfully. You can now add guidance or continue editing." } }); } catch (error) { setStatus({ type: "error", text: messageOf(error, "Unable to save the problem. Your existing data was not discarded.") }); } finally { setSaving(false); } };
  const removeCase = (testCase, index) => { if (testCase.id && !window.confirm("Remove this saved test case when you save the problem?")) return; if (testCase.id) setDeletedTestCaseIds((items) => [...items, testCase.id]); setTestCases((items) => items.filter((_, position) => position !== index)); };

  const actions = <><button type="button" className="secondary-button" onClick={() => navigate("/admin/problems")} disabled={saving}>Cancel</button><button form="problem-authoring-form" className="primary-button" disabled={saving || loading}>{saving ? <><Loader2 size={16} className="spin"/>Saving…</> : <><Save size={16}/>{isEditMode ? "Update Problem" : "Create Problem"}</>}</button></>;
  return <AdminShell eyebrow="Problem library / Authoring" title={isEditMode ? "Edit problem" : "Add problem"} description="Build a production-ready statement, execution contract, and judge suite from one focused workspace." actions={actions}>
    {loading ? <div className="vx-author-loading"><Loader2 size={20} className="spin"/>Loading authoring workspace…</div> : <form id="problem-authoring-form" className="vx-problem-author" onSubmit={submit} noValidate><nav className="vx-author-nav" aria-label="Problem form sections"><a href="#basics">01 Basics</a><a href="#statement">02 Statement</a><a href="#execution">03 Execution</a><a href="#cases">04 Test cases</a><a href="#guidance">05 Guidance</a></nav>{status && <div className={`vx-author-status is-${status.type}`} role={status.type === "error" ? "alert" : "status"}>{status.text}</div>}<div id="basics"><ProblemBasicsSection form={form} setForm={setForm} errors={errors}/></div><div id="statement"><ProblemStatementSection form={form} setForm={setForm} errors={errors}/></div><div id="execution"><ExecutionSection form={form} setForm={setForm} templates={templates} setTemplates={setTemplates} starterLanguage={starterLanguage} setStarterLanguage={setStarterLanguage}/></div><div id="cases"><TestCaseEditor mode={form.executionMode} cases={testCases} setCases={setTestCases} removeCase={removeCase}/>{errors.testCases && <p className="vx-inline-error" role="alert">{errors.testCases}</p>}</div><div id="guidance"><GuidanceSection id={id} hints={hints} setHints={setHints} editorial={editorial} setEditorial={setEditorial} saving={guidanceSaving} setSaving={setGuidanceSaving} setStatus={setStatus}/></div><footer className="vx-author-footer"><button type="button" className="secondary-button" onClick={() => navigate("/admin/problems")}><ArrowLeft size={15}/>Back to library</button><span>Changes are applied only when you save.</span><button className="primary-button" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></footer></form>}
  </AdminShell>;
}
