import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, describe, expect, test, vi } from "vitest";
vi.mock("../services/api", () => ({ default: { get: vi.fn(), post: vi.fn(), put: vi.fn(), delete: vi.fn() } }));
import api from "../services/api";
import AdminUserDetail from "./AdminUserDetail"; import AdminProblemAnalytics from "./AdminProblemAnalytics";
import AdminCollections from "./AdminCollections"; import AdminLearningPaths from "./AdminLearningPaths"; import AdminDailyChallenges from "./AdminDailyChallenges";
import Pagination from "../components/Pagination";
const route=(path,Component)=><MemoryRouter initialEntries={[path]}><Routes><Route path={path.replace(/\d+/,":id")} element={<Component/>}/></Routes></MemoryRouter>;
beforeEach(()=>{vi.clearAllMocks();window.confirm=vi.fn(()=>true);});
describe("Prompt 3 admin analytics",()=>{
 test("user detail renders safe metrics and source-free recent activity",async()=>{api.get.mockResolvedValue({data:{username:"ada",role:"USER",solvedTotal:3,easySolved:1,mediumSolved:1,hardSolved:1,totalSubmissions:5,acceptedSubmissions:3,acceptanceRate:60,activeDays:2,currentStreak:1,longestStreak:2,languageUsage:{java:4},recentSubmissions:[{id:1,problemTitle:"Two Sum",status:"ACCEPTED",language:"java",submittedAt:"2026-01-01T00:00:00"}]}});render(route("/admin/users/1",AdminUserDetail));expect(screen.getByText("Loading user analytics...")).toBeInTheDocument();expect(await screen.findByText("ada")).toBeInTheDocument();expect(screen.getByText("Two Sum")).toBeInTheDocument();expect(screen.queryByText(/password/i)).not.toBeInTheDocument();});
 test("user detail reports API failure",async()=>{api.get.mockRejectedValue(new Error("no"));render(route("/admin/users/1",AdminUserDetail));expect(await screen.findByText("Unable to load user analytics.")).toBeInTheDocument();});
 test("problem analytics shows readiness but not hidden values",async()=>{api.get.mockResolvedValue({data:{title:"Reverse",executionMode:"FUNCTION",published:true,totalSubmissions:4,acceptedSubmissions:2,acceptanceRate:50,uniqueAttemptedUsers:3,uniqueSolvedUsers:2,publicTestCaseCount:2,hiddenTestCaseCount:4,verdictDistribution:{ACCEPTED:2},languageDistribution:{python:4}}});render(route("/admin/problems/1/analytics",AdminProblemAnalytics));expect(screen.getByText("Loading problem analytics...")).toBeInTheDocument();expect(await screen.findByText("Reverse")).toBeInTheDocument();expect(screen.getByText("4 / 4")).toBeInTheDocument();expect(screen.queryByText("secret hidden input")).not.toBeInTheDocument();});
});
describe("Prompt 3 management pages",()=>{
 test("collections supports an empty state and create",async()=>{api.get.mockResolvedValue({data:[]});api.post.mockResolvedValue({data:{}});render(<MemoryRouter><AdminCollections/></MemoryRouter>);expect(await screen.findByText("No collections yet.")).toBeInTheDocument();fireEvent.change(screen.getByPlaceholderText("Collection title"),{target:{value:"Top 50"}});fireEvent.click(screen.getByText("Create"));await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/collections",expect.objectContaining({title:"Top 50"})));});
 test("learning paths renders paths and sections",async()=>{api.get.mockResolvedValue({data:[{id:1,title:"Basics",description:"x",published:false,sections:[{id:2,title:"Arrays",items:[]}]}]});render(<MemoryRouter><AdminLearningPaths/></MemoryRouter>);expect(await screen.findByDisplayValue("Basics")).toBeInTheDocument();expect(screen.getByText(/Arrays/)).toBeInTheDocument();});
 test("daily challenge displays participation and schedules",async()=>{api.get.mockResolvedValue({data:[{id:1,challengeDate:"2030-01-01",problem:{title:"Two Sum"},participants:10,successfulCompletions:7,completionRate:70}]});api.post.mockResolvedValue({data:{}});render(<MemoryRouter><AdminDailyChallenges/></MemoryRouter>);expect(await screen.findByText(/Participants: 10/)).toBeInTheDocument();fireEvent.change(screen.getByPlaceholderText("Published problem ID"),{target:{value:"4"}});fireEvent.change(screen.getByDisplayValue(""),{target:{value:"2030-02-01"}});fireEvent.click(screen.getByText("Schedule"));await waitFor(()=>expect(api.post).toHaveBeenCalled());});
});
test("pagination disables bounds and invokes page changes",()=>{const change=vi.fn();const{rerender}=render(<Pagination data={{page:0,totalPages:3,first:true,last:false}} onChange={change}/>);expect(screen.getByText("Previous")).toBeDisabled();fireEvent.click(screen.getByText("Next"));expect(change).toHaveBeenCalledWith(1);rerender(<Pagination data={{page:2,totalPages:3,first:false,last:true}} onChange={change}/>);expect(screen.getByText("Next")).toBeDisabled();fireEvent.click(screen.getByText("Previous"));expect(change).toHaveBeenCalledWith(1);});
