import { useState } from "react";
import { ArrowRight, Lock, Mail, User } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import api from "../services/api";
import BrandLogo from "../components/BrandLogo";

export default function Register() {
  const navigate = useNavigate(); const [form, setForm] = useState({ username:"", email:"", password:"", confirmPassword:"" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (form.password !== form.confirmPassword) { setError("Passwords do not match."); return; } setLoading(true); setError(""); try { await api.post("/auth/register", { username:form.username.trim(), email:form.email.trim(), password:form.password }); navigate("/verify-email", { replace:true, state:{ email:form.email.trim() } }); } catch (reason) { setError(reason.response?.data?.message || "Unable to reach the Verdixa server. Start the backend and try again."); } finally { setLoading(false); } };
  const fields = [["username","Username",User,"text","username"],["email","Email",Mail,"email","email"],["password","Password",Lock,"password","new-password"],["confirmPassword","Confirm password",Lock,"password","new-password"]];
  return <main className="vx-auth"><section className="vx-auth-manifest"><div className="vx-auth-brand"><BrandLogo/><span>VERDIXA / 01</span></div><div><p className="vx-eyebrow">Create your workspace</p><h1>Build logic.<br/>Earn clarity.</h1><p>Practice against a real multi-language judge.</p></div><small>Persisted progress<br/>No artificial metrics</small></section><section className="vx-auth-form"><div><span className="vx-section-meta">New developer account</span><h2>Begin with Verdixa</h2><p>Your identity is private by default and measured by real work.</p>{error && <div className="error-message" role="alert">{error}</div>}<form onSubmit={submit}>{fields.map(([name,label,Icon,type,complete]) => <label key={name}>{label}<div className="input-wrapper"><Icon size={17}/><input name={name} type={type} autoComplete={complete} value={form[name]} onChange={(event) => setForm({...form,[name]:event.target.value})} required minLength={name.toLowerCase().includes("password") ? 6 : undefined}/></div></label>)}<button className="login-button" disabled={loading}>{loading ? "Creating account…" : "Create workspace"}<ArrowRight size={17}/></button></form><p className="register-link">Already registered? <Link to="/login">Sign in</Link></p></div></section></main>;
}
