import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Save, Trash2 } from "lucide-react";
import api from "../services/api";

const blank = { inputData:"", functionArguments:[], expectedOutput:"", hidden:false };
export default function TestCaseManagement(){
 const {id}=useParams(), navigate=useNavigate(); const [problem,setProblem]=useState(null),[cases,setCases]=useState([]),[draft,setDraft]=useState(blank),[editingId,setEditingId]=useState(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const functional=problem?.executionMode==="FUNCTION", hiddenCount=cases.filter((item)=>item.hidden).length;
 const load=useCallback(async()=>{try{const [p,c]=await Promise.all([api.get(`/problems/${id}`),api.get(`/problems/${id}/testcases/all`)]);setProblem(p.data);setCases(c.data||[]);setDraft((value)=>({...value,functionArguments:p.data.executionMode==="FUNCTION"?(p.data.functionSignature?.parameters||[]).map((_,i)=>value.functionArguments[i]??""):[]}));}catch(e){setError(e.response?.data?.message||"Unable to load test cases.");}},[id]);
 useEffect(()=>{if(localStorage.getItem("algosphere_role")!=="ADMIN")navigate("/dashboard");else load();},[load,navigate]);
 const payload=()=>functional?{inputData:"",expectedOutput:draft.expectedOutput,functionArguments:`[${draft.functionArguments.join(",")}]`,hidden:draft.hidden}:{inputData:draft.inputData,expectedOutput:draft.expectedOutput,hidden:draft.hidden};
 const save=async(e)=>{e.preventDefault();setSaving(true);setError("");try{if(editingId)await api.put(`/problems/${id}/testcases/${editingId}`,payload());else await api.post(`/problems/${id}/testcases`,payload());setEditingId(null);setDraft({...blank,functionArguments:(problem.functionSignature?.parameters||[]).map(()=>"")});await load();}catch(err){setError(err.response?.data?.message||"Unable to save test case.");}finally{setSaving(false);}};
 const edit=(item)=>{let args=[];try{args=JSON.parse(item.functionArguments||"[]").map((value)=>JSON.stringify(value));}catch{/* backend remains authoritative */}setEditingId(item.id);setDraft({inputData:item.inputData||"",functionArguments:args,expectedOutput:item.expectedOutput,hidden:item.hidden});};
 const remove=async(item)=>{if(!confirm("Delete this test case?"))return;try{await api.delete(`/problems/${id}/testcases/${item.id}`);await load();}catch(err){setError(err.response?.data?.message||"Unable to delete test case.");}};
 return <div className="dashboard-layout"><main className="dashboard-main"><header className="dashboard-header"><div><button className="back-button" onClick={()=>navigate("/admin/problems")}><ArrowLeft size={18}/> Back</button><h1>Test Case Management</h1><p>{problem?.title}</p></div></header>{error&&<div className="error-message">{error}</div>}
 {functional&&<section className="hidden-coverage"><h2>Hidden Test Coverage: {hiddenCount} / 4</h2><strong>{hiddenCount===4?"READY TO PUBLISH":"NOT READY TO PUBLISH"}</strong></section>}
 <section className="dashboard-section"><form className="problem-form" onSubmit={save}><div className="form-section"><h2>{editingId?"Edit":"Add"} {draft.hidden?`Hidden Test ${Math.min(hiddenCount+(editingId?0:1),4)}`:"Public Test"}</h2>
 {functional?(problem.functionSignature?.parameters||[]).map((parameter,index)=><div className="form-group" key={parameter.name}><label>{parameter.name} <small>{parameter.type}</small></label><textarea required value={draft.functionArguments[index]||""} placeholder={parameter.type==="String"?'"hello"':parameter.type.endsWith("[]")?"[]":"0"} onChange={(e)=>setDraft({...draft,functionArguments:draft.functionArguments.map((value,i)=>i===index?e.target.value:value)})}/></div>):<div className="form-group"><label>Input</label><textarea required value={draft.inputData} onChange={(e)=>setDraft({...draft,inputData:e.target.value})}/></div>}
 <div className="form-group"><label>Expected {functional?"return":"output"}</label><textarea required value={draft.expectedOutput} onChange={(e)=>setDraft({...draft,expectedOutput:e.target.value})}/></div>
 <label className="checkbox-label"><input type="checkbox" disabled={!editingId&&hiddenCount>=4&&!draft.hidden} checked={draft.hidden} onChange={(e)=>setDraft({...draft,hidden:e.target.checked})}/><span>Hidden official test</span></label><div className="form-actions"><button className="primary-button" disabled={saving||(!editingId&&draft.hidden&&hiddenCount>=4)}><Save size={18}/>Save</button></div></div></form></section>
 <section className="dashboard-section"><div className="problem-table">{cases.map((item,index)=><div className="table-row" key={item.id}><span>{item.hidden?`Hidden Test ${cases.filter((x,i)=>x.hidden&&i<=index).length}`:`Public Test ${cases.filter((x,i)=>!x.hidden&&i<=index).length}`}</span><pre>{item.hidden?"Values protected":(item.functionArguments||item.inputData)}</pre><pre>{item.hidden?"Protected":item.expectedOutput}</pre><div><button onClick={()=>edit(item)}>Edit</button><button onClick={()=>remove(item)}><Trash2 size={16}/></button></div></div>)}</div></section>
 </main></div>;
}
