spring.application.name=LeetCodePlatform

spring.datasource.url=${ALGOSPHERE_DB_URL:jdbc:mysql://localhost:3306/leetcode_platform}
spring.datasource.username=${ALGOSPHERE_DB_USERNAME:root}
spring.datasource.password=${ALGOSPHERE_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

algosphere.execution.javac=${ALGOSPHERE_JAVAC_COMMAND:javac}
algosphere.execution.java=${ALGOSPHERE_JAVA_COMMAND:java}
algosphere.execution.gxx=${ALGOSPHERE_CPP_COMMAND:C:\\msys64\\ucrt64\\bin\\g++.exe}
algosphere.execution.python=${ALGOSPHERE_PYTHON_COMMAND:python}
algosphere.execution.runtime-path=${ALGOSPHERE_RUNTIME_PATH:C:\\msys64\\ucrt64\\bin;C:\\msys64\\usr\\bin}
algosphere.jwt.secret=${ALGOSPHERE_JWT_SECRET:}
algosphere.bootstrap-admin.username=${ALGOSPHERE_BOOTSTRAP_ADMIN_USERNAME:}
algosphere.bootstrap-admin.password=${ALGOSPHERE_BOOTSTRAP_ADMIN_PASSWORD:}
