package com.leetcode.backend.service;

import com.leetcode.backend.dto.*;
import com.leetcode.backend.model.*;
import com.leetcode.backend.repository.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.time.*;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.*;
import java.util.stream.*;

/** The single backend authority for assessment ownership, access, and lifecycle rules. */
@Service public class AssessmentService {
 private static final Logger log=LoggerFactory.getLogger(AssessmentService.class);
 private static final SecureRandom INVITE_RANDOM=new SecureRandom(); private final org.springframework.security.crypto.password.PasswordEncoder invitationEncoder=new org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder(); @org.springframework.beans.factory.annotation.Value("${verdixa.frontend-base-url:http://localhost:5173}") private String frontendBaseUrl="http://localhost:5173"; private final AssessmentRepository assessments; private final AssessmentProblemRepository links; private final AssessmentInvitationRepository invitations; private final AssessmentRegistrationRepository registrations; private final AssessmentAccessRepository accesses; private final AssessmentSessionRepository sessions; private final AssessmentProctorEventRepository events; private final UserRepository users; private final ProblemRepository problems; private final SubmissionRepository submissions; private final AssessmentCreatorService creators; private final SubmissionService judge; private final NotificationDeliveryService notifications; private final ApplicationEventPublisher publisher;
 @org.springframework.beans.factory.annotation.Autowired public AssessmentService(AssessmentRepository a,AssessmentProblemRepository l,AssessmentInvitationRepository i,AssessmentRegistrationRepository r,AssessmentAccessRepository aa,AssessmentSessionRepository s,AssessmentProctorEventRepository e,UserRepository u,ProblemRepository p,SubmissionRepository sub,AssessmentCreatorService c,SubmissionService j,NotificationDeliveryService n,ApplicationEventPublisher publisher){assessments=a;links=l;invitations=i;registrations=r;accesses=aa;sessions=s;events=e;users=u;problems=p;submissions=sub;creators=c;judge=j;notifications=n;this.publisher=publisher;}
 /** Compatibility constructor retained for existing focused unit tests. */
 public AssessmentService(AssessmentRepository a,AssessmentProblemRepository l,AssessmentInvitationRepository i,AssessmentRegistrationRepository r,AssessmentSessionRepository s,AssessmentProctorEventRepository e,UserRepository u,ProblemRepository p,SubmissionRepository sub,AssessmentCreatorService c,SubmissionService j,NotificationDeliveryService n){this(a,l,i,r,null,s,e,u,p,sub,c,j,n,null);}
 @Transactional public Map<String,Object> create(String name,AssessmentRequest req){User creator=user(name);creators.requireApproved(creator);validate(req);Assessment a=new Assessment();a.setCreator(creator);copy(a,req);a.setInviteToken(UUID.randomUUID().toString().replace("-", ""));a.setMcqQuestions(serializeMcqs(req.mcqs()));assessments.save(a);saveProblems(a,req);return view(a,creator);}
 @Transactional public Map<String,Object> update(String name,Long id,AssessmentRequest req){Assessment a=owned(name,id);creators.requireApproved(a.getCreator());AssessmentEnums.Status state=a.derivedStatus();if(Set.of(AssessmentEnums.Status.LIVE,AssessmentEnums.Status.COMPLETED,AssessmentEnums.Status.CANCELLED).contains(state))throw new IllegalArgumentException("A live, completed, or cancelled assessment cannot be structurally edited.");if(a.getStatus()!=AssessmentEnums.Status.DRAFT){if(!sameProblemSet(a,req)||a.isFullscreenRequired()!=req.fullscreenRequired()||a.isMicrophoneRequired()!=req.microphoneRequired()||a.isStrictProctoring()!=req.strictProctoring()||!Objects.equals(a.getMaxParticipants(),req.maxParticipants()))throw new IllegalArgumentException("Problems, scoring, capacity, and proctoring rules are locked after publishing.");if((!Objects.equals(a.getStartAt(),req.startAt())||!Objects.equals(a.getEndAt(),req.endAt()))&&a.getStartAt().isBefore(LocalDateTime.now().plusMinutes(10)))throw new IllegalArgumentException("The schedule is locked within 10 minutes of the assessment start.");if(a.getVisibility()!=req.visibility()&&(registrations.countByAssessmentId(id)>0||(accesses!=null&&accesses.countByAssessmentIdAndVerifiedAtIsNotNull(id)>0)))throw new IllegalArgumentException("Visibility cannot change after verified participant access exists.");if(a.getVisibility()!=req.visibility()&&req.visibility()==AssessmentEnums.Visibility.PRIVATE&&(req.inviteeIds()==null||req.inviteeIds().isEmpty()))throw new IllegalArgumentException("Select private invitees before switching visibility.");}validate(req);boolean changed=criticalChanged(a,req);copy(a,req);links.deleteByAssessmentId(id);saveProblems(a,req);if(req.visibility()==AssessmentEnums.Visibility.PRIVATE&&req.inviteeIds()!=null){Map<String,Object> invites=addInvitees(a,req.inviteeIds());if(((Number)invites.get("invited")).intValue()>0&&a.getStatus()!=AssessmentEnums.Status.DRAFT)dispatchPendingInvitations(a);}if(a.getStatus()!=AssessmentEnums.Status.DRAFT&&changed)event(new EmailNotificationEvents.AssessmentUpdated(a.getId()));return view(a,user(name));}
 @Transactional public Map<String,Object> publish(String name,Long id){Assessment a=owned(name,id);creators.requireApproved(a.getCreator());if(a.getStatus()!=AssessmentEnums.Status.DRAFT)throw new IllegalArgumentException("Only a draft can be published.");if(a.getVisibility()==AssessmentEnums.Visibility.PRIVATE&&invitations.countByAssessmentIdAndStatus(id,AssessmentEnums.InvitationStatus.INVITED)<1)throw new IllegalArgumentException("A private assessment needs at least one invited participant before publishing.");a.setStatus(AssessmentEnums.Status.PUBLISHED);if(a.getVisibility()==AssessmentEnums.Visibility.PRIVATE)dispatchPendingInvitations(a);event(new EmailNotificationEvents.AssessmentPublished(a.getId()));return view(a,user(name));}
 @Transactional public void cancel(String name,Long id){Assessment a=owned(name,id);if(a.getStatus()==AssessmentEnums.Status.DRAFT){if(registrations.countByAssessmentId(id)>0||!sessions.findByAssessmentId(id).isEmpty())throw new IllegalArgumentException("A draft with participant activity cannot be deleted.");links.deleteByAssessmentId(id);invitations.deleteByAssessmentId(id);assessments.delete(a);return;}if(a.derivedStatus()==AssessmentEnums.Status.COMPLETED)throw new IllegalArgumentException("Completed assessments retain their results.");if(a.getStatus()==AssessmentEnums.Status.CANCELLED)return;a.setStatus(AssessmentEnums.Status.CANCELLED);event(new EmailNotificationEvents.AssessmentCancelled(a.getId()));}
 @Transactional(readOnly=true) public List<Map<String,Object>> discover(String name){User u=user(name);return assessments.findAll().stream().filter(a->a.getArchivedAt()==null).filter(a->a.getStatus()!=AssessmentEnums.Status.DRAFT||a.getCreator().getId().equals(u.getId())).map(a->view(a,u)).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> mine(String name){User u=user(name);return assessments.findByCreatorIdOrderByCreatedAtDesc(u.getId()).stream().filter(a->a.getArchivedAt()==null).map(a->view(a,u)).toList();}
 @Transactional public void removeFromHistory(String name,Long id){Assessment assessment=owned(name,id);if(!Set.of(AssessmentEnums.Status.COMPLETED,AssessmentEnums.Status.CANCELLED).contains(assessment.derivedStatus()))throw new IllegalArgumentException("Only completed or cancelled assessments can be removed from history.");assessment.setArchivedAt(LocalDateTime.now());}
 @Transactional(readOnly=true) public Map<String,Object> get(String name,Long id){User u=user(name);return view(find(id),u);}
 @Transactional public Map<String,Object> invite(String name,Long id,List<Long> userIds){return invite(name,id,userIds,List.of());}
 @Transactional public Map<String,Object> invite(String name,Long id,List<Long> userIds,List<String> emails){Assessment a=owned(name,id);creators.requireApproved(a.getCreator());if(a.getVisibility()!=AssessmentEnums.Visibility.PRIVATE)throw new IllegalArgumentException("Invitees are only used for private assessments.");if(a.derivedStatus()==AssessmentEnums.Status.LIVE||a.derivedStatus()==AssessmentEnums.Status.COMPLETED||a.getStatus()==AssessmentEnums.Status.CANCELLED)throw new IllegalArgumentException("Invitees cannot be changed after this assessment has started or been cancelled.");Map<String,Object> result=addInvitees(a,userIds,emails);if(((Number)result.get("invited")).intValue()>0&&a.getStatus()!=AssessmentEnums.Status.DRAFT)dispatchPendingInvitations(a);return result;}
 @Transactional public void removeInvitee(String name,Long id,Long userId){Assessment a=owned(name,id);if(a.getVisibility()!=AssessmentEnums.Visibility.PRIVATE)throw new IllegalArgumentException("Only private assessments have invitees.");if(a.derivedStatus()==AssessmentEnums.Status.LIVE||a.derivedStatus()==AssessmentEnums.Status.COMPLETED||a.getStatus()==AssessmentEnums.Status.CANCELLED)throw new IllegalArgumentException("Invitees cannot be removed after the assessment starts.");if(sessions.findByAssessmentIdAndParticipantId(id,userId).isPresent())throw new IllegalArgumentException("A started participant cannot be removed; cancel the assessment instead.");invitations.findByAssessmentIdAndUserId(id,userId).ifPresent(inv->inv.setStatus(AssessmentEnums.InvitationStatus.CANCELLED));}
 @Transactional public Map<String,Object> start(String name,Long id){throw new AccessDeniedException("Verify assessment access by email before starting.");}
 @Transactional public Map<String,Object> startAuthorized(User participant,Long id){
  Assessment a=find(id);if(a.getStatus()==AssessmentEnums.Status.CANCELLED)throw new IllegalArgumentException("This assessment has been cancelled.");
  LocalDateTime now=LocalDateTime.now();if(now.isBefore(a.getStartAt())||!now.isBefore(a.getEndAt()))throw new IllegalArgumentException("The assessment is outside its active time window.");
  AssessmentSession session=sessions.lockByAssessmentIdAndParticipantId(id,participant.getId()).orElseGet(()->{AssessmentSession s=new AssessmentSession();s.setAssessment(a);s.setParticipant(participant);s.setStartedAt(now);s.setLastHeartbeatAt(now);return sessions.save(s);});
  if(session.getStatus()!=AssessmentEnums.SessionStatus.ACTIVE)throw new IllegalArgumentException("This assessment session is no longer active.");
  // A successful start (including safe re-entry to an existing ACTIVE attempt) owns a fresh
  // heartbeat lease. Without this assignment the scheduler can expire a reused session in
  // the milliseconds between the start response and the client's first heartbeat.
  session.setLastHeartbeatAt(now);
  event(session,AssessmentEnums.ProctorEventType.SESSION_STARTED,null);
  lifecycle(session,AssessmentEnums.SessionStatus.ACTIVE,AssessmentEnums.SessionStatus.ACTIVE,AssessmentEnums.ProctorEventType.SESSION_STARTED,null,now);
  return sessionView(session);
 }
 @Transactional public Map<String,Object> heartbeat(String name,Long sessionId){
  AssessmentSession s=ownedSession(name,sessionId);if(s.getStatus()!=AssessmentEnums.SessionStatus.ACTIVE)return sessionView(s);
  if(s.getAssessment().getStatus()==AssessmentEnums.Status.CANCELLED)throw new IllegalArgumentException("This assessment has been cancelled.");
  LocalDateTime now=LocalDateTime.now();if(!now.isBefore(s.getAssessment().getEndAt())){expire(s,"TIME_EXPIRED");return sessionView(s);}s.setLastHeartbeatAt(now);log.debug("[AssessmentSession] assessmentId={} sessionId={} participantId={} heartbeatAt={}",s.getAssessment().getId(),s.getId(),s.getParticipant().getId(),s.getLastHeartbeatAt());return sessionView(s);
 }
 @Transactional public Map<String,Object> armProctoring(String name,Long sessionId){
  AssessmentSession s=activeOwned(name,sessionId);if(s.getProctoringArmedAt()==null)s.setProctoringArmedAt(LocalDateTime.now());lifecycle(s,s.getStatus(),s.getStatus(),null,null,LocalDateTime.now());return sessionView(s);
 }
 @Transactional public Map<String,Object> proctor(String name,Long sessionId,String type,String metadata){
  AssessmentSession s=ownedSession(name,sessionId);AssessmentEnums.ProctorEventType eventType;try{eventType=AssessmentEnums.ProctorEventType.valueOf(type);}catch(RuntimeException exception){throw new IllegalArgumentException("Unsupported proctoring event.");}
  if(s.getStatus()!=AssessmentEnums.SessionStatus.ACTIVE)return sessionView(s);
  if(isTerminatingEvent(s,eventType)){
   if(s.getProctoringArmedAt()==null){log.debug("Ignoring unarmed assessment proctor event assessmentId={} sessionId={} participantId={} proctorEventType={} timestamp={}",s.getAssessment().getId(),s.getId(),s.getParticipant().getId(),eventType,LocalDateTime.now());return sessionView(s);}
   terminate(s,eventType.name(),eventType);
  }else event(s,eventType,metadata);
  return sessionView(s);
 }
 @Transactional public Map<String,Object> finish(String name,Long sessionId){AssessmentSession s=activeOwned(name,sessionId);AssessmentEnums.SessionStatus old=s.getStatus();s.setStatus(AssessmentEnums.SessionStatus.SUBMITTED);s.setSubmittedAt(LocalDateTime.now());event(s,AssessmentEnums.ProctorEventType.SESSION_SUBMITTED,null);lifecycle(s,old,s.getStatus(),AssessmentEnums.ProctorEventType.SESSION_SUBMITTED,null,LocalDateTime.now());return sessionView(s);}
 @Transactional public SubmissionResponse submit(String name,Long sessionId,Long problemId,String language,String code){AssessmentSession s=activeOwned(name,sessionId);if(s.getAssessment().getStatus()==AssessmentEnums.Status.CANCELLED)throw new IllegalArgumentException("This assessment has been cancelled.");if(LocalDateTime.now().isAfter(s.getAssessment().getEndAt())){terminate(s,"TIME_EXPIRED",AssessmentEnums.ProctorEventType.HEARTBEAT_TIMEOUT);throw new IllegalArgumentException("Assessment time has expired.");}if(!links.existsByAssessmentIdAndProblemId(s.getAssessment().getId(),problemId))throw new AccessDeniedException("Problem is not part of this assessment.");Submission sub=judge.createSubmission(s.getParticipant().getId(),problemId,language,code,null);sub.setAssessmentSession(s);submissions.save(sub);recalculate(s);addMcqScore(s);return new SubmissionResponse(judge.getSubmissionById(sub.getId()));}
 @Transactional(readOnly=true) public void authorizeRun(String name,Long sessionId,Long problemId){AssessmentSession s=activeOwned(name,sessionId);if(problemId==null||!links.existsByAssessmentIdAndProblemId(s.getAssessment().getId(),problemId))throw new AccessDeniedException("Problem is not part of this assessment.");if(!LocalDateTime.now().isBefore(s.getAssessment().getEndAt()))throw new IllegalArgumentException("Assessment time has expired.");}
 @Transactional(readOnly=true) public Map<String,Object> analytics(String name,Long id,boolean admin){Assessment a=find(id);if(!admin&&!a.getCreator().getUsername().equals(name))throw new AccessDeniedException("Only the assessment owner can view analytics.");List<AssessmentSession> ss=sessions.findByAssessmentId(id);long completed=ss.stream().filter(x->x.getStatus()==AssessmentEnums.SessionStatus.SUBMITTED).count(),terminated=ss.stream().filter(x->x.getStatus()==AssessmentEnums.SessionStatus.TERMINATED).count(),verified=accesses==null?0:accesses.countByAssessmentIdAndVerifiedAtIsNotNull(id);double avg=ss.stream().mapToInt(AssessmentSession::getScore).average().orElse(0);Map<String,Object> r=new LinkedHashMap<>();r.put("invited",invitations.countByAssessmentIdAndStatus(id,AssessmentEnums.InvitationStatus.INVITED)+invitations.countByAssessmentIdAndStatus(id,AssessmentEnums.InvitationStatus.REGISTERED));r.put("verified",verified);r.put("registered",verified);r.put("started",ss.size());r.put("completed",completed);r.put("terminated",terminated);r.put("active",ss.stream().filter(x->x.getStatus()==AssessmentEnums.SessionStatus.ACTIVE).count());r.put("absent",Math.max(0,verified-ss.size()));r.put("averageScore",Math.round(avg));r.put("highestScore",ss.stream().mapToInt(AssessmentSession::getScore).max().orElse(0));r.put("lowestScore",ss.stream().mapToInt(AssessmentSession::getScore).min().orElse(0));r.put("proctorEvents",events.countBySessionAssessmentId(id));r.put("leaderboard",ss.stream().sorted(Comparator.comparingInt(AssessmentSession::getScore).reversed().thenComparing(AssessmentSession::getStartedAt)).map(this::sessionView).toList());return r;}
 @Transactional(readOnly=true) public List<Map<String,Object>> searchInvitees(String name,String query){User creator=user(name);creators.requireApproved(creator);if(query==null||query.trim().length()<2)throw new IllegalArgumentException("Enter at least two characters.");return users.findTop20ByUsernameContainingIgnoreCase(query.trim()).stream().filter(u->u.getRole()==Role.USER&&!u.getId().equals(creator.getId())).map(u->Map.<String,Object>of("id",u.getId(),"username",u.getUsername())).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> participants(String name,Long id){
  Assessment a=owned(name,id);
  Map<Long,AssessmentInvitation> inviteMap=invitations.findByAssessmentId(id).stream().collect(Collectors.toMap(x->x.getUser().getId(),x->x,(left,right)->left,LinkedHashMap::new));
  List<AssessmentAccess> allAccesses=accesses==null?List.of():accesses.findByAssessmentId(id);
  Map<Long,AssessmentAccess> accessMap=allAccesses.stream().filter(x->x.getParticipant()!=null).collect(Collectors.toMap(x->x.getParticipant().getId(),x->x,(left,right)->left,LinkedHashMap::new));
  Map<Long,AssessmentAccess> requestedByInvitee=allAccesses.stream().filter(x->x.getInvitation()!=null).collect(Collectors.toMap(x->x.getInvitation().getUser().getId(),x->x,(left,right)->left,LinkedHashMap::new));
  List<AssessmentRegistration> allRegistrations=registrations.findByAssessmentId(id);
  Map<Long,AssessmentRegistration> registrationMap=allRegistrations.stream().collect(Collectors.toMap(x->x.getUser().getId(),x->x,(left,right)->left,LinkedHashMap::new));
  Set<Long> ids=new LinkedHashSet<>(inviteMap.keySet());ids.addAll(accessMap.keySet());ids.addAll(registrationMap.keySet());
  List<Map<String,Object>> rows=ids.stream().map(uid->{
   AssessmentInvitation inv=inviteMap.get(uid);AssessmentAccess access=accessMap.get(uid);if(access==null)access=requestedByInvitee.get(uid);AssessmentRegistration reg=registrationMap.get(uid);
   User participant=access!=null&&access.getParticipant()!=null?access.getParticipant():reg!=null?reg.getUser():inv.getUser();var session=sessions.findByAssessmentIdAndParticipantId(id,uid);
   String status=session.map(x->x.getStatus().name()).orElse(access!=null?(access.getVerifiedAt()!=null?"VERIFIED":"FORM_SUBMITTED"):reg!=null?"LEGACY_REGISTERED":inv.getStatus().name());
   Map<String,Object> row=new LinkedHashMap<>();row.put("id",uid);row.put("username",participant.getUsername());row.put("email",access!=null?access.getEmail():participant.getEmail());row.put("status",status);row.put("score",session.map(AssessmentSession::getScore).orElse(0));row.put("verifiedAt",access==null?null:access.getVerifiedAt());row.put("invitedAt",inv==null?null:inv.getInvitedAt());row.put("fullName",access==null?null:access.getFullName());row.put("participantReference",access==null?null:access.getParticipantReference());row.put("organization",access==null?null:access.getOrganization());row.put("formSubmittedAt",access==null?null:access.getCreatedAt());return row;
  }).collect(Collectors.toCollection(ArrayList::new));
  allAccesses.stream().filter(x->x.getParticipant()==null&&x.getInvitation()==null).forEach(access->{Map<String,Object> row=new LinkedHashMap<>();row.put("id","access-"+access.getId());row.put("username",access.getFullName());row.put("email",access.getEmail());row.put("status",access.getVerifiedAt()==null?"FORM_SUBMITTED":"VERIFIED");row.put("score",0);row.put("verifiedAt",access.getVerifiedAt());row.put("invitedAt",null);row.put("fullName",access.getFullName());row.put("participantReference",access.getParticipantReference());row.put("organization",access.getOrganization());row.put("formSubmittedAt",access.getCreatedAt());rows.add(row);});
  return rows;
 }
 @Transactional public void expireHeartbeats(int seconds){for(AssessmentSession s:sessions.lockArmedTimedOutSessions(AssessmentEnums.SessionStatus.ACTIVE,LocalDateTime.now().minusSeconds(seconds)))terminate(s,"HEARTBEAT_TIMEOUT",AssessmentEnums.ProctorEventType.HEARTBEAT_TIMEOUT);}
 private void recalculate(AssessmentSession s){Set<Long> accepted=submissions.findAll().stream().filter(x->x.getAssessmentSession()!=null&&x.getAssessmentSession().getId().equals(s.getId())&&"ACCEPTED".equals(x.getStatus())).map(x->x.getProblem().getId()).collect(Collectors.toSet());int score=links.findByAssessmentIdOrderByDisplayOrderAsc(s.getAssessment().getId()).stream().filter(x->accepted.contains(x.getProblem().getId())).mapToInt(AssessmentProblem::getPoints).sum();s.setScore(score);}
 private boolean isTerminatingEvent(AssessmentSession s,AssessmentEnums.ProctorEventType type){return switch(type){case FULLSCREEN_EXIT->s.getAssessment().isFullscreenRequired();case MICROPHONE_DISABLED->s.getAssessment().isMicrophoneRequired();case TAB_SWITCH,CAMERA_DISABLED,SCREEN_SHARE_STOPPED,PAGE_EXIT->s.getAssessment().isStrictProctoring();default->false;};}
 private void terminate(AssessmentSession s,String reason,AssessmentEnums.ProctorEventType type){if(s.getStatus()!=AssessmentEnums.SessionStatus.ACTIVE)return;AssessmentEnums.SessionStatus old=s.getStatus();s.setStatus(AssessmentEnums.SessionStatus.TERMINATED);s.setTerminationReason(reason);s.setTerminatedAt(LocalDateTime.now());event(s,type,null);lifecycle(s,old,s.getStatus(),type,reason,LocalDateTime.now());}
 private void expire(AssessmentSession s,String reason){if(s.getStatus()!=AssessmentEnums.SessionStatus.ACTIVE)return;AssessmentEnums.SessionStatus old=s.getStatus();s.setStatus(AssessmentEnums.SessionStatus.EXPIRED);s.setTerminationReason(reason);s.setTerminatedAt(LocalDateTime.now());lifecycle(s,old,s.getStatus(),null,reason,LocalDateTime.now());}
 private void event(AssessmentSession s,AssessmentEnums.ProctorEventType t,String metadata){AssessmentProctorEvent e=new AssessmentProctorEvent();e.setSession(s);e.setType(t);e.setMetadata(metadata==null?null:metadata.substring(0,Math.min(500,metadata.length())));events.save(e);}
 private void lifecycle(AssessmentSession s,AssessmentEnums.SessionStatus oldStatus,AssessmentEnums.SessionStatus newStatus,AssessmentEnums.ProctorEventType type,String reason,LocalDateTime timestamp){log.info("[AssessmentSession] assessmentId={} sessionId={} participantId={} {} -> {} reason={} proctorEventType={} timestamp={} lastHeartbeatAt={}",s.getAssessment().getId(),s.getId(),s.getParticipant().getId(),oldStatus,newStatus,reason,type,timestamp,s.getLastHeartbeatAt());}
 private AssessmentSession ownedSession(String n,Long id){AssessmentSession s=sessions.findById(id).orElseThrow(()->new RuntimeException("Assessment session not found."));if(n==null||!s.getParticipant().getUsername().equals(n))throw new AccessDeniedException("This session does not belong to you.");return s;}
 private AssessmentSession activeOwned(String n,Long id){AssessmentSession s=ownedSession(n,id);if(s.getStatus()!=AssessmentEnums.SessionStatus.ACTIVE)throw new IllegalArgumentException("Assessment session is not active.");return s;} private Assessment owned(String n,Long id){Assessment a=find(id);if(!a.getCreator().getUsername().equals(n))throw new AccessDeniedException("You do not own this assessment.");return a;} private Assessment find(Long id){return assessments.findById(id).orElseThrow(()->new RuntimeException("Assessment not found."));} private boolean isInvited(Assessment a,User u){return a.getCreator().getId().equals(u.getId())||invitations.existsByAssessmentIdAndUserId(a.getId(),u.getId());} private User user(String n){return users.findByUsername(n).orElseThrow(()->new RuntimeException("Authenticated user not found."));}
 private Map<String,Object> addInvitees(Assessment assessment,List<Long> userIds){return addInvitees(assessment,userIds,List.of());}
 private Map<String,Object> addInvitees(Assessment assessment,List<Long> userIds,List<String> emails){Set<Long> ids=new LinkedHashSet<>(userIds==null?List.of():userIds);Set<String> addresses=(emails==null?List.<String>of():emails).stream().filter(Objects::nonNull).map(x->x.trim().toLowerCase(Locale.ROOT)).filter(x->!x.isBlank()).collect(Collectors.toCollection(LinkedHashSet::new));if(ids.size()+addresses.size()<1||ids.size()+addresses.size()>100)throw new IllegalArgumentException("Invite between 1 and 100 people at a time.");int invited=0,alreadyInvited=0;for(Long userId:ids){User target=users.findById(userId).orElseThrow(()->new IllegalArgumentException("A selected user no longer exists."));if(invitations.existsByAssessmentIdAndUserId(assessment.getId(),userId)){alreadyInvited++;continue;}saveInvitation(assessment,target);invited++;}for(String address:addresses){User target=users.findByEmailIgnoreCase(address).orElseGet(()->createGuestInvitee(address));if(invitations.existsByAssessmentIdAndUserId(assessment.getId(),target.getId())){alreadyInvited++;continue;}saveInvitation(assessment,target);invited++;}return Map.of("invited",invited,"alreadyInvited",alreadyInvited);}
 private void saveInvitation(Assessment assessment,User target){AssessmentInvitation invitation=new AssessmentInvitation();invitation.setAssessment(assessment);invitation.setUser(target);invitation.setInvitedByCreator(assessment.getCreator());invitations.save(invitation);}
 private User createGuestInvitee(String email){User user=new User();user.setEmail(email);user.setUsername("invite-"+UUID.randomUUID().toString().replace("-","").substring(0,18));user.setPassword(invitationEncoder.encode(UUID.randomUUID().toString()));user.setRole(Role.ASSESSMENT_GUEST);user.setEmailVerified(false);return users.save(user);}
 private void dispatchPendingInvitations(Assessment assessment){int count=links.findByAssessmentIdOrderByDisplayOrderAsc(assessment.getId()).size();for(AssessmentInvitation invitation:invitations.findByAssessmentId(assessment.getId())){if(invitation.getStatus()!=AssessmentEnums.InvitationStatus.INVITED||invitation.getEmailSentAt()!=null)continue;byte[] bytes=new byte[32];INVITE_RANDOM.nextBytes(bytes);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);invitation.setAccessTokenHash(invitationEncoder.encode(token));invitation.setAccessTokenExpiresAt(assessment.getEndAt());invitation.setEmailSentAt(LocalDateTime.now());event(new EmailNotificationEvents.AssessmentAccessInvitation(invitation.getUser().getEmail(),invitation.getUser().getUsername(),assessment.getTitle(),assessment.getCreator().getUsername(),assessment.getOrganization(),assessment.getStartAt(),assessment.getEndAt(),count,assessment.isFullscreenRequired(),assessment.isMicrophoneRequired(),frontendBaseUrl.replaceAll("/+$","")+"/assessment/"+assessment.getId()+"/access?invite="+token));}}
 private void validate(AssessmentRequest r){if(!r.endAt().isAfter(r.startAt()))throw new IllegalArgumentException("Assessment end time must follow start time.");if(r.problems().stream().map(AssessmentRequest.ProblemSelection::problemId).distinct().count()!=r.problems().size())throw new IllegalArgumentException("An assessment cannot contain duplicate problems.");} private boolean sameProblemSet(Assessment a,AssessmentRequest r){List<String> current=links.findByAssessmentIdOrderByDisplayOrderAsc(a.getId()).stream().map(p->p.getProblem().getId()+":"+p.getPoints()).toList();List<String> requested=r.problems().stream().map(p->p.problemId()+":"+(p.points()==null?100:p.points())).toList();return current.equals(requested);} private boolean criticalChanged(Assessment a,AssessmentRequest r){return !Objects.equals(a.getDescription(),strip(r.description()))||!Objects.equals(a.getInstructions(),strip(r.instructions()))||!Objects.equals(a.getStartAt(),r.startAt())||!Objects.equals(a.getEndAt(),r.endAt());} private void copy(Assessment a,AssessmentRequest r){a.setTitle(r.title().trim());a.setOrganization(r.organization().trim());a.setDescription(strip(r.description()));a.setInstructions(strip(r.instructions()));a.setVisibility(r.visibility());a.setStartAt(r.startAt());a.setEndAt(r.endAt());a.setRegistrationDeadline(null);a.setMaxParticipants(r.maxParticipants());a.setFullscreenRequired(r.fullscreenRequired());a.setMicrophoneRequired(r.microphoneRequired());a.setStrictProctoring(r.strictProctoring());} private String strip(String s){return s==null?null:s.replaceAll("<[^>]*>","");} private void saveProblems(Assessment a,AssessmentRequest r){int order=0;for(var selection:r.problems()){AssessmentProblem link=new AssessmentProblem();link.setAssessment(a);link.setProblem(problems.findById(selection.problemId()).orElseThrow(()->new RuntimeException("Problem not found.")));link.setDisplayOrder(++order);link.setPoints(selection.points()==null?100:selection.points());links.save(link);}}
 private Map<String,Object> view(Assessment a,User viewer){boolean owner=a.getCreator().getId().equals(viewer.getId()), invited=isInvited(a,viewer), restricted=a.getVisibility()==AssessmentEnums.Visibility.PRIVATE&&!owner&&!invited;long verified=accesses==null?0:accesses.countByAssessmentIdAndVerifiedAtIsNotNull(a.getId());Map<String,Object> r=new LinkedHashMap<>();r.put("id",a.getId());r.put("title",a.getTitle());r.put("organization",a.getOrganization());r.put("description",a.getDescription());r.put("visibility",a.getVisibility());r.put("status",a.derivedStatus());r.put("startAt",a.getStartAt());r.put("endAt",a.getEndAt());r.put("host",a.getCreator().getUsername());r.put("owner",owner);r.put("invited",invited);r.put("accessRestricted",restricted);r.put("registered",accesses!=null&&accesses.findByAssessmentIdAndVerifiedAtIsNotNull(a.getId()).stream().anyMatch(x->x.getParticipant()!=null&&x.getParticipant().getId().equals(viewer.getId())));if(restricted)return r;r.put("instructions",a.getInstructions());r.put("maxParticipants",a.getMaxParticipants());r.put("fullscreenRequired",a.isFullscreenRequired());r.put("microphoneRequired",a.isMicrophoneRequired());r.put("strictProctoring",a.isStrictProctoring());r.put("participantCount",verified);r.put("invitedCount",invitations.findByAssessmentId(a.getId()).size());r.put("problems",links.findByAssessmentIdOrderByDisplayOrderAsc(a.getId()).stream().map(x->Map.of("id",x.getProblem().getId(),"title",x.getProblem().getTitle(),"difficulty",x.getProblem().getDifficulty(),"points",x.getPoints(),"order",x.getDisplayOrder())).toList());return r;} private Map<String,Object> sessionView(AssessmentSession s){Map<String,Object> r=new LinkedHashMap<>();r.put("id",s.getId());r.put("assessmentId",s.getAssessment().getId());r.put("participant",s.getParticipant().getUsername());r.put("status",s.getStatus());r.put("score",s.getScore());r.put("startedAt",s.getStartedAt());r.put("submittedAt",s.getSubmittedAt());r.put("terminatedAt",s.getTerminatedAt());r.put("endsAt",s.getAssessment().getEndAt());r.put("serverNow",LocalDateTime.now());r.put("lastHeartbeatAt",s.getLastHeartbeatAt());r.put("proctoringArmed",s.getProctoringArmedAt()!=null);r.put("terminationReason",s.getTerminationReason()==null?"":s.getTerminationReason());return r;}
 private void event(Object event){if(publisher!=null)publisher.publishEvent(event);else if(event instanceof EmailNotificationEvents.AssessmentInvitationsChanged e)notifications.queueAssessmentInvitations(e.assessmentId());else if(event instanceof EmailNotificationEvents.AssessmentPublished e)notifications.queueAssessmentPublished(e.assessmentId());else if(event instanceof EmailNotificationEvents.AssessmentRegistered e)notifications.queueAssessmentRegistration(e.assessmentId(),e.userId());else if(event instanceof EmailNotificationEvents.AssessmentUpdated e)notifications.queueAssessmentUpdate(e.assessmentId());else if(event instanceof EmailNotificationEvents.AssessmentCancelled e)notifications.queueAssessmentCancellation(e.assessmentId());}
 @Transactional public Map<String,Object> submitMcq(String name,Long sessionId,int questionIndex,int selectedOption){AssessmentSession session=activeOwned(name,sessionId);List<Map<String,Object>> questions=mcqs(session.getAssessment());if(questionIndex<0||questionIndex>=questions.size()||selectedOption<0||selectedOption>=((List<?>)questions.get(questionIndex).get("options")).size())throw new IllegalArgumentException("Invalid multiple-choice answer.");Map<String,Integer> answers=mcqAnswers(session);answers.put(String.valueOf(questionIndex),selectedOption);session.setMcqAnswers(new com.fasterxml.jackson.databind.ObjectMapper().valueToTree(answers).toString());recalculate(session);int mcqScore=0;for(int index=0;index<questions.size();index++){Map<String,Object> question=questions.get(index);Object correct=question.get("correctOption"),points=question.get("points");if(correct instanceof Number answer&&Objects.equals(answers.get(String.valueOf(index)),answer.intValue()))mcqScore+=points instanceof Number value?value.intValue():100;}session.setScore(session.getScore()+mcqScore);return Map.of("saved",true,"score",session.getScore());}
 @SuppressWarnings("unchecked") private List<Map<String,Object>> mcqs(Assessment assessment){try{return new com.fasterxml.jackson.databind.ObjectMapper().readValue(assessment.getMcqQuestions()==null?"[]":assessment.getMcqQuestions(),new com.fasterxml.jackson.core.type.TypeReference<List<Map<String,Object>>>(){});}catch(Exception ignored){return List.of();}}
 @SuppressWarnings("unchecked") private Map<String,Integer> mcqAnswers(AssessmentSession session){try{return new com.fasterxml.jackson.databind.ObjectMapper().readValue(session.getMcqAnswers()==null?"{}":session.getMcqAnswers(),new com.fasterxml.jackson.core.type.TypeReference<Map<String,Integer>>(){});}catch(Exception ignored){return new LinkedHashMap<>();}}
 private void addMcqScore(AssessmentSession session){Map<String,Integer> answers=mcqAnswers(session);int extra=0;for(int index=0;index<mcqs(session.getAssessment()).size();index++){Map<String,Object> question=mcqs(session.getAssessment()).get(index);Object correct=question.get("correctOption"),points=question.get("points");if(correct instanceof Number answer&&Objects.equals(answers.get(String.valueOf(index)),answer.intValue()))extra+=points instanceof Number value?value.intValue():100;}session.setScore(session.getScore()+extra);}
 private String serializeMcqs(List<AssessmentRequest.McqSelection> questions){try{return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(questions==null?List.of():questions);}catch(Exception e){throw new IllegalArgumentException("Multiple-choice questions could not be saved.");}}
}
