package com.leetcode.backend.service;
import com.leetcode.backend.dto.*; import com.leetcode.backend.model.*; import com.leetcode.backend.repository.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.*;
@Service public class ContestService {
 private final ContestRepository contests; private final ContestProblemRepository contestProblems; private final ContestRegistrationRepository registrations; private final ProblemRepository problems; private final UserRepository users; private final SubmissionRepository submissions; private final PasswordEncoder encoder; private final ApplicationEventPublisher events;
 public ContestService(ContestRepository c,ContestProblemRepository cp,ContestRegistrationRepository r,ProblemRepository p,UserRepository u,SubmissionRepository s,PasswordEncoder e,ApplicationEventPublisher events){contests=c;contestProblems=cp;registrations=r;problems=p;users=u;submissions=s;encoder=e;this.events=events;}
 @Transactional(readOnly=true) public List<ContestResponse> adminList(){return contests.findAll().stream().sorted(Comparator.comparing(Contest::getStartAt).reversed()).map(c->ContestResponse.from(c,false,registrations.countByContestId(c.getId()))).toList();}
 @Transactional(readOnly=true) public List<AdminContestListResponse> adminContestList(){
  LocalDateTime now=LocalDateTime.now();
  return contests.findAdminRows().stream().map(row->new AdminContestListResponse(row.getId(),row.getTitle(),row.getStartTime(),row.getEndTime(),scheduleStatus(row.getStartTime(),row.getEndTime(),now),row.getProblemCount(),row.getRegistrationCount())).toList();
 }
 @Transactional(readOnly=true) public AdminContestDetailResponse adminContestDetail(Long id){
  requirePositive(id); Contest contest=adminContest(id); LocalDateTime now=LocalDateTime.now();
  List<ContestProblem> problemLinks=contestProblems.findWithProblemByContestIdOrderByDisplayOrderAsc(id);
  List<ContestRegistration> entries=registrations.findWithUserByContestIdOrderByRegisteredAtAsc(id);
  List<Long> userIds=entries.stream().map(entry->entry.getUser().getId()).toList();
  List<Long> contestProblemIds=problemLinks.stream().map(ContestProblem::getId).toList();
  Map<Long,Long> solvedByUser=(userIds.isEmpty()||contestProblemIds.isEmpty())?Map.of():submissions.countAcceptedContestProblemsByUser(id,userIds,contestProblemIds,contest.getStartAt(),contest.getEndAt()).stream().collect(Collectors.toMap(SubmissionRepository.ContestUserSolvedCount::getUserId,SubmissionRepository.ContestUserSolvedCount::getSolved));
  List<AdminContestDetailResponse.ContestProblem> detailProblems=problemLinks.stream().map(link->new AdminContestDetailResponse.ContestProblem(link.getProblem().getId(),link.getProblem().getTitle(),link.getProblem().getDifficulty(),tags(link.getProblem().getTags()),link.getDisplayOrder())).toList();
  long total=problemLinks.size();
  List<AdminContestDetailResponse.Registration> detailRegistrations=entries.stream().map(entry->new AdminContestDetailResponse.Registration(entry.getUser().getId(),entry.getUser().getUsername(),entry.getUser().getEmail(),entry.getRegisteredAt(),solvedByUser.getOrDefault(entry.getUser().getId(),0L),total)).toList();
  return new AdminContestDetailResponse(contest.getId(),contest.getTitle(),contest.getDescription(),contest.getStartAt(),contest.getEndAt(),scheduleStatus(contest.getStartAt(),contest.getEndAt(),now),total,entries.size(),detailProblems,detailRegistrations);
 }
 @Transactional public AdminContestDeleteResponse deleteAdminContest(Long id){
  requirePositive(id); Contest contest=adminContest(id);
  if(submissions.countContestHistoryByContestId(id)>0)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.CONFLICT,"This contest has submission history and cannot be deleted safely. Users, global problems, and submissions were not changed.");
  registrations.deleteAllByContestId(id);
  contestProblems.deleteAllByContestId(id);
  contests.delete(contest);
  return new AdminContestDeleteResponse(id,"Contest deleted. Contest registrations and contest-specific problem links were removed.");
 }
 @Transactional(readOnly=true) public AdminContestAnalyticsResponse adminAnalytics(Long id){
  contest(id);
  List<ContestRegistration> entries=registrations.findByContestId(id);
  Set<Long> registeredUserIds=entries.stream().map(entry->entry.getUser().getId()).collect(Collectors.toSet());
  Set<Long> contestProblemIds=contestProblems.findByContestIdOrderByDisplayOrderAsc(id).stream().map(cp->cp.getProblem().getId()).collect(Collectors.toSet());
  Map<Long,Set<Long>> solvedByUser=new HashMap<>();
  for(Submission submission:submissions.findByContestIdOrderBySubmittedAtAsc(id)){
   if("ACCEPTED".equals(submission.getStatus())&&submission.getUser()!=null&&registeredUserIds.contains(submission.getUser().getId())&&contestProblemIds.contains(submission.getProblem().getId()))
    solvedByUser.computeIfAbsent(submission.getUser().getId(),ignored->new HashSet<>()).add(submission.getProblem().getId());
  }
  List<AdminContestAnalyticsResponse.RegisteredContestUser> users=entries.stream().sorted(Comparator.comparing(ContestRegistration::getRegisteredAt)).map(entry->new AdminContestAnalyticsResponse.RegisteredContestUser(entry.getUser().getUsername(),solvedByUser.getOrDefault(entry.getUser().getId(),Set.of()).size(),entry.getRegisteredAt())).toList();
  long participantsWhoSolved=users.stream().filter(entry->entry.solvedProblemCount()>0).count();
  long solvedProblemCount=solvedByUser.values().stream().flatMap(Set::stream).distinct().count();
  return new AdminContestAnalyticsResponse(entries.size(),participantsWhoSolved,contestProblemIds.size(),solvedProblemCount,users);
 }
 @Transactional(readOnly=true) public List<ContestResponse> list(String username){User u=user(username);return contests.findAll().stream().filter(c->c.getStatus()!=ContestStatus.DRAFT&&c.getStatus()!=ContestStatus.CANCELLED).filter(c->c.getVisibility()==ContestVisibility.PUBLIC||registrations.findByContestIdAndUserId(c.getId(),u.getId()).isPresent()).sorted(Comparator.comparing(Contest::getStartAt).reversed()).map(c->ContestResponse.from(c,registrations.findByContestIdAndUserId(c.getId(),u.getId()).isPresent(),registrations.countByContestId(c.getId()))).toList();}
 @Transactional(readOnly=true) public ContestResponse get(Long id,String username){Contest c=contest(id);User u=user(username);return ContestResponse.from(c,registrations.findByContestIdAndUserId(id,u.getId()).isPresent(),registrations.countByContestId(id));}
 @Transactional public ContestResponse create(ContestRequest r,String username){validate(r);if(contests.existsBySlug(r.slug()))throw new IllegalArgumentException("A contest already uses this slug.");Contest c=new Contest();copy(c,r);c.setCreatedBy(user(username));return ContestResponse.from(contests.save(c),false,0);}
 @Transactional public ContestResponse update(Long id,ContestRequest r){Contest c=contest(id);if(c.derivedStatus()==ContestStatus.LIVE||c.derivedStatus()==ContestStatus.ENDED)throw new IllegalArgumentException("A live or ended contest cannot be changed.");validate(r);copy(c,r);return ContestResponse.from(contests.save(c),false,registrations.countByContestId(id));}
 @Transactional public void register(Long id,String accessCode,String username){Contest c=contests.findWithProblemSetLockById(id).orElseThrow(()->new RuntimeException("Contest not found."));if(c.derivedStatus()==ContestStatus.ENDED||c.getStatus()==ContestStatus.CANCELLED||c.getStatus()==ContestStatus.DRAFT)throw new IllegalArgumentException("Registration is closed.");User u=user(username);if(c.getVisibility()==ContestVisibility.PRIVATE&&(accessCode==null||!encoder.matches(accessCode,c.getAccessCodeHash())))throw new IllegalArgumentException("Invalid contest access code.");if(registrations.findByContestIdAndUserId(id,u.getId()).isPresent())return;ContestRegistration entry=new ContestRegistration();entry.setContest(c);entry.setUser(u);registrations.save(entry);events.publishEvent(new EmailNotificationEvents.ContestRegistered(u.getEmail(),u.getUsername(),c.getTitle(),c.getDescription(),c.getStartAt(),c.getEndAt(),contestProblems.findByContestIdOrderByDisplayOrderAsc(id).size(),c.getId()));}
 @Transactional public ContestProblemResponse addProblem(Long id,ContestProblemRequest r){Contest c=contests.findWithProblemSetLockById(id).orElseThrow(()->new RuntimeException("Contest not found."));if(c.derivedStatus()==ContestStatus.LIVE||c.derivedStatus()==ContestStatus.ENDED)throw new IllegalArgumentException("Contest problems cannot change after the contest starts.");if(contestProblems.findByContestIdAndProblemId(id,r.problemId()).isPresent())throw new IllegalArgumentException("Problem is already in this contest.");ContestProblem cp=new ContestProblem();cp.setContest(c);cp.setProblem(problems.findById(r.problemId()).orElseThrow(()->new RuntimeException("Problem not found.")));cp.setDisplayOrder(contestProblems.findByContestIdOrderByDisplayOrderAsc(id).size()+1);cp.setPoints(r.points()==null?100:r.points());return ContestProblemResponse.from(contestProblems.save(cp));}
 @Transactional(readOnly=true) public List<ContestProblemResponse> problems(Long id,String username){Contest c=contest(id);if(c.derivedStatus()==ContestStatus.UPCOMING)throw new IllegalArgumentException("Contest problems are available when the contest starts.");if(!registrations.findByContestIdAndUserId(id,user(username).getId()).isPresent())throw new IllegalArgumentException("Register for this contest first.");return contestProblems.findByContestIdOrderByDisplayOrderAsc(id).stream().map(ContestProblemResponse::from).toList();}
 @Transactional(readOnly=true) public void assertProblemAccess(Long id, Long problemId, String username){Contest c=contest(id);if(c.derivedStatus()!=ContestStatus.LIVE)throw new IllegalArgumentException("Contest problems are only available while the contest is live.");User u=user(username);if(registrations.findByContestIdAndUserId(id,u.getId()).isEmpty())throw new IllegalArgumentException("Register for this contest first.");if(contestProblems.findByContestIdAndProblemId(id,problemId).isEmpty())throw new IllegalArgumentException("Problem is not part of this contest.");}
 @Transactional(readOnly=true) public List<ContestStandingResponse> standings(Long id){Contest c=contest(id);List<ContestProblem> cps=contestProblems.findByContestIdOrderByDisplayOrderAsc(id);List<ContestStandingResponse> rows=new ArrayList<>();for(ContestRegistration reg:registrations.findByContestId(id)){List<Submission> userSubs=submissions.findByContestIdAndUserIdOrderBySubmittedAtDesc(id,reg.getUser().getId());int solved=0,penalty=0;LocalDateTime last=null;Map<Long,String> cells=new LinkedHashMap<>();for(ContestProblem cp:cps){List<Submission> p=userSubs.stream().filter(s->s.getContestProblem()!=null&&s.getContestProblem().getId().equals(cp.getId())).sorted(Comparator.comparing(Submission::getSubmittedAt)).toList();Optional<Submission> ac=p.stream().filter(s->"ACCEPTED".equals(s.getStatus())).findFirst();if(ac.isPresent()){solved++;int wrong=(int)p.stream().takeWhile(s->!s.getId().equals(ac.get().getId())).filter(s->"WRONG_ANSWER".equals(s.getStatus())).count();int mins=(int)Math.max(0,Duration.between(c.getStartAt(),ac.get().getSubmittedAt()).toMinutes());penalty+=mins+20*wrong;last=last==null||ac.get().getSubmittedAt().isAfter(last)?ac.get().getSubmittedAt():last;cells.put(cp.getProblem().getId(),"+"+(wrong>0?wrong:""));}else cells.put(cp.getProblem().getId(),p.isEmpty()?"—":"-"+p.stream().filter(s->"WRONG_ANSWER".equals(s.getStatus())).count());}rows.add(new ContestStandingResponse(0,reg.getUser().getId(),reg.getUser().getUsername(),solved,penalty,last,cells));}rows.sort(Comparator.comparing(ContestStandingResponse::solved).reversed().thenComparing(ContestStandingResponse::penalty).thenComparing(x->x.lastAcceptedAt()==null?LocalDateTime.MAX:x.lastAcceptedAt()).thenComparing(ContestStandingResponse::userId));for(int i=0;i<rows.size();i++){ContestStandingResponse x=rows.get(i);rows.set(i,new ContestStandingResponse(i+1,x.userId(),x.username(),x.solved(),x.penalty(),x.lastAcceptedAt(),x.problems()));}return rows;}
 private void validate(ContestRequest r){if(!r.endAt().isAfter(r.startAt()))throw new IllegalArgumentException("Contest end time must be after its start time.");if(r.visibility()==ContestVisibility.PRIVATE&&(r.accessCode()==null||r.accessCode().isBlank()))throw new IllegalArgumentException("Private contests require an access code.");} private void copy(Contest c,ContestRequest r){c.setTitle(r.title().trim());c.setSlug(r.slug().trim());c.setDescription(r.description());c.setRulesText(r.rulesText());c.setAccent(r.accent());c.setStartAt(r.startAt());c.setEndAt(r.endAt());c.setVisibility(r.visibility());c.setStatus(r.status()==null?ContestStatus.UPCOMING:r.status());if(r.accessCode()!=null&&!r.accessCode().isBlank())c.setAccessCodeHash(encoder.encode(r.accessCode()));}
 private String scheduleStatus(LocalDateTime startAt,LocalDateTime endAt,LocalDateTime now){return now.isBefore(startAt)?"UPCOMING":now.isBefore(endAt)?"LIVE":"ENDED";}
 private List<String> tags(String raw){return raw==null||raw.isBlank()?List.of():Arrays.stream(raw.split(",")).map(String::trim).filter(value->!value.isEmpty()).toList();}
 private void requirePositive(Long id){if(id==null||id<=0)throw new IllegalArgumentException("Contest id must be a positive number.");}
 private Contest adminContest(Long id){return contests.findById(id).orElseThrow(()->new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"Contest not found."));}
 private Contest contest(Long id){return contests.findById(id).orElseThrow(()->new RuntimeException("Contest not found."));} private User user(String n){return users.findByUsername(n).orElseThrow(()->new RuntimeException("Authenticated user not found."));}
}
