package com.leetcode.backend.service;
import com.leetcode.backend.dto.*; import com.leetcode.backend.model.*; import com.leetcode.backend.repository.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.*;
@Service public class ContestService {
 private final ContestRepository contests; private final ContestProblemRepository contestProblems; private final ContestRegistrationRepository registrations; private final ProblemRepository problems; private final UserRepository users; private final SubmissionRepository submissions; private final PasswordEncoder encoder;
 public ContestService(ContestRepository c,ContestProblemRepository cp,ContestRegistrationRepository r,ProblemRepository p,UserRepository u,SubmissionRepository s,PasswordEncoder e){contests=c;contestProblems=cp;registrations=r;problems=p;users=u;submissions=s;encoder=e;}
 @Transactional(readOnly=true) public List<ContestResponse> adminList(){return contests.findAll().stream().sorted(Comparator.comparing(Contest::getStartAt).reversed()).map(c->ContestResponse.from(c,false,registrations.countByContestId(c.getId()))).toList();}
 @Transactional(readOnly=true) public List<ContestResponse> list(String username){User u=user(username);return contests.findAll().stream().filter(c->c.getStatus()!=ContestStatus.DRAFT&&c.getStatus()!=ContestStatus.CANCELLED).filter(c->c.getVisibility()==ContestVisibility.PUBLIC||registrations.findByContestIdAndUserId(c.getId(),u.getId()).isPresent()).sorted(Comparator.comparing(Contest::getStartAt).reversed()).map(c->ContestResponse.from(c,registrations.findByContestIdAndUserId(c.getId(),u.getId()).isPresent(),registrations.countByContestId(c.getId()))).toList();}
 @Transactional(readOnly=true) public ContestResponse get(Long id,String username){Contest c=contest(id);User u=user(username);if(c.getVisibility()==ContestVisibility.PRIVATE&&!registrations.findByContestIdAndUserId(id,u.getId()).isPresent())throw new RuntimeException("Contest not found.");return ContestResponse.from(c,registrations.findByContestIdAndUserId(id,u.getId()).isPresent(),registrations.countByContestId(id));}
 @Transactional public ContestResponse create(ContestRequest r,String username){validate(r);if(contests.existsBySlug(r.slug()))throw new IllegalArgumentException("A contest already uses this slug.");Contest c=new Contest();copy(c,r);c.setCreatedBy(user(username));return ContestResponse.from(contests.save(c),false,0);}
 @Transactional public ContestResponse update(Long id,ContestRequest r){Contest c=contest(id);if(c.derivedStatus()==ContestStatus.LIVE||c.derivedStatus()==ContestStatus.ENDED)throw new IllegalArgumentException("A live or ended contest cannot be changed.");validate(r);copy(c,r);return ContestResponse.from(contests.save(c),false,registrations.countByContestId(id));}
 @Transactional public void register(Long id,String accessCode,String username){Contest c=contest(id);if(c.derivedStatus()==ContestStatus.ENDED||c.getStatus()==ContestStatus.CANCELLED||c.getStatus()==ContestStatus.DRAFT)throw new IllegalArgumentException("Registration is closed.");User u=user(username);if(c.getVisibility()==ContestVisibility.PRIVATE&&(accessCode==null||!encoder.matches(accessCode,c.getAccessCodeHash())))throw new IllegalArgumentException("Invalid contest access code.");if(registrations.findByContestIdAndUserId(id,u.getId()).isPresent())return;ContestRegistration entry=new ContestRegistration();entry.setContest(c);entry.setUser(u);registrations.save(entry);}
 @Transactional public ContestProblemResponse addProblem(Long id,ContestProblemRequest r){Contest c=contest(id);if(c.derivedStatus()==ContestStatus.LIVE||c.derivedStatus()==ContestStatus.ENDED)throw new IllegalArgumentException("Contest problems cannot change after the contest starts.");if(contestProblems.findByContestIdAndProblemId(id,r.problemId()).isPresent())throw new IllegalArgumentException("Problem is already in this contest.");ContestProblem cp=new ContestProblem();cp.setContest(c);cp.setProblem(problems.findById(r.problemId()).orElseThrow(()->new RuntimeException("Problem not found.")));cp.setDisplayOrder(contestProblems.findByContestIdOrderByDisplayOrderAsc(id).size()+1);cp.setPoints(r.points()==null?100:r.points());return ContestProblemResponse.from(contestProblems.save(cp));}
 @Transactional(readOnly=true) public List<ContestProblemResponse> problems(Long id,String username){Contest c=contest(id);if(c.derivedStatus()==ContestStatus.UPCOMING)throw new IllegalArgumentException("Contest problems are available when the contest starts.");if(!registrations.findByContestIdAndUserId(id,user(username).getId()).isPresent())throw new IllegalArgumentException("Register for this contest first.");return contestProblems.findByContestIdOrderByDisplayOrderAsc(id).stream().map(ContestProblemResponse::from).toList();}
 @Transactional(readOnly=true) public void assertProblemAccess(Long id, Long problemId, String username){Contest c=contest(id);if(c.derivedStatus()!=ContestStatus.LIVE)throw new IllegalArgumentException("Contest problems are only available while the contest is live.");User u=user(username);if(registrations.findByContestIdAndUserId(id,u.getId()).isEmpty())throw new IllegalArgumentException("Register for this contest first.");if(contestProblems.findByContestIdAndProblemId(id,problemId).isEmpty())throw new IllegalArgumentException("Problem is not part of this contest.");}
 @Transactional(readOnly=true) public List<ContestStandingResponse> standings(Long id){Contest c=contest(id);List<ContestProblem> cps=contestProblems.findByContestIdOrderByDisplayOrderAsc(id);List<ContestStandingResponse> rows=new ArrayList<>();for(ContestRegistration reg:registrations.findByContestId(id)){List<Submission> userSubs=submissions.findByContestIdAndUserIdOrderBySubmittedAtDesc(id,reg.getUser().getId());int solved=0,penalty=0;LocalDateTime last=null;Map<Long,String> cells=new LinkedHashMap<>();for(ContestProblem cp:cps){List<Submission> p=userSubs.stream().filter(s->s.getContestProblem()!=null&&s.getContestProblem().getId().equals(cp.getId())).sorted(Comparator.comparing(Submission::getSubmittedAt)).toList();Optional<Submission> ac=p.stream().filter(s->"ACCEPTED".equals(s.getStatus())).findFirst();if(ac.isPresent()){solved++;int wrong=(int)p.stream().takeWhile(s->!s.getId().equals(ac.get().getId())).filter(s->"WRONG_ANSWER".equals(s.getStatus())).count();int mins=(int)Math.max(0,Duration.between(c.getStartAt(),ac.get().getSubmittedAt()).toMinutes());penalty+=mins+20*wrong;last=last==null||ac.get().getSubmittedAt().isAfter(last)?ac.get().getSubmittedAt():last;cells.put(cp.getProblem().getId(),"+"+(wrong>0?wrong:""));}else cells.put(cp.getProblem().getId(),p.isEmpty()?"—":"-"+p.stream().filter(s->"WRONG_ANSWER".equals(s.getStatus())).count());}rows.add(new ContestStandingResponse(0,reg.getUser().getId(),reg.getUser().getUsername(),solved,penalty,last,cells));}rows.sort(Comparator.comparing(ContestStandingResponse::solved).reversed().thenComparing(ContestStandingResponse::penalty).thenComparing(x->x.lastAcceptedAt()==null?LocalDateTime.MAX:x.lastAcceptedAt()).thenComparing(ContestStandingResponse::userId));for(int i=0;i<rows.size();i++){ContestStandingResponse x=rows.get(i);rows.set(i,new ContestStandingResponse(i+1,x.userId(),x.username(),x.solved(),x.penalty(),x.lastAcceptedAt(),x.problems()));}return rows;}
 private void validate(ContestRequest r){if(!r.endAt().isAfter(r.startAt()))throw new IllegalArgumentException("Contest end time must be after its start time.");if(r.visibility()==ContestVisibility.PRIVATE&&(r.accessCode()==null||r.accessCode().isBlank()))throw new IllegalArgumentException("Private contests require an access code.");} private void copy(Contest c,ContestRequest r){c.setTitle(r.title().trim());c.setSlug(r.slug().trim());c.setDescription(r.description());c.setRulesText(r.rulesText());c.setAccent(r.accent());c.setStartAt(r.startAt());c.setEndAt(r.endAt());c.setVisibility(r.visibility());c.setStatus(r.status()==null?ContestStatus.UPCOMING:r.status());if(r.accessCode()!=null&&!r.accessCode().isBlank())c.setAccessCodeHash(encoder.encode(r.accessCode()));} private Contest contest(Long id){return contests.findById(id).orElseThrow(()->new RuntimeException("Contest not found."));} private User user(String n){return users.findByUsername(n).orElseThrow(()->new RuntimeException("Authenticated user not found."));}
}
