package com.leetcode.backend.service;

import com.leetcode.backend.model.*; import com.leetcode.backend.repository.*;
import org.slf4j.*; import org.springframework.beans.factory.annotation.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;

/** Persistent outbox. The unique user/type/entity key makes scheduler restarts safe. */
@Service public class NotificationDeliveryService {
 private static final Logger log=LoggerFactory.getLogger(NotificationDeliveryService.class);
 private final NotificationDeliveryRepository deliveries; private final UserRepository users; private final ContestRepository contests; private final ContestRegistrationRepository contestRegistrations; private final AssessmentRepository assessments; private final AssessmentProblemRepository assessmentProblems; private final EmailService mail; private final int reminderMinutes; private final List<Integer> assessmentReminderOffsets; private final AssessmentRegistrationRepository assessmentRegistrations; private final AssessmentInvitationRepository invitations; private final AssessmentAccessRepository assessmentAccesses;
 @Autowired public NotificationDeliveryService(NotificationDeliveryRepository d,UserRepository u,ContestRepository c,ContestRegistrationRepository cr,AssessmentRepository a,AssessmentRegistrationRepository ar,AssessmentInvitationRepository i,AssessmentAccessRepository aa,AssessmentProblemRepository ap,EmailService m,@Value("${verdixa.contest.reminder-minutes:10}")int contestMinutes,@Value("${verdixa.assessment.reminder-minutes:10}")int assessmentMinutes,@Value("${verdixa.assessment.reminder-offset-minutes:1440,30}")String reminderOffsets){deliveries=d;users=u;contests=c;contestRegistrations=cr;assessments=a;assessmentRegistrations=ar;invitations=i;assessmentAccesses=aa;assessmentProblems=ap;mail=m;reminderMinutes=assessmentMinutes;assessmentReminderOffsets=parseOffsets(reminderOffsets,assessmentMinutes);}
 /** Source-compatible constructor for focused tests and older integrations without assessment access records. */
 public NotificationDeliveryService(NotificationDeliveryRepository d,UserRepository u,ContestRepository c,ContestRegistrationRepository cr,AssessmentRepository a,AssessmentRegistrationRepository ar,AssessmentInvitationRepository i,AssessmentProblemRepository ap,EmailService m,int contestMinutes,int assessmentMinutes){deliveries=d;users=u;contests=c;contestRegistrations=cr;assessments=a;assessmentRegistrations=ar;invitations=i;assessmentAccesses=null;assessmentProblems=ap;mail=m;reminderMinutes=assessmentMinutes;assessmentReminderOffsets=List.of(assessmentMinutes);}
 /** Legacy constructor retained for contest-focused unit tests. */
 public NotificationDeliveryService(NotificationDeliveryRepository d,UserRepository u,ContestRepository c,ContestRegistrationRepository r,AssessmentRepository a,EmailService m,int minutes){deliveries=d;users=u;contests=c;contestRegistrations=r;assessments=a;assessmentRegistrations=null;invitations=null;assessmentAccesses=null;assessmentProblems=null;mail=m;reminderMinutes=minutes;assessmentReminderOffsets=List.of(minutes);}
 @Transactional public void queueContestAnnouncement(Long id){Contest c=contests.findById(id).orElseThrow(()->new RuntimeException("Contest not found."));if(c.getStatus()==ContestStatus.DRAFT||c.getStatus()==ContestStatus.CANCELLED)return;for(User user:users.findByEmailVerifiedTrue())queue(user,"CONTEST_ANNOUNCEMENT","CONTEST",id);}
 @Transactional public void queueAssessmentInvitation(User user,Long id){queue(user,"ASSESSMENT_PRIVATE_INVITATION","ASSESSMENT",id);}
 @Transactional public void queueAssessmentPublished(Long id){Assessment a=assessment(id);if(a.getVisibility()==AssessmentEnums.Visibility.PUBLIC){for(User user:users.findByEmailVerifiedTrue())queue(user,"ASSESSMENT_PUBLIC_ANNOUNCEMENT","ASSESSMENT",id);}}
 /** Private invitations are delivered from purpose-specific after-commit events so each email receives its own opaque token. */
 @Transactional public void queueAssessmentInvitations(Long id){}
 @Transactional public void queueAssessmentRegistration(Long id,Long userId){if(assessmentRegistrations==null)return;assessmentRegistrations.findByAssessmentId(id).stream().filter(r->r.getUser().getId().equals(userId)).findFirst().ifPresent(r->queue(r.getUser(),"ASSESSMENT_REGISTRATION_CONFIRMATION","ASSESSMENT",id));}
 @Transactional public void queueAssessmentUpdate(Long id){assessmentRecipients(id).forEach(u->queue(u,"ASSESSMENT_UPDATED","ASSESSMENT",id));}
 @Transactional public void queueAssessmentCancellation(Long id){assessmentRecipients(id).forEach(u->queue(u,"ASSESSMENT_CANCELLED","ASSESSMENT",id));}
 @Scheduled(fixedDelayString="${verdixa.notifications.scheduler-ms:60000}") @Transactional public void scheduleAndSend(){LocalDateTime now=LocalDateTime.now();for(Contest c:contests.findAll()){if(c.getStatus()==ContestStatus.DRAFT||c.getStatus()==ContestStatus.CANCELLED)continue;if(!c.getStartAt().isBefore(now)&&!c.getStartAt().isAfter(now.plusMinutes(reminderMinutes+1)))for(ContestRegistration r:contestRegistrations.findWithUserByContestIdOrderByRegisteredAtAsc(c.getId()))queue(r.getUser(),"CONTEST_TEN_MINUTE_REMINDER","CONTEST",c.getId());if(!c.getStartAt().isAfter(now)&&c.getStartAt().isAfter(now.minusMinutes(2)))for(ContestRegistration r:contestRegistrations.findWithUserByContestIdOrderByRegisteredAtAsc(c.getId()))queue(r.getUser(),"CONTEST_LIVE","CONTEST",c.getId());}if(assessmentRegistrations!=null){for(Assessment a:assessments.findAll()){if(a.getStatus()==AssessmentEnums.Status.CANCELLED||a.getStatus()==AssessmentEnums.Status.DRAFT)continue;for(Integer offset:assessmentReminderOffsets){LocalDateTime target=a.getStartAt().minusMinutes(offset);if(!target.isBefore(now.minusMinutes(2))&&!target.isAfter(now.plusMinutes(1)))for(User participant:verifiedAssessmentRecipients(a.getId()))queue(participant,"ASSESSMENT_REMINDER_"+offset+"M","ASSESSMENT",a.getId());}if(!a.getStartAt().isAfter(now)&&a.getStartAt().isAfter(now.minusMinutes(2)))for(User participant:verifiedAssessmentRecipients(a.getId()))queue(participant,"ASSESSMENT_LIVE","ASSESSMENT",a.getId());}}for(NotificationDelivery d:deliveries.findTop100ByStatusOrderByIdAsc(AssessmentEnums.DeliveryStatus.PENDING))send(d);}
 private static List<Integer> parseOffsets(String raw,int fallback){try{List<Integer> values=Arrays.stream(raw.split(",")).map(String::trim).filter(x->x.matches("\\d+")).map(Integer::parseInt).filter(x->x>0&&x<=10080).distinct().sorted(Comparator.reverseOrder()).toList();return values.isEmpty()?List.of(fallback):values;}catch(Exception ignored){return List.of(fallback);}} private List<User> verifiedAssessmentRecipients(Long id){if(assessmentAccesses==null)return List.of();return assessmentAccesses.findByAssessmentIdAndVerifiedAtIsNotNull(id).stream().map(AssessmentAccess::getParticipant).filter(Objects::nonNull).toList();} private List<User> assessmentRecipients(Long id){LinkedHashMap<Long,User> recipients=new LinkedHashMap<>();if(invitations!=null)invitations.findByAssessmentId(id).forEach(i->recipients.put(i.getUser().getId(),i.getUser()));if(assessmentRegistrations!=null)assessmentRegistrations.findByAssessmentId(id).forEach(r->recipients.put(r.getUser().getId(),r.getUser()));for(User participant:verifiedAssessmentRecipients(id))recipients.put(participant.getId(),participant);return new ArrayList<>(recipients.values());}
 private Assessment assessment(Long id){return assessments.findById(id).orElseThrow(()->new RuntimeException("Assessment not found."));}
 private void queue(User user,String type,String entity,Long id){if(user==null||!user.isEmailVerified()||deliveries.existsByUserIdAndTypeAndEntityTypeAndEntityId(user.getId(),type,entity,id))return;NotificationDelivery d=new NotificationDelivery();d.setUser(user);d.setType(type);d.setEntityType(entity);d.setEntityId(id);d.setRecipient(user.getEmail());deliveries.save(d);}
 private void send(NotificationDelivery d){d.setStatus(AssessmentEnums.DeliveryStatus.SENDING);d.setAttemptCount(d.getAttemptCount()+1);try{if("CONTEST".equals(d.getEntityType())){Contest c=contests.findById(d.getEntityId()).orElseThrow();mail.sendContestNotice(d.getRecipient(),d.getUser().getUsername(),c.getTitle(),c.getStartAt(),c.getEndAt(),c.getId(),d.getType());}else if("ASSESSMENT".equals(d.getEntityType())){Assessment a=assessment(d.getEntityId());int problems=assessmentProblems==null?0:assessmentProblems.findByAssessmentIdOrderByDisplayOrderAsc(a.getId()).size();mail.sendAssessmentNotice(d.getRecipient(),d.getUser().getUsername(),a.getTitle(),a.getCreator().getUsername(),a.getOrganization(),a.getDescription(),a.getStartAt(),a.getEndAt(),a.getRegistrationDeadline(),problems,a.isFullscreenRequired(),a.isMicrophoneRequired(),a.getId(),d.getType(),a.getVisibility()==AssessmentEnums.Visibility.PRIVATE?a.getInviteToken():null);if("ASSESSMENT_PRIVATE_INVITATION".equals(d.getType())&&invitations!=null)invitations.findByAssessmentIdAndUserId(a.getId(),d.getUser().getId()).ifPresent(i->i.setEmailSentAt(LocalDateTime.now()));}d.setStatus(AssessmentEnums.DeliveryStatus.SENT);d.setSentAt(LocalDateTime.now());}catch(Exception e){d.setStatus(d.getAttemptCount()>=3?AssessmentEnums.DeliveryStatus.FAILED:AssessmentEnums.DeliveryStatus.PENDING);d.setLastError(e.getMessage());log.warn("Notification {} delivery failed: {}",d.getId(),e.getClass().getSimpleName());}}
}
