package com.leetcode.backend.service;
import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile; import javax.crypto.*; import javax.crypto.spec.*; import java.nio.file.*; import java.security.SecureRandom; import java.util.*;
@Service public class VerificationDocumentStorage {
 private final Path root; private final SecretKey key; private final SecureRandom random=new SecureRandom();
 public VerificationDocumentStorage(@Value("${verdixa.verification.storage-path:${java.io.tmpdir}/verdixa-verification}") String path,@Value("${verdixa.verification.storage-key:}") String encoded){root=Paths.get(path).toAbsolutePath().normalize();try{Files.createDirectories(root);}catch(Exception e){throw new IllegalStateException("Verification storage cannot be initialized.",e);}if(encoded==null||encoded.isBlank()){key=null;}else{byte[] decoded;try{decoded=Base64.getDecoder().decode(encoded);}catch(IllegalArgumentException e){throw new IllegalStateException("VERIFICATION_STORAGE_KEY must be valid Base64.");}if(decoded.length!=16&&decoded.length!=24&&decoded.length!=32)throw new IllegalStateException("VERIFICATION_STORAGE_KEY must decode to 16, 24, or 32 bytes.");key=new SecretKeySpec(decoded,"AES");}}
 public record Stored(String name,long size,String contentType,String originalName){}
 public Stored store(MultipartFile file){try{if(file==null||file.isEmpty()||file.getSize()>8*1024*1024)throw new IllegalArgumentException("A document up to 8 MB is required.");byte[] bytes=file.getBytes();String type=detect(bytes);String declared=file.getContentType();if(type==null||declared==null||!type.equalsIgnoreCase(declared))throw new IllegalArgumentException("The declared MIME type and file signature must identify a JPEG, PNG, or PDF document.");if(key==null)throw new IllegalStateException("VERIFICATION_STORAGE_KEY must be configured before accepting identity documents.");byte[] iv=new byte[12];random.nextBytes(iv);Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,key,new GCMParameterSpec(128,iv));byte[] encrypted=cipher.doFinal(bytes);String name=UUID.randomUUID()+".bin";byte[] payload=new byte[iv.length+encrypted.length];System.arraycopy(iv,0,payload,0,iv.length);System.arraycopy(encrypted,0,payload,iv.length,encrypted.length);Path target=root.resolve(name).normalize();if(!target.getParent().equals(root))throw new IllegalArgumentException("Invalid storage target.");Files.write(target,payload,StandardOpenOption.CREATE_NEW);return new Stored(name,bytes.length,type,safeName(file.getOriginalFilename()));}catch(IllegalArgumentException|IllegalStateException e){throw e;}catch(Exception e){throw new IllegalStateException("Verification document could not be stored.",e);}}
 public byte[] read(String name){try{Path target=root.resolve(name).normalize();if(!target.getParent().equals(root))throw new IllegalArgumentException("Invalid document reference.");byte[] payload=Files.readAllBytes(target);byte[] iv=Arrays.copyOfRange(payload,0,12);Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key,new GCMParameterSpec(128,iv));return cipher.doFinal(Arrays.copyOfRange(payload,12,payload.length));}catch(Exception e){throw new IllegalStateException("Document cannot be read.",e);}}
 public void delete(String name){try{Path target=root.resolve(name).normalize();if(!target.getParent().equals(root))throw new IllegalArgumentException("Invalid document reference.");Files.deleteIfExists(target);}catch(Exception e){throw new IllegalStateException("Document could not be removed.",e);}}
 private String detect(byte[] b){if(b.length>4&&b[0]=='%'&&b[1]=='P'&&b[2]=='D'&&b[3]=='F')return "application/pdf";if(b.length>8&&(b[0]&255)==0x89&&b[1]=='P'&&b[2]=='N'&&b[3]=='G')return "image/png";if(b.length>3&&(b[0]&255)==0xff&&(b[1]&255)==0xd8&&(b[2]&255)==0xff)return "image/jpeg";return null;} private String safeName(String n){String value=n==null?"document":Paths.get(n).getFileName().toString();return value.replaceAll("[^A-Za-z0-9._ -]","_").substring(0,Math.min(200,value.length()));}
}
